const NSE_STOCKS = [
  // ===== LARGE CAP (50 stocks) - Nifty 50 Constituents =====
  {symbol:'RELIANCE',name:'Reliance Industries Ltd',sector:'Energy',cap:'large',basePrice:2950},
  {symbol:'TCS',name:'Tata Consultancy Services Ltd',sector:'IT',cap:'large',basePrice:3850},
  {symbol:'HDFCBANK',name:'HDFC Bank Ltd',sector:'Banking',cap:'large',basePrice:1720},
  {symbol:'INFY',name:'Infosys Ltd',sector:'IT',cap:'large',basePrice:1580},
  {symbol:'ICICIBANK',name:'ICICI Bank Ltd',sector:'Banking',cap:'large',basePrice:1280},
  {symbol:'HINDUNILVR',name:'Hindustan Unilever Ltd',sector:'FMCG',cap:'large',basePrice:2480},
  {symbol:'ITC',name:'ITC Ltd',sector:'FMCG',cap:'large',basePrice:465},
  {symbol:'SBIN',name:'State Bank of India',sector:'Banking',cap:'large',basePrice:820},
  {symbol:'BHARTIARTL',name:'Bharti Airtel Ltd',sector:'Telecom',cap:'large',basePrice:1650},
  {symbol:'KOTAKBANK',name:'Kotak Mahindra Bank Ltd',sector:'Banking',cap:'large',basePrice:1850},
  {symbol:'LT',name:'Larsen & Toubro Ltd',sector:'Infrastructure',cap:'large',basePrice:3520},
  {symbol:'AXISBANK',name:'Axis Bank Ltd',sector:'Banking',cap:'large',basePrice:1150},
  {symbol:'BAJFINANCE',name:'Bajaj Finance Ltd',sector:'Finance',cap:'large',basePrice:6800},
  {symbol:'MARUTI',name:'Maruti Suzuki India Ltd',sector:'Auto',cap:'large',basePrice:12500},
  {symbol:'TITAN',name:'Titan Company Ltd',sector:'Consumer',cap:'large',basePrice:3250},
  {symbol:'SUNPHARMA',name:'Sun Pharmaceutical Industries Ltd',sector:'Pharma',cap:'large',basePrice:1180},
  {symbol:'TATAMOTORS',name:'Tata Motors Ltd',sector:'Auto',cap:'large',basePrice:950},
  {symbol:'HCLTECH',name:'HCL Technologies Ltd',sector:'IT',cap:'large',basePrice:1520},
  {symbol:'NTPC',name:'NTPC Ltd',sector:'Power',cap:'large',basePrice:365},
  {symbol:'POWERGRID',name:'Power Grid Corporation of India Ltd',sector:'Power',cap:'large',basePrice:310},
  {symbol:'TATASTEEL',name:'Tata Steel Ltd',sector:'Metals',cap:'large',basePrice:155},
  {symbol:'ADANIENT',name:'Adani Enterprises Ltd',sector:'Infrastructure',cap:'large',basePrice:3100},
  {symbol:'NESTLEIND',name:'Nestle India Ltd',sector:'FMCG',cap:'large',basePrice:2400},
  {symbol:'ULTRACEMCO',name:'UltraTech Cement Ltd',sector:'Cement',cap:'large',basePrice:10200},
  {symbol:'WIPRO',name:'Wipro Ltd',sector:'IT',cap:'large',basePrice:480},
  {symbol:'M&M',name:'Mahindra & Mahindra Ltd',sector:'Auto',cap:'large',basePrice:2680},
  {symbol:'ONGC',name:'Oil and Natural Gas Corporation Ltd',sector:'Energy',cap:'large',basePrice:265},
  {symbol:'JSWSTEEL',name:'JSW Steel Ltd',sector:'Metals',cap:'large',basePrice:880},
  {symbol:'COALINDIA',name:'Coal India Ltd',sector:'Mining',cap:'large',basePrice:440},
  {symbol:'BAJAJFINSV',name:'Bajaj Finserv Ltd',sector:'Finance',cap:'large',basePrice:1680},
  {symbol:'DRREDDY',name:'Dr Reddys Laboratories Ltd',sector:'Pharma',cap:'large',basePrice:5900},
  {symbol:'CIPLA',name:'Cipla Ltd',sector:'Pharma',cap:'large',basePrice:1480},
  {symbol:'DIVISLAB',name:'Divi\'s Laboratories Ltd',sector:'Pharma',cap:'large',basePrice:3750},
  {symbol:'GRASIM',name:'Grasim Industries Ltd',sector:'Cement',cap:'large',basePrice:2350},
  {symbol:'BRITANNIA',name:'Britannia Industries Ltd',sector:'FMCG',cap:'large',basePrice:5100},
  {symbol:'HEROMOTOCO',name:'Hero MotoCorp Ltd',sector:'Auto',cap:'large',basePrice:4600},
  {symbol:'EICHERMOT',name:'Eicher Motors Ltd',sector:'Auto',cap:'large',basePrice:4200},
  {symbol:'APOLLOHOSP',name:'Apollo Hospitals Enterprise Ltd',sector:'Healthcare',cap:'large',basePrice:5800},
  {symbol:'BPCL',name:'Bharat Petroleum Corporation Ltd',sector:'Energy',cap:'large',basePrice:340},
  {symbol:'TATACONSUM',name:'Tata Consumer Products Ltd',sector:'FMCG',cap:'large',basePrice:1050},
  {symbol:'SBILIFE',name:'SBI Life Insurance Company Ltd',sector:'Insurance',cap:'large',basePrice:1520},
  {symbol:'INDUSINDBK',name:'IndusInd Bank Ltd',sector:'Banking',cap:'large',basePrice:1450},
  {symbol:'HDFCLIFE',name:'HDFC Life Insurance Company Ltd',sector:'Insurance',cap:'large',basePrice:640},
  {symbol:'ADANIPORTS',name:'Adani Ports and Special Economic Zone Ltd',sector:'Infrastructure',cap:'large',basePrice:1250},
  {symbol:'HINDALCO',name:'Hindalco Industries Ltd',sector:'Metals',cap:'large',basePrice:580},
  {symbol:'BAJAJ-AUTO',name:'Bajaj Auto Ltd',sector:'Auto',cap:'large',basePrice:8900},
  {symbol:'TECHM',name:'Tech Mahindra Ltd',sector:'IT',cap:'large',basePrice:1380},
  {symbol:'ASIANPAINT',name:'Asian Paints Ltd',sector:'Consumer',cap:'large',basePrice:2850},
  {symbol:'UPL',name:'UPL Ltd',sector:'Chemicals',cap:'large',basePrice:520},
  {symbol:'SHRIRAMFIN',name:'Shriram Finance Ltd',sector:'Finance',cap:'large',basePrice:2400},

  // ===== MID CAP (100 stocks) - Nifty Midcap 150 Representative =====
  {symbol:'PERSISTENT',name:'Persistent Systems Ltd',sector:'IT',cap:'mid',basePrice:5200},
  {symbol:'COFORGE',name:'Coforge Ltd',sector:'IT',cap:'mid',basePrice:5800},
  {symbol:'MPHASIS',name:'MphasiS Ltd',sector:'IT',cap:'mid',basePrice:2600},
  {symbol:'FEDERALBNK',name:'Federal Bank Ltd',sector:'Banking',cap:'mid',basePrice:168},
  {symbol:'ESCORTS',name:'Escorts Kubota Ltd',sector:'Auto',cap:'mid',basePrice:3400},
  {symbol:'AUROPHARMA',name:'Aurobindo Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:1280},
  {symbol:'CROMPTON',name:'Crompton Greaves Consumer Electricals Ltd',sector:'Consumer',cap:'mid',basePrice:380},
  {symbol:'MUTHOOTFIN',name:'Muthoot Finance Ltd',sector:'Finance',cap:'mid',basePrice:1850},
  {symbol:'CUMMINSIND',name:'Cummins India Ltd',sector:'Industrial',cap:'mid',basePrice:2800},
  {symbol:'POLYCAB',name:'Polycab India Ltd',sector:'Industrial',cap:'mid',basePrice:5600},
  {symbol:'TRENT',name:'Trent Ltd',sector:'Retail',cap:'mid',basePrice:4200},
  {symbol:'GODREJCP',name:'Godrej Consumer Products Ltd',sector:'FMCG',cap:'mid',basePrice:1350},
  {symbol:'VOLTAS',name:'Voltas Ltd',sector:'Consumer',cap:'mid',basePrice:1150},
  {symbol:'PIIND',name:'PI Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:3800},
  {symbol:'ASTRAL',name:'Astral Ltd',sector:'Industrial',cap:'mid',basePrice:1900},
  {symbol:'JUBLFOOD',name:'Jubilant FoodWorks Ltd',sector:'Consumer',cap:'mid',basePrice:580},
  {symbol:'MAXHEALTH',name:'Max Healthcare Institute Ltd',sector:'Healthcare',cap:'mid',basePrice:820},
  {symbol:'DMART',name:'Avenue Supermarts Ltd',sector:'Retail',cap:'mid',basePrice:4100},
  {symbol:'OBEROIRLTY',name:'Oberoi Realty Ltd',sector:'Real Estate',cap:'mid',basePrice:1600},
  {symbol:'TORNTPHARM',name:'Torrent Pharmaceuticals Ltd',sector:'Pharma',cap:'mid',basePrice:2600},
  {symbol:'BHARATFORG',name:'Bharat Forge Ltd',sector:'Industrial',cap:'mid',basePrice:1350},
  {symbol:'IDFCFIRSTB',name:'IDFC First Bank Ltd',sector:'Banking',cap:'mid',basePrice:82},
  {symbol:'LICHSGFIN',name:'LIC Housing Finance Ltd',sector:'Finance',cap:'mid',basePrice:620},
  {symbol:'PAGEIND',name:'Page Industries Ltd',sector:'Textiles',cap:'mid',basePrice:42000},
  {symbol:'PHOENIXLTD',name:'Phoenix Mills Ltd',sector:'Real Estate',cap:'mid',basePrice:1650},
  {symbol:'SOLARIND',name:'Solar Industries India Ltd',sector:'Chemicals',cap:'mid',basePrice:6800},
  {symbol:'ABCAPITAL',name:'Aditya Birla Capital Ltd',sector:'Finance',cap:'mid',basePrice:210},
  {symbol:'MFSL',name:'Max Financial Services Ltd',sector:'Insurance',cap:'mid',basePrice:1050},
  {symbol:'COLPAL',name:'Colgate-Palmolive India Ltd',sector:'FMCG',cap:'mid',basePrice:2700},
  {symbol:'AMBUJACEM',name:'Ambuja Cements Ltd',sector:'Cement',cap:'mid',basePrice:620},
  {symbol:'CONCOR',name:'Container Corporation of India Ltd',sector:'Logistics',cap:'mid',basePrice:880},
  {symbol:'IRCTC',name:'Indian Railway Catering and Tourism Corporation Ltd',sector:'Consumer',cap:'mid',basePrice:880},
  {symbol:'SAIL',name:'Steel Authority of India Ltd',sector:'Metals',cap:'mid',basePrice:130},
  {symbol:'CANBK',name:'Canara Bank',sector:'Banking',cap:'mid',basePrice:110},
  {symbol:'INDHOTEL',name:'Indian Hotels Company Ltd',sector:'Consumer',cap:'mid',basePrice:620},
  {symbol:'OFSS',name:'Oracle Financial Services Software Ltd',sector:'IT',cap:'mid',basePrice:5200},
  {symbol:'LUPIN',name:'Lupin Ltd',sector:'Pharma',cap:'mid',basePrice:1600},
  {symbol:'IPCALAB',name:'IPCA Laboratories Ltd',sector:'Pharma',cap:'mid',basePrice:1350},
  {symbol:'ABB',name:'ABB India Ltd',sector:'Industrial',cap:'mid',basePrice:5800},
  {symbol:'SIEMENS',name:'Siemens Ltd',sector:'Industrial',cap:'mid',basePrice:5400},
  {symbol:'HAVELLS',name:'Havells India Ltd',sector:'Consumer',cap:'mid',basePrice:1580},
  {symbol:'WHIRLPOOL',name:'Whirlpool of India Ltd',sector:'Consumer',cap:'mid',basePrice:1400},
  {symbol:'BALKRISIND',name:'Balkrishna Industries Ltd',sector:'Auto',cap:'mid',basePrice:2600},
  {symbol:'SUNDARMFIN',name:'Sundaram Finance Ltd',sector:'Finance',cap:'mid',basePrice:4200},
  {symbol:'MCDOWELL',name:'United Spirits Ltd',sector:'Consumer',cap:'mid',basePrice:6800},
  {symbol:'BERGEPAINT',name:'Berger Paints India Ltd',sector:'Consumer',cap:'mid',basePrice:550},
  {symbol:'PIDILITIND',name:'Pidilite Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:2750},
  {symbol:'ATUL',name:'Atul Ltd',sector:'Chemicals',cap:'mid',basePrice:6400},
  {symbol:'SYNGENE',name:'Syngene International Ltd',sector:'Healthcare',cap:'mid',basePrice:780},
  {symbol:'ALKEM',name:'Alkem Laboratories Ltd',sector:'Pharma',cap:'mid',basePrice:5200},
  {symbol:'BANDHANBNK',name:'Bandhan Bank Ltd',sector:'Banking',cap:'mid',basePrice:220},
  {symbol:'NAUKRI',name:'Info Edge India Ltd',sector:'Internet',cap:'mid',basePrice:5400},
  {symbol:'LTIM',name:'LTIMindtree Ltd',sector:'IT',cap:'mid',basePrice:5600},
  {symbol:'PETRONET',name:'Petronet LNG Ltd',sector:'Energy',cap:'mid',basePrice:260},
  {symbol:'GLAND',name:'Gland Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:1750},
  {symbol:'NHPC',name:'NHPC Ltd',sector:'Power',cap:'mid',basePrice:68},
  {symbol:'TATAPOWER',name:'Tata Power Company Ltd',sector:'Power',cap:'mid',basePrice:420},
  {symbol:'TATACOMM',name:'Tata Communications Ltd',sector:'Telecom',cap:'mid',basePrice:1780},
  {symbol:'BIOCON',name:'Biocon Ltd',sector:'Pharma',cap:'mid',basePrice:280},
  {symbol:'LAURUSLABS',name:'Laurus Labs Ltd',sector:'Pharma',cap:'mid',basePrice:420},
  {symbol:'MANAPPURAM',name:'Manappuram Finance Ltd',sector:'Finance',cap:'mid',basePrice:180},
  {symbol:'LINDEINDIA',name:'Linde India Ltd',sector:'Chemicals',cap:'mid',basePrice:6200},
  {symbol:'AUBANK',name:'AU Small Finance Bank Ltd',sector:'Banking',cap:'mid',basePrice:650},
  {symbol:'CHOLAFIN',name:'Cholamandalam Investment and Finance Co Ltd',sector:'Finance',cap:'mid',basePrice:1350},
  {symbol:'PNB',name:'Punjab National Bank',sector:'Banking',cap:'mid',basePrice:105},
  {symbol:'BANKBARODA',name:'Bank of Baroda',sector:'Banking',cap:'mid',basePrice:260},
  {symbol:'RECLTD',name:'REC Ltd',sector:'Finance',cap:'mid',basePrice:520},
  {symbol:'PFC',name:'Power Finance Corporation Ltd',sector:'Finance',cap:'mid',basePrice:480},
  {symbol:'NMDC',name:'NMDC Ltd',sector:'Mining',cap:'mid',basePrice:220},
  {symbol:'GODREJPROP',name:'Godrej Properties Ltd',sector:'Real Estate',cap:'mid',basePrice:2200},
  {symbol:'INDUSTOWER',name:'Indus Towers Ltd',sector:'Telecom',cap:'mid',basePrice:350},
  {symbol:'ZYDUSLIFE',name:'Zydus Lifesciences Ltd',sector:'Pharma',cap:'mid',basePrice:620},
  {symbol:'APLAPOLLO',name:'APL Apollo Tubes Ltd',sector:'Industrial',cap:'mid',basePrice:1650},
  {symbol:'DEEPAKNITRI',name:'Deepak Nitrite Ltd',sector:'Chemicals',cap:'mid',basePrice:2200},
  {symbol:'SCHAEFFLER',name:'Schaeffler India Ltd',sector:'Auto',cap:'mid',basePrice:3400},
  {symbol:'HONAUT',name:'Honeywell Automation India Ltd',sector:'Industrial',cap:'mid',basePrice:48000},
  {symbol:'GLAXO',name:'GlaxoSmithKline Pharmaceuticals Ltd',sector:'Pharma',cap:'mid',basePrice:1650},
  {symbol:'STARHEALTH',name:'Star Health and Allied Insurance Co Ltd',sector:'Insurance',cap:'mid',basePrice:580},
  {symbol:'SUPREMEIND',name:'Supreme Industries Ltd',sector:'Industrial',cap:'mid',basePrice:4800},
  {symbol:'THERMAX',name:'Thermax Ltd',sector:'Industrial',cap:'mid',basePrice:3200},
  {symbol:'RATNAMANI',name:'Ratnamani Metals and Tubes Ltd',sector:'Industrial',cap:'mid',basePrice:3100},
  {symbol:'SUNDRMFAST',name:'Sundram Fasteners Ltd',sector:'Auto',cap:'mid',basePrice:1150},
  {symbol:'NATCO',name:'Natco Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:880},
  {symbol:'KANSAINER',name:'Kansai Nerolac Paints Ltd',sector:'Consumer',cap:'mid',basePrice:420},
  {symbol:'JKCEMENT',name:'JK Cement Ltd',sector:'Cement',cap:'mid',basePrice:4200},
  {symbol:'TVSMOTOR',name:'TVS Motor Company Ltd',sector:'Auto',cap:'mid',basePrice:2200},
  {symbol:'ACC',name:'ACC Ltd',sector:'Cement',cap:'mid',basePrice:2450},
  {symbol:'EMAMILTD',name:'Emami Ltd',sector:'FMCG',cap:'mid',basePrice:620},
  {symbol:'PRESTIGE',name:'Prestige Estates Projects Ltd',sector:'Real Estate',cap:'mid',basePrice:1250},
  {symbol:'KAJARIACER',name:'Kajaria Ceramics Ltd',sector:'Consumer',cap:'mid',basePrice:1350},
  {symbol:'ZEEL',name:'Zee Entertainment Enterprises Ltd',sector:'Media',cap:'mid',basePrice:145},
  {symbol:'RAMCOCEM',name:'Ramco Cements Ltd',sector:'Cement',cap:'mid',basePrice:920},
  {symbol:'TATACHEM',name:'Tata Chemicals Ltd',sector:'Chemicals',cap:'mid',basePrice:1080},
  {symbol:'SUMICHEM',name:'Sumitomo Chemical India Ltd',sector:'Chemicals',cap:'mid',basePrice:420},
  {symbol:'NIACL',name:'New India Assurance Company Ltd',sector:'Insurance',cap:'mid',basePrice:195},
  {symbol:'SPARC',name:'Sun Pharma Advanced Research Company Ltd',sector:'Pharma',cap:'mid',basePrice:310},
  {symbol:'CENTRALBK',name:'Central Bank of India',sector:'Banking',cap:'mid',basePrice:62},
  {symbol:'MARICO',name:'Marico Ltd',sector:'FMCG',cap:'mid',basePrice:580},
  {symbol:'DABUR',name:'Dabur India Ltd',sector:'FMCG',cap:'mid',basePrice:560},
  {symbol:'SUNTV',name:'Sun TV Network Ltd',sector:'Media',cap:'mid',basePrice:620},

  // ===== SMALL CAP (100 stocks) - Nifty Smallcap 250 Representative =====
  {symbol:'CDSL',name:'Central Depository Services India Ltd',sector:'Fintech',cap:'small',basePrice:1800},
  {symbol:'KPITTECH',name:'KPIT Technologies Ltd',sector:'IT',cap:'small',basePrice:1450},
  {symbol:'DEEPAKNTR',name:'Deepak Fertilisers and Petrochemicals Ltd',sector:'Chemicals',cap:'small',basePrice:2200},
  {symbol:'MAZDOCK',name:'Mazagon Dock Shipbuilders Ltd',sector:'Defence',cap:'small',basePrice:3800},
  {symbol:'BEL',name:'Bharat Electronics Ltd',sector:'Defence',cap:'small',basePrice:280},
  {symbol:'HAL',name:'Hindustan Aeronautics Ltd',sector:'Defence',cap:'small',basePrice:4200},
  {symbol:'COCHINSHIP',name:'Cochin Shipyard Ltd',sector:'Defence',cap:'small',basePrice:1800},
  {symbol:'IRFC',name:'Indian Railway Finance Corporation Ltd',sector:'Finance',cap:'small',basePrice:160},
  {symbol:'ZOMATO',name:'Zomato Ltd',sector:'Internet',cap:'small',basePrice:240},
  {symbol:'PAYTM',name:'One97 Communications Ltd',sector:'Fintech',cap:'small',basePrice:780},
  {symbol:'JIOFIN',name:'Jio Financial Services Ltd',sector:'Fintech',cap:'small',basePrice:310},
  {symbol:'POLICYBZR',name:'PB Fintech Ltd',sector:'Fintech',cap:'small',basePrice:1650},
  {symbol:'DELHIVERY',name:'Delhivery Ltd',sector:'Logistics',cap:'small',basePrice:420},
  {symbol:'AFFLE',name:'Affle India Ltd',sector:'IT',cap:'small',basePrice:1180},
  {symbol:'CLEAN',name:'Clean Science and Technology Ltd',sector:'Chemicals',cap:'small',basePrice:1500},
  {symbol:'FINEORG',name:'Fine Organic Industries Ltd',sector:'Chemicals',cap:'small',basePrice:4800},
  {symbol:'GRINDWELL',name:'Grindwell Norton Ltd',sector:'Industrial',cap:'small',basePrice:2100},
  {symbol:'HAPPSTMNDS',name:'Happiest Minds Technologies Ltd',sector:'IT',cap:'small',basePrice:780},
  {symbol:'ROUTE',name:'Route Mobile Ltd',sector:'IT',cap:'small',basePrice:1650},
  {symbol:'TANLA',name:'Tanla Platforms Ltd',sector:'IT',cap:'small',basePrice:920},
  {symbol:'DATAPATTNS',name:'Data Patterns India Ltd',sector:'Defence',cap:'small',basePrice:2400},
  {symbol:'IDEAFORGE',name:'Ideaforge Technology Ltd',sector:'Defence',cap:'small',basePrice:680},
  {symbol:'SYRMA',name:'Syrma SGS Technology Ltd',sector:'Electronics',cap:'small',basePrice:420},
  {symbol:'KAYNES',name:'Kaynes Technology India Ltd',sector:'Electronics',cap:'small',basePrice:3800},
  {symbol:'DIXON',name:'Dixon Technologies India Ltd',sector:'Electronics',cap:'small',basePrice:5200},
  {symbol:'AMBER',name:'Amber Enterprises India Ltd',sector:'Electronics',cap:'small',basePrice:3400},
  {symbol:'OLECTRA',name:'Olectra Greentech Ltd',sector:'EV',cap:'small',basePrice:1350},
  {symbol:'TATAELXSI',name:'Tata Elxsi Ltd',sector:'IT',cap:'small',basePrice:6800},
  {symbol:'SONACOMS',name:'Sona BLW Precision Forgings Ltd',sector:'Auto',cap:'small',basePrice:620},
  {symbol:'CRAFTSMAN',name:'Craftsman Automation Ltd',sector:'Auto',cap:'small',basePrice:4800},
  {symbol:'CARTRADE',name:'CarTrade Tech Ltd',sector:'Internet',cap:'small',basePrice:820},
  {symbol:'YATHARTH',name:'Yatharth Hospital and Trauma Care Services Ltd',sector:'Healthcare',cap:'small',basePrice:520},
  {symbol:'MEDANTA',name:'Global Health Ltd',sector:'Healthcare',cap:'small',basePrice:1350},
  {symbol:'RAINBOW',name:'Rainbow Childrens Medicare Ltd',sector:'Healthcare',cap:'small',basePrice:1450},
  {symbol:'AAVAS',name:'Aavas Financiers Ltd',sector:'Finance',cap:'small',basePrice:1650},
  {symbol:'HOMEFIRST',name:'Home First Finance Company India Ltd',sector:'Finance',cap:'small',basePrice:950},
  {symbol:'APTUS',name:'Aptus Value Housing Finance India Ltd',sector:'Finance',cap:'small',basePrice:340},
  {symbol:'CAMPUS',name:'Campus Activewear Ltd',sector:'Consumer',cap:'small',basePrice:280},
  {symbol:'METROBRAND',name:'Metro Brands Ltd',sector:'Retail',cap:'small',basePrice:1250},
  {symbol:'GPIL',name:'Godawari Power and Ispat Ltd',sector:'Metals',cap:'small',basePrice:680},
  {symbol:'RVNL',name:'Rail Vikas Nigam Ltd',sector:'Infrastructure',cap:'small',basePrice:260},
  {symbol:'IRCON',name:'Ircon International Ltd',sector:'Infrastructure',cap:'small',basePrice:220},
  {symbol:'NBCC',name:'NBCC India Ltd',sector:'Infrastructure',cap:'small',basePrice:140},
  {symbol:'ENGINERSIN',name:'Engineers India Ltd',sector:'Infrastructure',cap:'small',basePrice:210},
  {symbol:'EASEMYTRIP',name:'Easy Trip Planners Ltd',sector:'Internet',cap:'small',basePrice:38},
  {symbol:'IXIGO',name:'Le Travenues Technology Ltd',sector:'Internet',cap:'small',basePrice:155},
  {symbol:'RATEGAIN',name:'RateGain Travel Technologies Ltd',sector:'IT',cap:'small',basePrice:680},
  {symbol:'LATENTVIEW',name:'Latent View Analytics Ltd',sector:'IT',cap:'small',basePrice:420},
  {symbol:'INTELLECT',name:'Intellect Design Arena Ltd',sector:'IT',cap:'small',basePrice:780},
  {symbol:'MASTEK',name:'Mastek Ltd',sector:'IT',cap:'small',basePrice:2600},
  {symbol:'BIRLASOFT',name:'Birlasoft Ltd',sector:'IT',cap:'small',basePrice:580},
  {symbol:'ZENSAR',name:'Zensar Technologies Ltd',sector:'IT',cap:'small',basePrice:520},
  {symbol:'NUVAMA',name:'Nuvama Wealth Management Ltd',sector:'Finance',cap:'small',basePrice:5200},
  {symbol:'ANGELONE',name:'Angel One Ltd',sector:'Fintech',cap:'small',basePrice:2800},
  {symbol:'MOTILALOFS',name:'Motilal Oswal Financial Services Ltd',sector:'Finance',cap:'small',basePrice:1850},
  {symbol:'CAMS',name:'Computer Age Management Services Ltd',sector:'Fintech',cap:'small',basePrice:3200},
  {symbol:'JBCHEPHARM',name:'JB Chemicals and Pharmaceuticals Ltd',sector:'Pharma',cap:'small',basePrice:1750},
  {symbol:'SUPRIYA',name:'Supriya Lifescience Ltd',sector:'Pharma',cap:'small',basePrice:480},
  {symbol:'LXCHEM',name:'Laxmi Organic Industries Ltd',sector:'Chemicals',cap:'small',basePrice:280},
  {symbol:'TATVA',name:'Tatva Chintan Pharma Chem Ltd',sector:'Chemicals',cap:'small',basePrice:1850},
  {symbol:'GALAXYSURF',name:'Galaxy Surfactants Ltd',sector:'Chemicals',cap:'small',basePrice:2800},
  {symbol:'FLUOROCHEM',name:'Gujarat Fluorochemicals Ltd',sector:'Chemicals',cap:'small',basePrice:3200},
  {symbol:'ANANDRATHI',name:'Anand Rathi Wealth Ltd',sector:'Finance',cap:'small',basePrice:4200},
  {symbol:'FIVESTAR',name:'Five-Star Business Finance Ltd',sector:'Finance',cap:'small',basePrice:780},
  {symbol:'JKLAKSHMI',name:'JK Lakshmi Cement Ltd',sector:'Cement',cap:'small',basePrice:820},
  {symbol:'STARCEMENT',name:'Star Cement Ltd',sector:'Cement',cap:'small',basePrice:210},
  {symbol:'RADICO',name:'Radico Khaitan Ltd',sector:'Consumer',cap:'small',basePrice:1650},
  {symbol:'GLOBUSSPR',name:'Globus Spirits Ltd',sector:'Consumer',cap:'small',basePrice:1050},
  {symbol:'SAPPHIRE',name:'Sapphire Foods India Ltd',sector:'Consumer',cap:'small',basePrice:1450},
  {symbol:'DEVYANI',name:'Devyani International Ltd',sector:'Consumer',cap:'small',basePrice:165},
  {symbol:'SHOPERSTOP',name:'Shoppers Stop Ltd',sector:'Retail',cap:'small',basePrice:780},
  {symbol:'VMART',name:'V-Mart Retail Ltd',sector:'Retail',cap:'small',basePrice:2200},
  {symbol:'TEGA',name:'Tega Industries Ltd',sector:'Industrial',cap:'small',basePrice:1450},
  {symbol:'CERA',name:'Cera Sanitaryware Ltd',sector:'Consumer',cap:'small',basePrice:7200},
  {symbol:'ELGIEQUIP',name:'Elgi Equipments Ltd',sector:'Industrial',cap:'small',basePrice:580},
  {symbol:'TIMKEN',name:'Timken India Ltd',sector:'Industrial',cap:'small',basePrice:3400},
  {symbol:'PRAJ',name:'Praj Industries Ltd',sector:'Industrial',cap:'small',basePrice:520},
  {symbol:'GPPL',name:'Gujarat Pipavav Port Ltd',sector:'Logistics',cap:'small',basePrice:165},
  {symbol:'TCI',name:'Transport Corporation of India Ltd',sector:'Logistics',cap:'small',basePrice:880},
  {symbol:'BLUESTARCO',name:'Blue Star Ltd',sector:'Consumer',cap:'small',basePrice:1250},
  {symbol:'CENTURYTEX',name:'Century Textiles and Industries Ltd',sector:'Textiles',cap:'small',basePrice:1650},
  {symbol:'RAYMOND',name:'Raymond Ltd',sector:'Textiles',cap:'small',basePrice:1850},
  {symbol:'TVSSRICHAK',name:'TVS Srichakra Ltd',sector:'Auto',cap:'small',basePrice:3200},
  {symbol:'GRSE',name:'Garden Reach Shipbuilders and Engineers Ltd',sector:'Defence',cap:'small',basePrice:2100},
  {symbol:'BDL',name:'Bharat Dynamics Ltd',sector:'Defence',cap:'small',basePrice:1250},
  {symbol:'JSWENERGY',name:'JSW Energy Ltd',sector:'Power',cap:'small',basePrice:480},
  {symbol:'SJVN',name:'SJVN Ltd',sector:'Power',cap:'small',basePrice:120},
  {symbol:'POWERMECH',name:'Power Mech Projects Ltd',sector:'Infrastructure',cap:'small',basePrice:4800},
  {symbol:'PRICOLLTD',name:'Pricol Ltd',sector:'Auto',cap:'small',basePrice:480},
  {symbol:'ELECON',name:'Elecon Engineering Company Ltd',sector:'Industrial',cap:'small',basePrice:580},
  {symbol:'SENCO',name:'Senco Gold Ltd',sector:'Consumer',cap:'small',basePrice:1050},
  {symbol:'KALYANKJIL',name:'Kalyan Jewellers India Ltd',sector:'Consumer',cap:'small',basePrice:480},
  {symbol:'NETWORK18',name:'Network18 Media and Investments Ltd',sector:'Media',cap:'small',basePrice:82},
  {symbol:'NAZARA',name:'Nazara Technologies Ltd',sector:'Media',cap:'small',basePrice:780},
  {symbol:'PVRINOX',name:'PVR INOX Ltd',sector:'Media',cap:'small',basePrice:1450},
  {symbol:'ZAGGLE',name:'Zaggle Prepaid Ocean Services Ltd',sector:'Fintech',cap:'small',basePrice:340},
  {symbol:'RBLBANK',name:'RBL Bank Ltd',sector:'Banking',cap:'small',basePrice:240},
  {symbol:'UJJIVANSFB',name:'Ujjivan Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:48},
  {symbol:'EQUITASBNK',name:'Equitas Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:95},
  {symbol:'NYKAA',name:'FSN E-Commerce Ventures Ltd',sector:'Internet',cap:'small',basePrice:175},
];


const BSE_STOCKS = [
// === LARGE CAP (30 stocks) - Sensex 30 Constituents ===
{symbol:'RELIANCE',name:'Reliance Industries Ltd',sector:'Oil & Gas',cap:'large',basePrice:2950},
{symbol:'TCS',name:'Tata Consultancy Services Ltd',sector:'IT',cap:'large',basePrice:3850},
{symbol:'HDFCBANK',name:'HDFC Bank Ltd',sector:'Banking',cap:'large',basePrice:1720},
{symbol:'INFY',name:'Infosys Ltd',sector:'IT',cap:'large',basePrice:1580},
{symbol:'ICICIBANK',name:'ICICI Bank Ltd',sector:'Banking',cap:'large',basePrice:1280},
{symbol:'HINDUNILVR',name:'Hindustan Unilever Ltd',sector:'FMCG',cap:'large',basePrice:2480},
{symbol:'ITC',name:'ITC Ltd',sector:'FMCG',cap:'large',basePrice:465},
{symbol:'SBIN',name:'State Bank of India',sector:'Banking',cap:'large',basePrice:820},
{symbol:'BHARTIARTL',name:'Bharti Airtel Ltd',sector:'Telecom',cap:'large',basePrice:1650},
{symbol:'KOTAKBANK',name:'Kotak Mahindra Bank Ltd',sector:'Banking',cap:'large',basePrice:1850},
{symbol:'LT',name:'Larsen & Toubro Ltd',sector:'Engineering',cap:'large',basePrice:3520},
{symbol:'AXISBANK',name:'Axis Bank Ltd',sector:'Banking',cap:'large',basePrice:1150},
{symbol:'BAJFINANCE',name:'Bajaj Finance Ltd',sector:'Finance',cap:'large',basePrice:6800},
{symbol:'MARUTI',name:'Maruti Suzuki India Ltd',sector:'Auto',cap:'large',basePrice:12500},
{symbol:'TITAN',name:'Titan Company Ltd',sector:'Consumer',cap:'large',basePrice:3250},
{symbol:'SUNPHARMA',name:'Sun Pharmaceutical Industries Ltd',sector:'Pharma',cap:'large',basePrice:1180},
{symbol:'TATAMOTORS',name:'Tata Motors Ltd',sector:'Auto',cap:'large',basePrice:950},
{symbol:'HCLTECH',name:'HCL Technologies Ltd',sector:'IT',cap:'large',basePrice:1520},
{symbol:'NTPC',name:'NTPC Ltd',sector:'Power',cap:'large',basePrice:365},
{symbol:'POWERGRID',name:'Power Grid Corporation of India Ltd',sector:'Power',cap:'large',basePrice:310},
{symbol:'TATASTEEL',name:'Tata Steel Ltd',sector:'Metals',cap:'large',basePrice:155},
{symbol:'NESTLEIND',name:'Nestle India Ltd',sector:'FMCG',cap:'large',basePrice:2400},
{symbol:'ULTRACEMCO',name:'UltraTech Cement Ltd',sector:'Cement',cap:'large',basePrice:10200},
{symbol:'WIPRO',name:'Wipro Ltd',sector:'IT',cap:'large',basePrice:480},
{symbol:'M&M',name:'Mahindra & Mahindra Ltd',sector:'Auto',cap:'large',basePrice:2680},
{symbol:'TECHM',name:'Tech Mahindra Ltd',sector:'IT',cap:'large',basePrice:1380},
{symbol:'ASIANPAINT',name:'Asian Paints Ltd',sector:'Consumer',cap:'large',basePrice:2850},
{symbol:'INDUSINDBK',name:'IndusInd Bank Ltd',sector:'Banking',cap:'large',basePrice:1450},
{symbol:'BAJAJ-AUTO',name:'Bajaj Auto Ltd',sector:'Auto',cap:'large',basePrice:8900},
{symbol:'ADANIENT',name:'Adani Enterprises Ltd',sector:'Industrial',cap:'large',basePrice:3100},
// === MID CAP (100 stocks) ===
{symbol:'ATHER',name:'Ather Energy Ltd',sector:'EV',cap:'mid',basePrice:345},
{symbol:'ZOMATO',name:'Zomato Ltd',sector:'Internet',cap:'mid',basePrice:240},
{symbol:'PAYTM',name:'One 97 Communications Ltd',sector:'Fintech',cap:'mid',basePrice:780},
{symbol:'NYKAA',name:'FSN E-Commerce Ventures Ltd',sector:'E-Commerce',cap:'mid',basePrice:180},
{symbol:'POLICYBZR',name:'PB Fintech Ltd',sector:'Fintech',cap:'mid',basePrice:1650},
{symbol:'DELHIVERY',name:'Delhivery Ltd',sector:'Logistics',cap:'mid',basePrice:420},
{symbol:'MAPMYINDIA',name:'CE Info Systems Ltd',sector:'IT',cap:'mid',basePrice:1800},
{symbol:'IRCTC',name:'Indian Railway Catering & Tourism Corp Ltd',sector:'Travel',cap:'mid',basePrice:880},
{symbol:'TRENT',name:'Trent Ltd',sector:'Retail',cap:'mid',basePrice:4200},
{symbol:'MOTHERSON',name:'Samvardhana Motherson International Ltd',sector:'Auto',cap:'mid',basePrice:140},
{symbol:'VOLTAS',name:'Voltas Ltd',sector:'Consumer',cap:'mid',basePrice:1150},
{symbol:'MAXHEALTH',name:'Max Healthcare Institute Ltd',sector:'Healthcare',cap:'mid',basePrice:820},
{symbol:'OBEROIRLTY',name:'Oberoi Realty Ltd',sector:'Real Estate',cap:'mid',basePrice:1600},
{symbol:'PHOENIXLTD',name:'The Phoenix Mills Ltd',sector:'Real Estate',cap:'mid',basePrice:1650},
{symbol:'GODREJPROP',name:'Godrej Properties Ltd',sector:'Real Estate',cap:'mid',basePrice:2350},
{symbol:'PRESTIGE',name:'Prestige Estates Projects Ltd',sector:'Real Estate',cap:'mid',basePrice:1280},
{symbol:'MPHASIS',name:'MphasiS Ltd',sector:'IT',cap:'mid',basePrice:2450},
{symbol:'LTIM',name:'LTIMindtree Ltd',sector:'IT',cap:'mid',basePrice:5200},
{symbol:'COFORGE',name:'Coforge Ltd',sector:'IT',cap:'mid',basePrice:5800},
{symbol:'PERSISTENT',name:'Persistent Systems Ltd',sector:'IT',cap:'mid',basePrice:4500},
{symbol:'FEDERALBNK',name:'Federal Bank Ltd',sector:'Banking',cap:'mid',basePrice:165},
{symbol:'IDFCFIRSTB',name:'IDFC First Bank Ltd',sector:'Banking',cap:'mid',basePrice:72},
{symbol:'BANDHANBNK',name:'Bandhan Bank Ltd',sector:'Banking',cap:'mid',basePrice:210},
{symbol:'AUBANK',name:'AU Small Finance Bank Ltd',sector:'Banking',cap:'mid',basePrice:620},
{symbol:'MUTHOOTFIN',name:'Muthoot Finance Ltd',sector:'Finance',cap:'mid',basePrice:1750},
{symbol:'CHOLAFIN',name:'Cholamandalam Investment & Finance Co Ltd',sector:'Finance',cap:'mid',basePrice:1320},
{symbol:'SHRIRAMFIN',name:'Shriram Finance Ltd',sector:'Finance',cap:'mid',basePrice:2450},
{symbol:'MANAPPURAM',name:'Manappuram Finance Ltd',sector:'Finance',cap:'mid',basePrice:185},
{symbol:'PIIND',name:'PI Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:3650},
{symbol:'AARTIIND',name:'Aarti Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:580},
{symbol:'DEEPAKNITRO',name:'Deepak Nitrite Ltd',sector:'Chemicals',cap:'mid',basePrice:2100},
{symbol:'SOLARINDS',name:'Solar Industries India Ltd',sector:'Chemicals',cap:'mid',basePrice:8500},
{symbol:'ASTRAL',name:'Astral Ltd',sector:'Industrial',cap:'mid',basePrice:1900},
{symbol:'POLYCAB',name:'Polycab India Ltd',sector:'Industrial',cap:'mid',basePrice:5600},
{symbol:'CUMMINSIND',name:'Cummins India Ltd',sector:'Engineering',cap:'mid',basePrice:2500},
{symbol:'APLAPOLLO',name:'APL Apollo Tubes Ltd',sector:'Industrial',cap:'mid',basePrice:1550},
{symbol:'SUPREMEIND',name:'Supreme Industries Ltd',sector:'Industrial',cap:'mid',basePrice:4800},
{symbol:'PAGEIND',name:'Page Industries Ltd',sector:'Textiles',cap:'mid',basePrice:38000},
{symbol:'DIXON',name:'Dixon Technologies India Ltd',sector:'Electronics',cap:'mid',basePrice:5400},
{symbol:'HONAUT',name:'Honeywell Automation India Ltd',sector:'Industrial',cap:'mid',basePrice:42000},
{symbol:'SCHAEFFLER',name:'Schaeffler India Ltd',sector:'Engineering',cap:'mid',basePrice:3200},
{symbol:'SYNGENE',name:'Syngene International Ltd',sector:'Pharma',cap:'mid',basePrice:780},
{symbol:'AUROPHARMA',name:'Aurobindo Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:1150},
{symbol:'ALKEM',name:'Alkem Laboratories Ltd',sector:'Pharma',cap:'mid',basePrice:5200},
{symbol:'LAURUSLABS',name:'Laurus Labs Ltd',sector:'Pharma',cap:'mid',basePrice:420},
{symbol:'IPCALAB',name:'IPCA Laboratories Ltd',sector:'Pharma',cap:'mid',basePrice:1350},
{symbol:'TORNTPHARM',name:'Torrent Pharmaceuticals Ltd',sector:'Pharma',cap:'mid',basePrice:2600},
{symbol:'JUBLFOOD',name:'Jubilant FoodWorks Ltd',sector:'QSR',cap:'mid',basePrice:520},
{symbol:'DEVYANI',name:'Devyani International Ltd',sector:'QSR',cap:'mid',basePrice:165},
{symbol:'INDIANHOTELS',name:'The Indian Hotels Company Ltd',sector:'Hospitality',cap:'mid',basePrice:580},
{symbol:'LEMONTR',name:'Lemon Tree Hotels Ltd',sector:'Hospitality',cap:'mid',basePrice:125},
{symbol:'CROMPTON',name:'Crompton Greaves Consumer Electricals Ltd',sector:'Consumer',cap:'mid',basePrice:340},
{symbol:'HAVELLS',name:'Havells India Ltd',sector:'Consumer',cap:'mid',basePrice:1480},
{symbol:'WHIRLPOOL',name:'Whirlpool of India Ltd',sector:'Consumer',cap:'mid',basePrice:1350},
{symbol:'BLUESTARLT',name:'Blue Star Ltd',sector:'Consumer',cap:'mid',basePrice:1250},
{symbol:'METROBRAND',name:'Metro Brands Ltd',sector:'Retail',cap:'mid',basePrice:1200},
{symbol:'VMART',name:'V-Mart Retail Ltd',sector:'Retail',cap:'mid',basePrice:2100},
{symbol:'ABFRL',name:'Aditya Birla Fashion & Retail Ltd',sector:'Retail',cap:'mid',basePrice:220},
{symbol:'MEDANTA',name:'Global Health Ltd',sector:'Healthcare',cap:'mid',basePrice:1450},
{symbol:'FORTIS',name:'Fortis Healthcare Ltd',sector:'Healthcare',cap:'mid',basePrice:480},
{symbol:'KIMS',name:'Krishna Institute of Medical Sciences Ltd',sector:'Healthcare',cap:'mid',basePrice:2200},
{symbol:'IIFL',name:'IIFL Finance Ltd',sector:'Finance',cap:'mid',basePrice:450},
{symbol:'ANGELONE',name:'Angel One Ltd',sector:'Finance',cap:'mid',basePrice:2400},
{symbol:'BSOFT',name:'Birlasoft Ltd',sector:'IT',cap:'mid',basePrice:620},
{symbol:'ROUTE',name:'Route Mobile Ltd',sector:'IT',cap:'mid',basePrice:1650},
{symbol:'TANLA',name:'Tanla Platforms Ltd',sector:'IT',cap:'mid',basePrice:980},
{symbol:'ZEEL',name:'Zee Entertainment Enterprises Ltd',sector:'Media',cap:'mid',basePrice:135},
{symbol:'PVRINOX',name:'PVR INOX Ltd',sector:'Entertainment',cap:'small',basePrice:1400},
{symbol:'SUNTV',name:'Sun TV Network Ltd',sector:'Media',cap:'mid',basePrice:620},
{symbol:'CONCOR',name:'Container Corporation of India Ltd',sector:'Logistics',cap:'mid',basePrice:780},
{symbol:'RVNL',name:'Rail Vikas Nigam Ltd',sector:'Engineering',cap:'mid',basePrice:250},
{symbol:'IRFC',name:'Indian Railway Finance Corporation Ltd',sector:'Finance',cap:'mid',basePrice:155},
{symbol:'RECLTD',name:'REC Ltd',sector:'Finance',cap:'mid',basePrice:480},
{symbol:'PFC',name:'Power Finance Corporation Ltd',sector:'Finance',cap:'mid',basePrice:420},
{symbol:'NHPC',name:'NHPC Ltd',sector:'Power',cap:'mid',basePrice:85},
{symbol:'SJVN',name:'SJVN Ltd',sector:'Power',cap:'mid',basePrice:115},
{symbol:'TORNTPOWER',name:'Torrent Power Ltd',sector:'Power',cap:'mid',basePrice:1650},
{symbol:'CESC',name:'CESC Ltd',sector:'Power',cap:'mid',basePrice:155},
{symbol:'TATAPOWER',name:'Tata Power Company Ltd',sector:'Power',cap:'mid',basePrice:420},
{symbol:'ADANIGREEN',name:'Adani Green Energy Ltd',sector:'Power',cap:'mid',basePrice:1750},
{symbol:'ADANIPORTS',name:'Adani Ports and Special Economic Zone Ltd',sector:'Logistics',cap:'mid',basePrice:1280},
{symbol:'GLAND',name:'Gland Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:1650},
{symbol:'BIOCON',name:'Biocon Ltd',sector:'Pharma',cap:'mid',basePrice:320},
{symbol:'CLEAN',name:'Clean Science and Technology Ltd',sector:'Chemicals',cap:'mid',basePrice:1450},
{symbol:'ATUL',name:'Atul Ltd',sector:'Chemicals',cap:'mid',basePrice:6200},
{symbol:'CARBORUNIV',name:'Carborundum Universal Ltd',sector:'Industrial',cap:'mid',basePrice:1150},
{symbol:'GRINDWELL',name:'Grindwell Norton Ltd',sector:'Industrial',cap:'mid',basePrice:2000},
{symbol:'TIINDIA',name:'Tube Investments of India Ltd',sector:'Industrial',cap:'mid',basePrice:3400},
{symbol:'BRIGADE',name:'Brigade Enterprises Ltd',sector:'Real Estate',cap:'mid',basePrice:1150},
{symbol:'LODHA',name:'Macrotech Developers Ltd',sector:'Real Estate',cap:'mid',basePrice:1350},
{symbol:'SONACOMS',name:'Sona BLW Precision Forgings Ltd',sector:'Auto',cap:'mid',basePrice:580},
{symbol:'HAPPSTMNDS',name:'Happiest Minds Technologies Ltd',sector:'IT',cap:'mid',basePrice:750},
{symbol:'INTELLECT',name:'Intellect Design Arena Ltd',sector:'IT',cap:'mid',basePrice:680},
{symbol:'FLUOROCHEM',name:'Gujarat Fluorochemicals Ltd',sector:'Chemicals',cap:'mid',basePrice:3200},
{symbol:'ESCORTS',name:'Escorts Kubota Ltd',sector:'Auto',cap:'mid',basePrice:3400},
{symbol:'EICHERMOT',name:'Eicher Motors Ltd',sector:'Auto',cap:'mid',basePrice:4500},
{symbol:'THERMAX',name:'Thermax Ltd',sector:'Engineering',cap:'mid',basePrice:3800},
{symbol:'CGPOWER',name:'CG Power and Industrial Solutions Ltd',sector:'Industrial',cap:'mid',basePrice:520},
{symbol:'BHEL',name:'Bharat Heavy Electricals Ltd',sector:'Engineering',cap:'mid',basePrice:245},
{symbol:'BEL',name:'Bharat Electronics Ltd',sector:'Defence',cap:'mid',basePrice:280},
{symbol:'HAL',name:'Hindustan Aeronautics Ltd',sector:'Defence',cap:'mid',basePrice:4200},
// === SMALL CAP (100 stocks) ===
{symbol:'OLACABS',name:'Ola Electric Mobility Ltd',sector:'EV',cap:'small',basePrice:85},
{symbol:'IDEAFORGE',name:'ideaForge Technology Ltd',sector:'Defence',cap:'small',basePrice:620},
{symbol:'YATHARTH',name:'Yatharth Hospital & Trauma Care Services Ltd',sector:'Healthcare',cap:'small',basePrice:520},
{symbol:'ZAGGLE',name:'Zaggle Prepaid Ocean Services Ltd',sector:'Fintech',cap:'small',basePrice:380},
{symbol:'NETWEB',name:'Netweb Technologies India Ltd',sector:'IT',cap:'small',basePrice:2400},
{symbol:'BONDADA',name:'Bondada Engineering Ltd',sector:'Engineering',cap:'small',basePrice:450},
{symbol:'JYOTICTL',name:'Jyoti CNC Automation Ltd',sector:'Engineering',cap:'small',basePrice:1100},
{symbol:'TBOTEK',name:'TBO Tek Ltd',sector:'Travel Tech',cap:'small',basePrice:1500},
{symbol:'JUNIPER',name:'Juniper Hotels Ltd',sector:'Hospitality',cap:'small',basePrice:420},
{symbol:'CELLO',name:'Cello World Ltd',sector:'Consumer',cap:'small',basePrice:750},
{symbol:'KAYNES',name:'Kaynes Technology India Ltd',sector:'Electronics',cap:'small',basePrice:3800},
{symbol:'EXICOM',name:'Exicom Tele-Systems Ltd',sector:'EV',cap:'small',basePrice:320},
{symbol:'DOMS',name:'DOMS Industries Ltd',sector:'Stationery',cap:'small',basePrice:2200},
{symbol:'SENCO',name:'Senco Gold Ltd',sector:'Jewellery',cap:'small',basePrice:1100},
{symbol:'SAMHI',name:'Samhi Hotels Ltd',sector:'Hospitality',cap:'small',basePrice:280},
{symbol:'CREDO',name:'Credo Brands Marketing Ltd',sector:'Fashion',cap:'small',basePrice:450},
{symbol:'RATEGAIN',name:'RateGain Travel Technologies Ltd',sector:'Travel Tech',cap:'small',basePrice:680},
{symbol:'SAPPHIRE',name:'Sapphire Foods India Ltd',sector:'QSR',cap:'small',basePrice:1400},
{symbol:'MEDPLUS',name:'MedPlus Health Services Ltd',sector:'Healthcare',cap:'small',basePrice:640},
{symbol:'CAMPUS',name:'Campus Activewear Ltd',sector:'Fashion',cap:'small',basePrice:265},
{symbol:'GPIL',name:'Godawari Power and Ispat Ltd',sector:'Metals',cap:'small',basePrice:850},
{symbol:'GALAXYSURF',name:'Galaxy Surfactants Ltd',sector:'Chemicals',cap:'small',basePrice:2600},
{symbol:'DATAPATTNS',name:'Data Patterns India Ltd',sector:'Defence',cap:'small',basePrice:2400},
{symbol:'PARAS',name:'Paras Defence and Space Technologies Ltd',sector:'Defence',cap:'small',basePrice:980},
{symbol:'MAZAGON',name:'Mazagon Dock Shipbuilders Ltd',sector:'Defence',cap:'small',basePrice:3800},
{symbol:'COCHINSHIP',name:'Cochin Shipyard Ltd',sector:'Defence',cap:'small',basePrice:1850},
{symbol:'GRSE',name:'Garden Reach Shipbuilders & Engineers Ltd',sector:'Defence',cap:'small',basePrice:2100},
{symbol:'LATENTVIEW',name:'Latent View Analytics Ltd',sector:'IT',cap:'small',basePrice:420},
{symbol:'CARTRADE',name:'CarTrade Tech Ltd',sector:'Internet',cap:'small',basePrice:850},
{symbol:'EASEMYTRIP',name:'Easy Trip Planners Ltd',sector:'Travel Tech',cap:'small',basePrice:38},
{symbol:'IXIGO',name:'Le Travenues Technology Ltd',sector:'Travel Tech',cap:'small',basePrice:145},
{symbol:'YATRA',name:'Yatra Online Ltd',sector:'Travel Tech',cap:'small',basePrice:120},
{symbol:'FIVESTAR',name:'Five-Star Business Finance Ltd',sector:'Finance',cap:'small',basePrice:720},
{symbol:'JBMA',name:'JB Chemicals & Pharmaceuticals Ltd',sector:'Pharma',cap:'small',basePrice:1750},
{symbol:'LXCHEM',name:'Laxmi Organic Industries Ltd',sector:'Chemicals',cap:'small',basePrice:265},
{symbol:'HOMEFIRST',name:'Home First Finance Company India Ltd',sector:'Finance',cap:'small',basePrice:950},
{symbol:'APTUS',name:'Aptus Value Housing Finance India Ltd',sector:'Finance',cap:'small',basePrice:320},
{symbol:'ELECTRONICA',name:'Electronica Plastic Machines Ltd',sector:'Industrial',cap:'small',basePrice:380},
{symbol:'MASTERTRUST',name:'Mastertrust Ltd',sector:'Finance',cap:'small',basePrice:240},
{symbol:'SYRMA',name:'Syrma SGS Technology Ltd',sector:'Electronics',cap:'small',basePrice:420},
{symbol:'AETHER',name:'Aether Industries Ltd',sector:'Chemicals',cap:'small',basePrice:850},
{symbol:'AVALON',name:'Avalon Technologies Ltd',sector:'Electronics',cap:'small',basePrice:580},
{symbol:'CYIENT',name:'Cyient Ltd',sector:'IT',cap:'small',basePrice:1650},
{symbol:'ZENTEC',name:'Zen Technologies Ltd',sector:'Defence',cap:'small',basePrice:1450},
{symbol:'DREAMFOLKS',name:'Dreamfolks Services Ltd',sector:'Travel Tech',cap:'small',basePrice:420},
{symbol:'EPIGRAL',name:'Epigral Ltd',sector:'Chemicals',cap:'small',basePrice:1650},
{symbol:'SHYAMMET',name:'Shyam Metalics and Energy Ltd',sector:'Metals',cap:'small',basePrice:620},
{symbol:'GRAVITA',name:'Gravita India Ltd',sector:'Metals',cap:'small',basePrice:1850},
{symbol:'CRAFTSMAN',name:'Craftsman Automation Ltd',sector:'Engineering',cap:'small',basePrice:4500},
{symbol:'TVSHLDGS',name:'TVS Holdings Ltd',sector:'Industrial',cap:'small',basePrice:8200},
{symbol:'BIKAJI',name:'Bikaji Foods International Ltd',sector:'FMCG',cap:'small',basePrice:650},
{symbol:'GOPAL',name:'Gopal Snacks Ltd',sector:'FMCG',cap:'small',basePrice:320},
{symbol:'MAMA',name:'Mama Earth (Honasa Consumer Ltd)',sector:'FMCG',cap:'small',basePrice:380},
{symbol:'SBFC',name:'SBFC Finance Ltd',sector:'Finance',cap:'small',basePrice:82},
{symbol:'SIGNATURE',name:'Signatureglobal India Ltd',sector:'Real Estate',cap:'small',basePrice:1350},
{symbol:'SOBHA',name:'Sobha Ltd',sector:'Real Estate',cap:'small',basePrice:1550},
{symbol:'RAYMOND',name:'Raymond Ltd',sector:'Textiles',cap:'small',basePrice:1650},
{symbol:'KFINTECH',name:'KFin Technologies Ltd',sector:'Fintech',cap:'small',basePrice:680},
{symbol:'CAMS',name:'Computer Age Management Services Ltd',sector:'Fintech',cap:'small',basePrice:3200},
{symbol:'JSWENERGY',name:'JSW Energy Ltd',sector:'Power',cap:'small',basePrice:520},
{symbol:'RENEW',name:'ReNew Energy Global Plc',sector:'Power',cap:'small',basePrice:450},
{symbol:'SWANENERGY',name:'Swan Energy Ltd',sector:'Industrial',cap:'small',basePrice:580},
{symbol:'MAZDOCK',name:'Mazagon Dock Ltd',sector:'Defence',cap:'small',basePrice:3500},
{symbol:'TRITURBINE',name:'Triveni Turbine Ltd',sector:'Engineering',cap:'small',basePrice:520},
{symbol:'ANURAS',name:'Anupam Rasayan India Ltd',sector:'Chemicals',cap:'small',basePrice:850},
{symbol:'MOTISONS',name:'Motisons Jewellers Ltd',sector:'Jewellery',cap:'small',basePrice:145},
{symbol:'KALYANKJIL',name:'Kalyan Jewellers India Ltd',sector:'Jewellery',cap:'small',basePrice:520},
{symbol:'PNBHOUSING',name:'PNB Housing Finance Ltd',sector:'Finance',cap:'small',basePrice:780},
{symbol:'EQUITAS',name:'Equitas Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:95},
{symbol:'UJJIVANSFB',name:'Ujjivan Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:42},
{symbol:'INDIGOPNTS',name:'Indigo Paints Ltd',sector:'Consumer',cap:'small',basePrice:1450},
{symbol:'KPITTECH',name:'KPIT Technologies Ltd',sector:'IT',cap:'small',basePrice:1350},
{symbol:'TATAELXSI',name:'Tata Elxsi Ltd',sector:'IT',cap:'small',basePrice:6800},
{symbol:'RRKABEL',name:'R R Kabel Ltd',sector:'Industrial',cap:'small',basePrice:1450},
{symbol:'JKCEMENT',name:'JK Cement Ltd',sector:'Cement',cap:'small',basePrice:3800},
{symbol:'RATNAMANI',name:'Ratnamani Metals & Tubes Ltd',sector:'Industrial',cap:'small',basePrice:3100},
{symbol:'HAPPYFORGE',name:'Happy Forgings Ltd',sector:'Engineering',cap:'small',basePrice:850},
{symbol:'WONDERLA',name:'Wonderla Holidays Ltd',sector:'Entertainment',cap:'small',basePrice:780},
{symbol:'IMAGICAA',name:'Imagicaaworld Entertainment Ltd',sector:'Entertainment',cap:'small',basePrice:65},
{symbol:'NAZARA',name:'Nazara Technologies Ltd',sector:'Entertainment',cap:'small',basePrice:820},
{symbol:'RAINBOW',name:'Rainbow Childrens Medicare Ltd',sector:'Healthcare',cap:'small',basePrice:1350},
{symbol:'SUPRIYA',name:'Supriya Lifescience Ltd',sector:'Pharma',cap:'small',basePrice:420},
{symbol:'WINDLAS',name:'Windlas Biotech Ltd',sector:'Pharma',cap:'small',basePrice:680},
{symbol:'EMUDHRA',name:'eMudhra Ltd',sector:'IT',cap:'small',basePrice:650},
{symbol:'TRACXN',name:'Tracxn Technologies Ltd',sector:'IT',cap:'small',basePrice:85},
{symbol:'INFOBEANS',name:'InfoBeans Technologies Ltd',sector:'IT',cap:'small',basePrice:420},
{symbol:'GPPL',name:'Gujarat Pipavav Port Ltd',sector:'Logistics',cap:'small',basePrice:185},
{symbol:'MAHLIFE',name:'Mahindra Lifespace Developers Ltd',sector:'Real Estate',cap:'small',basePrice:520},
{symbol:'REFEX',name:'Refex Industries Ltd',sector:'Industrial',cap:'small',basePrice:480},
{symbol:'FIEMIND',name:'Fiem Industries Ltd',sector:'Auto',cap:'small',basePrice:1250},
{symbol:'GREENPANEL',name:'Greenpanel Industries Ltd',sector:'Industrial',cap:'small',basePrice:320},
{symbol:'PENIND',name:'Pennar Industries Ltd',sector:'Engineering',cap:'small',basePrice:155},
{symbol:'HGINFRA',name:'H.G. Infra Engineering Ltd',sector:'Engineering',cap:'small',basePrice:1350},
{symbol:'WOCKPHARMA',name:'Wockhardt Ltd',sector:'Pharma',cap:'small',basePrice:580},
{symbol:'ROSSARI',name:'Rossari Biotech Ltd',sector:'Chemicals',cap:'small',basePrice:750},
{symbol:'ETHOSLTD',name:'Ethos Ltd',sector:'Retail',cap:'small',basePrice:2400},
{symbol:'GOCOLORS',name:'Go Fashion India Ltd',sector:'Fashion',cap:'small',basePrice:1050},
{symbol:'VEDANT',name:'Vedant Fashions Ltd',sector:'Fashion',cap:'small',basePrice:1150},
{symbol:'HARSHA',name:'Harsha Engineers International Ltd',sector:'Engineering',cap:'small',basePrice:450},
];


const NASDAQ_STOCKS = [
  // === LARGE CAP (100 stocks) — NASDAQ-100 Constituents ===
  {symbol:'AAPL',name:'Apple Inc.',sector:'Technology',cap:'large',basePrice:195,currency:'$'},
  {symbol:'MSFT',name:'Microsoft Corporation',sector:'Technology',cap:'large',basePrice:430,currency:'$'},
  {symbol:'GOOGL',name:'Alphabet Inc.',sector:'Technology',cap:'large',basePrice:175,currency:'$'},
  {symbol:'AMZN',name:'Amazon.com Inc.',sector:'E-Commerce',cap:'large',basePrice:185,currency:'$'},
  {symbol:'NVDA',name:'NVIDIA Corporation',sector:'Semiconductors',cap:'large',basePrice:135,currency:'$'},
  {symbol:'META',name:'Meta Platforms Inc.',sector:'Technology',cap:'large',basePrice:510,currency:'$'},
  {symbol:'TSLA',name:'Tesla Inc.',sector:'Auto/EV',cap:'large',basePrice:250,currency:'$'},
  {symbol:'AVGO',name:'Broadcom Inc.',sector:'Semiconductors',cap:'large',basePrice:165,currency:'$'},
  {symbol:'COST',name:'Costco Wholesale Corporation',sector:'Retail',cap:'large',basePrice:720,currency:'$'},
  {symbol:'NFLX',name:'Netflix Inc.',sector:'Entertainment',cap:'large',basePrice:630,currency:'$'},
  {symbol:'AMD',name:'Advanced Micro Devices Inc.',sector:'Semiconductors',cap:'large',basePrice:155,currency:'$'},
  {symbol:'ADBE',name:'Adobe Inc.',sector:'Software',cap:'large',basePrice:530,currency:'$'},
  {symbol:'PEP',name:'PepsiCo Inc.',sector:'Consumer',cap:'large',basePrice:175,currency:'$'},
  {symbol:'INTC',name:'Intel Corporation',sector:'Semiconductors',cap:'large',basePrice:32,currency:'$'},
  {symbol:'CMCSA',name:'Comcast Corporation',sector:'Media',cap:'large',basePrice:42,currency:'$'},
  {symbol:'QCOM',name:'Qualcomm Inc.',sector:'Semiconductors',cap:'large',basePrice:175,currency:'$'},
  {symbol:'INTU',name:'Intuit Inc.',sector:'Software',cap:'large',basePrice:620,currency:'$'},
  {symbol:'AMAT',name:'Applied Materials Inc.',sector:'Semiconductors',cap:'large',basePrice:195,currency:'$'},
  {symbol:'ISRG',name:'Intuitive Surgical Inc.',sector:'Healthcare',cap:'large',basePrice:400,currency:'$'},
  {symbol:'BKNG',name:'Booking Holdings Inc.',sector:'Travel',cap:'large',basePrice:3800,currency:'$'},
  {symbol:'LRCX',name:'Lam Research Corporation',sector:'Semiconductors',cap:'large',basePrice:920,currency:'$'},
  {symbol:'MU',name:'Micron Technology Inc.',sector:'Semiconductors',cap:'large',basePrice:110,currency:'$'},
  {symbol:'REGN',name:'Regeneron Pharmaceuticals Inc.',sector:'Biotech',cap:'large',basePrice:980,currency:'$'},
  {symbol:'KLAC',name:'KLA Corporation',sector:'Semiconductors',cap:'large',basePrice:680,currency:'$'},
  {symbol:'PANW',name:'Palo Alto Networks Inc.',sector:'Cybersecurity',cap:'large',basePrice:310,currency:'$'},
  {symbol:'SNPS',name:'Synopsys Inc.',sector:'Software',cap:'large',basePrice:540,currency:'$'},
  {symbol:'CDNS',name:'Cadence Design Systems Inc.',sector:'Software',cap:'large',basePrice:290,currency:'$'},
  {symbol:'MRVL',name:'Marvell Technology Inc.',sector:'Semiconductors',cap:'large',basePrice:72,currency:'$'},
  {symbol:'ABNB',name:'Airbnb Inc.',sector:'Travel',cap:'large',basePrice:150,currency:'$'},
  {symbol:'FTNT',name:'Fortinet Inc.',sector:'Cybersecurity',cap:'large',basePrice:75,currency:'$'},
  {symbol:'CRWD',name:'CrowdStrike Holdings Inc.',sector:'Cybersecurity',cap:'large',basePrice:320,currency:'$'},
  {symbol:'DDOG',name:'Datadog Inc.',sector:'Cloud',cap:'large',basePrice:125,currency:'$'},
  {symbol:'ZS',name:'Zscaler Inc.',sector:'Cybersecurity',cap:'large',basePrice:220,currency:'$'},
  {symbol:'LULU',name:'Lululemon Athletica Inc.',sector:'Retail',cap:'large',basePrice:420,currency:'$'},
  {symbol:'MDLZ',name:'Mondelez International Inc.',sector:'Consumer',cap:'large',basePrice:72,currency:'$'},
  {symbol:'GILD',name:'Gilead Sciences Inc.',sector:'Biotech',cap:'large',basePrice:85,currency:'$'},
  {symbol:'AMGN',name:'Amgen Inc.',sector:'Biotech',cap:'large',basePrice:290,currency:'$'},
  {symbol:'ADP',name:'Automatic Data Processing Inc.',sector:'Technology',cap:'large',basePrice:265,currency:'$'},
  {symbol:'CSX',name:'CSX Corporation',sector:'Technology',cap:'large',basePrice:35,currency:'$'},
  {symbol:'SBUX',name:'Starbucks Corporation',sector:'QSR',cap:'large',basePrice:95,currency:'$'},
  {symbol:'MNST',name:'Monster Beverage Corporation',sector:'Consumer',cap:'large',basePrice:56,currency:'$'},
  {symbol:'PYPL',name:'PayPal Holdings Inc.',sector:'Fintech',cap:'large',basePrice:65,currency:'$'},
  {symbol:'ORLY',name:'O\'Reilly Automotive Inc.',sector:'Retail',cap:'large',basePrice:1050,currency:'$'},
  {symbol:'CEG',name:'Constellation Energy Corp.',sector:'Technology',cap:'large',basePrice:180,currency:'$'},
  {symbol:'MELI',name:'MercadoLibre Inc.',sector:'E-Commerce',cap:'large',basePrice:1680,currency:'$'},
  {symbol:'TEAM',name:'Atlassian Corporation',sector:'Software',cap:'large',basePrice:240,currency:'$'},
  {symbol:'WDAY',name:'Workday Inc.',sector:'Cloud',cap:'large',basePrice:270,currency:'$'},
  {symbol:'CTAS',name:'Cintas Corporation',sector:'Consumer',cap:'large',basePrice:620,currency:'$'},
  {symbol:'VRSK',name:'Verisk Analytics Inc.',sector:'Technology',cap:'large',basePrice:245,currency:'$'},
  {symbol:'ROP',name:'Roper Technologies Inc.',sector:'Technology',cap:'large',basePrice:560,currency:'$'},
  {symbol:'ODFL',name:'Old Dominion Freight Line Inc.',sector:'Technology',cap:'large',basePrice:420,currency:'$'},
  {symbol:'IDXX',name:'IDEXX Laboratories Inc.',sector:'Healthcare',cap:'large',basePrice:520,currency:'$'},
  {symbol:'FAST',name:'Fastenal Company',sector:'Retail',cap:'large',basePrice:72,currency:'$'},
  {symbol:'EA',name:'Electronic Arts Inc.',sector:'Gaming',cap:'large',basePrice:140,currency:'$'},
  {symbol:'ANSS',name:'ANSYS Inc.',sector:'Software',cap:'large',basePrice:330,currency:'$'},
  {symbol:'DXCM',name:'DexCom Inc.',sector:'Healthcare',cap:'large',basePrice:120,currency:'$'},
  {symbol:'PCAR',name:'PACCAR Inc.',sector:'Auto/EV',cap:'large',basePrice:95,currency:'$'},
  {symbol:'CPRT',name:'Copart Inc.',sector:'Technology',cap:'large',basePrice:48,currency:'$'},
  {symbol:'ROST',name:'Ross Stores Inc.',sector:'Retail',cap:'large',basePrice:145,currency:'$'},
  {symbol:'PAYX',name:'Paychex Inc.',sector:'Technology',cap:'large',basePrice:120,currency:'$'},
  {symbol:'KDP',name:'Keurig Dr Pepper Inc.',sector:'Consumer',cap:'large',basePrice:35,currency:'$'},
  {symbol:'AZN',name:'AstraZeneca PLC',sector:'Biotech',cap:'large',basePrice:70,currency:'$'},
  {symbol:'NXPI',name:'NXP Semiconductors NV',sector:'Semiconductors',cap:'large',basePrice:230,currency:'$'},
  {symbol:'GEHC',name:'GE HealthCare Technologies Inc.',sector:'Healthcare',cap:'large',basePrice:82,currency:'$'},
  {symbol:'EXC',name:'Exelon Corporation',sector:'Technology',cap:'large',basePrice:42,currency:'$'},
  {symbol:'XEL',name:'Xcel Energy Inc.',sector:'Technology',cap:'large',basePrice:62,currency:'$'},
  {symbol:'ON',name:'ON Semiconductor Corp.',sector:'Semiconductors',cap:'large',basePrice:72,currency:'$'},
  {symbol:'CDW',name:'CDW Corporation',sector:'Technology',cap:'large',basePrice:230,currency:'$'},
  {symbol:'TTWO',name:'Take-Two Interactive Software',sector:'Gaming',cap:'large',basePrice:165,currency:'$'},
  {symbol:'WBD',name:'Warner Bros. Discovery Inc.',sector:'Media',cap:'large',basePrice:12,currency:'$'},
  {symbol:'FANG',name:'Diamondback Energy Inc.',sector:'Technology',cap:'large',basePrice:165,currency:'$'},
  {symbol:'BKR',name:'Baker Hughes Company',sector:'Technology',cap:'large',basePrice:35,currency:'$'},
  {symbol:'GFS',name:'GlobalFoundries Inc.',sector:'Semiconductors',cap:'large',basePrice:55,currency:'$'},
  {symbol:'MCHP',name:'Microchip Technology Inc.',sector:'Semiconductors',cap:'large',basePrice:80,currency:'$'},
  {symbol:'DASH',name:'DoorDash Inc.',sector:'Technology',cap:'large',basePrice:125,currency:'$'},
  {symbol:'ARM',name:'Arm Holdings PLC',sector:'Semiconductors',cap:'large',basePrice:130,currency:'$'},
  {symbol:'SMCI',name:'Super Micro Computer Inc.',sector:'Hardware',cap:'large',basePrice:45,currency:'$'},
  {symbol:'BIIB',name:'Biogen Inc.',sector:'Biotech',cap:'large',basePrice:220,currency:'$'},
  {symbol:'MRNA',name:'Moderna Inc.',sector:'Biotech',cap:'large',basePrice:105,currency:'$'},
  {symbol:'HON',name:'Honeywell International Inc.',sector:'Technology',cap:'large',basePrice:200,currency:'$'},
  {symbol:'DLTR',name:'Dollar Tree Inc.',sector:'Retail',cap:'large',basePrice:135,currency:'$'},
  {symbol:'ILMN',name:'Illumina Inc.',sector:'Healthcare',cap:'large',basePrice:130,currency:'$'},
  {symbol:'CHTR',name:'Charter Communications Inc.',sector:'Media',cap:'large',basePrice:380,currency:'$'},
  {symbol:'MAR',name:'Marriott International Inc.',sector:'Travel',cap:'large',basePrice:240,currency:'$'},
  {symbol:'AEP',name:'American Electric Power Co.',sector:'Technology',cap:'large',basePrice:88,currency:'$'},
  {symbol:'CTSH',name:'Cognizant Technology Solutions',sector:'Technology',cap:'large',basePrice:75,currency:'$'},
  {symbol:'VRTX',name:'Vertex Pharmaceuticals Inc.',sector:'Biotech',cap:'large',basePrice:410,currency:'$'},
  {symbol:'PDD',name:'PDD Holdings Inc.',sector:'E-Commerce',cap:'large',basePrice:125,currency:'$'},
  {symbol:'LCID',name:'Lucid Group Inc.',sector:'Auto/EV',cap:'large',basePrice:4,currency:'$'},
  {symbol:'ASML',name:'ASML Holding NV',sector:'Semiconductors',cap:'large',basePrice:710,currency:'$'},
  {symbol:'TMUS',name:'T-Mobile US Inc.',sector:'Technology',cap:'large',basePrice:165,currency:'$'},
  {symbol:'ADI',name:'Analog Devices Inc.',sector:'Semiconductors',cap:'large',basePrice:205,currency:'$'},
  {symbol:'TXN',name:'Texas Instruments Inc.',sector:'Semiconductors',cap:'large',basePrice:175,currency:'$'},
  {symbol:'SIRI',name:'Sirius XM Holdings Inc.',sector:'Media',cap:'large',basePrice:4,currency:'$'},
  {symbol:'MTCH',name:'Match Group Inc.',sector:'Internet',cap:'large',basePrice:38,currency:'$'},
  {symbol:'MSTR',name:'MicroStrategy Inc.',sector:'Technology',cap:'large',basePrice:480,currency:'$'},
  {symbol:'ENPH',name:'Enphase Energy Inc.',sector:'Technology',cap:'large',basePrice:120,currency:'$'},
  {symbol:'WBA',name:'Walgreens Boots Alliance Inc.',sector:'Healthcare',cap:'large',basePrice:22,currency:'$'},
  {symbol:'ZM',name:'Zoom Video Communications Inc.',sector:'Cloud',cap:'large',basePrice:68,currency:'$'},
  {symbol:'ALGN',name:'Align Technology Inc.',sector:'Healthcare',cap:'large',basePrice:280,currency:'$'},
  // === MID CAP (50 stocks) — NASDAQ Mid-Caps ($10B-$50B) ===
  {symbol:'SNOW',name:'Snowflake Inc.',sector:'Cloud',cap:'mid',basePrice:165,currency:'$'},
  {symbol:'TTD',name:'The Trade Desk Inc.',sector:'AdTech',cap:'mid',basePrice:85,currency:'$'},
  {symbol:'NET',name:'Cloudflare Inc.',sector:'Cloud',cap:'mid',basePrice:95,currency:'$'},
  {symbol:'OKTA',name:'Okta Inc.',sector:'Cybersecurity',cap:'mid',basePrice:105,currency:'$'},
  {symbol:'HUBS',name:'HubSpot Inc.',sector:'Software',cap:'mid',basePrice:580,currency:'$'},
  {symbol:'MDB',name:'MongoDB Inc.',sector:'Cloud',cap:'mid',basePrice:280,currency:'$'},
  {symbol:'COIN',name:'Coinbase Global Inc.',sector:'Fintech',cap:'mid',basePrice:220,currency:'$'},
  {symbol:'ROKU',name:'Roku Inc.',sector:'Entertainment',cap:'mid',basePrice:65,currency:'$'},
  {symbol:'DKNG',name:'DraftKings Inc.',sector:'Gaming',cap:'mid',basePrice:38,currency:'$'},
  {symbol:'RIVN',name:'Rivian Automotive Inc.',sector:'Auto/EV',cap:'mid',basePrice:14,currency:'$'},
  {symbol:'MNDY',name:'Monday.com Ltd.',sector:'Software',cap:'mid',basePrice:250,currency:'$'},
  {symbol:'BILL',name:'BILL Holdings Inc.',sector:'Fintech',cap:'mid',basePrice:72,currency:'$'},
  {symbol:'CELH',name:'Celsius Holdings Inc.',sector:'Consumer',cap:'mid',basePrice:55,currency:'$'},
  {symbol:'PATH',name:'UiPath Inc.',sector:'Software',cap:'mid',basePrice:15,currency:'$'},
  {symbol:'CRSP',name:'CRISPR Therapeutics AG',sector:'Biotech',cap:'mid',basePrice:55,currency:'$'},
  {symbol:'TWLO',name:'Twilio Inc.',sector:'Cloud',cap:'mid',basePrice:65,currency:'$'},
  {symbol:'PINS',name:'Pinterest Inc.',sector:'Internet',cap:'mid',basePrice:35,currency:'$'},
  {symbol:'LYFT',name:'Lyft Inc.',sector:'Ride-hailing',cap:'mid',basePrice:18,currency:'$'},
  {symbol:'RBLX',name:'Roblox Corporation',sector:'Gaming',cap:'mid',basePrice:42,currency:'$'},
  {symbol:'ETSY',name:'Etsy Inc.',sector:'E-Commerce',cap:'mid',basePrice:75,currency:'$'},
  {symbol:'ZI',name:'ZoomInfo Technologies Inc.',sector:'Software',cap:'mid',basePrice:20,currency:'$'},
  {symbol:'SPLK',name:'Splunk Inc.',sector:'Software',cap:'mid',basePrice:155,currency:'$'},
  {symbol:'DOCN',name:'DigitalOcean Holdings Inc.',sector:'Cloud',cap:'mid',basePrice:35,currency:'$'},
  {symbol:'CFLT',name:'Confluent Inc.',sector:'Cloud',cap:'mid',basePrice:28,currency:'$'},
  {symbol:'GTLB',name:'GitLab Inc.',sector:'Software',cap:'mid',basePrice:55,currency:'$'},
  {symbol:'PCOR',name:'Procore Technologies Inc.',sector:'Software',cap:'mid',basePrice:68,currency:'$'},
  {symbol:'VEEV',name:'Veeva Systems Inc.',sector:'Cloud',cap:'mid',basePrice:195,currency:'$'},
  {symbol:'TOST',name:'Toast Inc.',sector:'Fintech',cap:'mid',basePrice:25,currency:'$'},
  {symbol:'NTNX',name:'Nutanix Inc.',sector:'Cloud',cap:'mid',basePrice:55,currency:'$'},
  {symbol:'ESTC',name:'Elastic NV',sector:'Software',cap:'mid',basePrice:110,currency:'$'},
  {symbol:'CYBR',name:'CyberArk Software Ltd.',sector:'Cybersecurity',cap:'mid',basePrice:240,currency:'$'},
  {symbol:'PAYC',name:'Paycom Software Inc.',sector:'Software',cap:'mid',basePrice:195,currency:'$'},
  {symbol:'PCTY',name:'Paylocity Holding Corp.',sector:'Software',cap:'mid',basePrice:165,currency:'$'},
  {symbol:'ENSG',name:'Ensign Group Inc.',sector:'Healthcare',cap:'mid',basePrice:115,currency:'$'},
  {symbol:'EXAS',name:'Exact Sciences Corporation',sector:'Healthcare',cap:'mid',basePrice:72,currency:'$'},
  {symbol:'MANH',name:'Manhattan Associates Inc.',sector:'Software',cap:'mid',basePrice:220,currency:'$'},
  {symbol:'TYL',name:'Tyler Technologies Inc.',sector:'Software',cap:'mid',basePrice:450,currency:'$'},
  {symbol:'FIVE',name:'Five Below Inc.',sector:'Retail',cap:'mid',basePrice:145,currency:'$'},
  {symbol:'CHWY',name:'Chewy Inc.',sector:'E-Commerce',cap:'mid',basePrice:28,currency:'$'},
  {symbol:'SMAR',name:'Smartsheet Inc.',sector:'Software',cap:'mid',basePrice:48,currency:'$'},
  {symbol:'QLYS',name:'Qualys Inc.',sector:'Cybersecurity',cap:'mid',basePrice:155,currency:'$'},
  {symbol:'TRMB',name:'Trimble Inc.',sector:'Technology',cap:'mid',basePrice:58,currency:'$'},
  {symbol:'WIX',name:'Wix.com Ltd.',sector:'Internet',cap:'mid',basePrice:145,currency:'$'},
  {symbol:'PODD',name:'Insulet Corporation',sector:'Healthcare',cap:'mid',basePrice:175,currency:'$'},
  {symbol:'FLEX',name:'Flex Ltd.',sector:'Hardware',cap:'mid',basePrice:28,currency:'$'},
  {symbol:'SWAV',name:'Shockwave Medical Inc.',sector:'Healthcare',cap:'mid',basePrice:330,currency:'$'},
  {symbol:'LSCC',name:'Lattice Semiconductor Corp.',sector:'Semiconductors',cap:'mid',basePrice:72,currency:'$'},
  {symbol:'GLOB',name:'Globant S.A.',sector:'Technology',cap:'mid',basePrice:195,currency:'$'},
  {symbol:'AZPN',name:'Aspen Technology Inc.',sector:'Software',cap:'mid',basePrice:210,currency:'$'},
  {symbol:'FRSH',name:'Freshworks Inc.',sector:'Software',cap:'mid',basePrice:18,currency:'$'},
  // === SMALL CAP (50 stocks) — NASDAQ Small-Caps (< $10B) ===
  {symbol:'IONQ',name:'IonQ Inc.',sector:'Quantum Computing',cap:'small',basePrice:18,currency:'$'},
  {symbol:'RKLB',name:'Rocket Lab USA Inc.',sector:'Aerospace',cap:'small',basePrice:22,currency:'$'},
  {symbol:'SOUN',name:'SoundHound AI Inc.',sector:'AI',cap:'small',basePrice:8,currency:'$'},
  {symbol:'JOBY',name:'Joby Aviation Inc.',sector:'Aerospace',cap:'small',basePrice:6.5,currency:'$'},
  {symbol:'DNA',name:'Ginkgo Bioworks Holdings Inc.',sector:'Biotech',cap:'small',basePrice:12,currency:'$'},
  {symbol:'PLTR',name:'Palantir Technologies Inc.',sector:'AI',cap:'small',basePrice:24,currency:'$'},
  {symbol:'SOFI',name:'SoFi Technologies Inc.',sector:'Fintech',cap:'small',basePrice:9,currency:'$'},
  {symbol:'GRAB',name:'Grab Holdings Ltd.',sector:'Ride-hailing',cap:'small',basePrice:3.8,currency:'$'},
  {symbol:'HOOD',name:'Robinhood Markets Inc.',sector:'Fintech',cap:'small',basePrice:18,currency:'$'},
  {symbol:'AFRM',name:'Affirm Holdings Inc.',sector:'Fintech',cap:'small',basePrice:42,currency:'$'},
  {symbol:'UPST',name:'Upstart Holdings Inc.',sector:'Fintech',cap:'small',basePrice:28,currency:'$'},
  {symbol:'U',name:'Unity Software Inc.',sector:'Gaming',cap:'small',basePrice:22,currency:'$'},
  {symbol:'RDDT',name:'Reddit Inc.',sector:'Internet',cap:'small',basePrice:55,currency:'$'},
  {symbol:'DUOL',name:'Duolingo Inc.',sector:'EdTech',cap:'small',basePrice:220,currency:'$'},
  {symbol:'APP',name:'AppLovin Corporation',sector:'AdTech',cap:'small',basePrice:85,currency:'$'},
  {symbol:'CAVA',name:'CAVA Group Inc.',sector:'QSR',cap:'small',basePrice:75,currency:'$'},
  {symbol:'BMBL',name:'Bumble Inc.',sector:'Internet',cap:'small',basePrice:15,currency:'$'},
  {symbol:'SKLZ',name:'Skillz Inc.',sector:'Gaming',cap:'small',basePrice:7,currency:'$'},
  {symbol:'OPEN',name:'Opendoor Technologies Inc.',sector:'Technology',cap:'small',basePrice:3.5,currency:'$'},
  {symbol:'ASAN',name:'Asana Inc.',sector:'Software',cap:'small',basePrice:18,currency:'$'},
  {symbol:'GDRX',name:'GoodRx Holdings Inc.',sector:'Healthcare',cap:'small',basePrice:7,currency:'$'},
  {symbol:'BIGC',name:'BigCommerce Holdings Inc.',sector:'E-Commerce',cap:'small',basePrice:8,currency:'$'},
  {symbol:'WKHS',name:'Workhorse Group Inc.',sector:'Auto/EV',cap:'small',basePrice:1.2,currency:'$'},
  {symbol:'LAZR',name:'Luminar Technologies Inc.',sector:'Auto/EV',cap:'small',basePrice:4,currency:'$'},
  {symbol:'VLD',name:'Velo3D Inc.',sector:'Technology',cap:'small',basePrice:2.5,currency:'$'},
  {symbol:'MAPS',name:'WM Technology Inc.',sector:'Technology',cap:'small',basePrice:1.8,currency:'$'},
  {symbol:'SEAT',name:'Vivid Seats Inc.',sector:'Entertainment',cap:'small',basePrice:6,currency:'$'},
  {symbol:'BRZE',name:'Braze Inc.',sector:'Software',cap:'small',basePrice:45,currency:'$'},
  {symbol:'NNOX',name:'Nano-X Imaging Ltd.',sector:'Healthcare',cap:'small',basePrice:12,currency:'$'},
  {symbol:'QBTS',name:'D-Wave Quantum Inc.',sector:'Quantum Computing',cap:'small',basePrice:3,currency:'$'},
  {symbol:'RGTI',name:'Rigetti Computing Inc.',sector:'Quantum Computing',cap:'small',basePrice:2,currency:'$'},
  {symbol:'ARQT',name:'Arcus Biosciences Inc.',sector:'Biotech',cap:'small',basePrice:18,currency:'$'},
  {symbol:'CIFR',name:'Cipher Mining Inc.',sector:'Technology',cap:'small',basePrice:5,currency:'$'},
  {symbol:'ASTS',name:'AST SpaceMobile Inc.',sector:'Aerospace',cap:'small',basePrice:15,currency:'$'},
  {symbol:'LUNR',name:'Intuitive Machines Inc.',sector:'Aerospace',cap:'small',basePrice:8,currency:'$'},
  {symbol:'RDW',name:'Redwire Corporation',sector:'Aerospace',cap:'small',basePrice:6,currency:'$'},
  {symbol:'SMWB',name:'Similarweb Ltd.',sector:'Software',cap:'small',basePrice:10,currency:'$'},
  {symbol:'TASK',name:'TaskUs Inc.',sector:'Technology',cap:'small',basePrice:14,currency:'$'},
  {symbol:'DLO',name:'DLocal Ltd.',sector:'Fintech',cap:'small',basePrice:12,currency:'$'},
  {symbol:'VERX',name:'Vertex Inc.',sector:'Software',cap:'small',basePrice:25,currency:'$'},
  {symbol:'CWAN',name:'Clearwater Analytics Holdings',sector:'Fintech',cap:'small',basePrice:20,currency:'$'},
  {symbol:'RELY',name:'Remitly Global Inc.',sector:'Fintech',cap:'small',basePrice:18,currency:'$'},
  {symbol:'KARO',name:'Karooooo Ltd.',sector:'Technology',cap:'small',basePrice:35,currency:'$'},
  {symbol:'BLZE',name:'Backblaze Inc.',sector:'Cloud',cap:'small',basePrice:9,currency:'$'},
  {symbol:'PRCT',name:'PROCEPT BioRobotics Corp.',sector:'Healthcare',cap:'small',basePrice:55,currency:'$'},
  {symbol:'AEHR',name:'Aehr Test Systems',sector:'Semiconductors',cap:'small',basePrice:18,currency:'$'},
  {symbol:'VERV',name:'Verve Therapeutics Inc.',sector:'Biotech',cap:'small',basePrice:8,currency:'$'},
  {symbol:'MGNI',name:'Magnite Inc.',sector:'AdTech',cap:'small',basePrice:12,currency:'$'},
  {symbol:'INDI',name:'Indie Semiconductor Inc.',sector:'Semiconductors',cap:'small',basePrice:7,currency:'$'},
  {symbol:'BTDR',name:'Bitdeer Technologies Group',sector:'Technology',cap:'small',basePrice:10,currency:'$'}
];


const EXCHANGE_MAP = {nse: NSE_STOCKS, bse: BSE_STOCKS, nasdaq: NASDAQ_STOCKS};