const BSE_STOCKS = [
// === LARGE CAP (30 stocks) - Sensex 30 Constituents ===
{symbol:'RELIANCE',name:'Reliance Industries Ltd',sector:'Oil & Gas',cap:'large',basePrice:2950},
{symbol:'TCS',name:'Tata Consultancy Services Ltd',sector:'IT',cap:'large',basePrice:3850},
{symbol:'HDFCBANK',name:'HDFC Bank Ltd',sector:'Banking',cap:'large',basePrice:1720},
{symbol:'INFY',name:'Infosys Ltd',sector:'IT',cap:'large',basePrice:1580},
{symbol:'ICICIBANK',name:'ICICI Bank Ltd',sector:'Banking',cap:'large',basePrice:1280},
{symbol:'HINDUNILVR',name:'Hindustan Unilever Ltd',sector:'FMCG',cap:'large',basePrice:2480},
{symbol:'ITC',name:'ITC Ltd',sector:'FMCG',cap:'large',basePrice:465},
{symbol:'SBIN',name:'State Bank of India',sector:'Banking',cap:'large',basePrice:820},
{symbol:'BHARTIARTL',name:'Bharti Airtel Ltd',sector:'Telecom',cap:'large',basePrice:1650},
{symbol:'KOTAKBANK',name:'Kotak Mahindra Bank Ltd',sector:'Banking',cap:'large',basePrice:1850},
{symbol:'LT',name:'Larsen & Toubro Ltd',sector:'Infrastructure',cap:'large',basePrice:3520},
{symbol:'AXISBANK',name:'Axis Bank Ltd',sector:'Banking',cap:'large',basePrice:1150},
{symbol:'BAJFINANCE',name:'Bajaj Finance Ltd',sector:'Finance',cap:'large',basePrice:6800},
{symbol:'MARUTI',name:'Maruti Suzuki India Ltd',sector:'Auto',cap:'large',basePrice:12500},
{symbol:'TITAN',name:'Titan Company Ltd',sector:'Consumer',cap:'large',basePrice:3250},
{symbol:'SUNPHARMA',name:'Sun Pharmaceutical Industries Ltd',sector:'Pharma',cap:'large',basePrice:1180},
{symbol:'TATAMOTORS',name:'Tata Motors Ltd',sector:'Auto',cap:'large',basePrice:950},
{symbol:'HCLTECH',name:'HCL Technologies Ltd',sector:'IT',cap:'large',basePrice:1520},
{symbol:'NTPC',name:'NTPC Ltd',sector:'Power',cap:'large',basePrice:365},
{symbol:'POWERGRID',name:'Power Grid Corporation of India Ltd',sector:'Power',cap:'large',basePrice:310},
{symbol:'TATASTEEL',name:'Tata Steel Ltd',sector:'Metals',cap:'large',basePrice:155},
{symbol:'NESTLEIND',name:'Nestle India Ltd',sector:'FMCG',cap:'large',basePrice:2400},
{symbol:'ULTRACEMCO',name:'UltraTech Cement Ltd',sector:'Cement',cap:'large',basePrice:10200},
{symbol:'WIPRO',name:'Wipro Ltd',sector:'IT',cap:'large',basePrice:480},
{symbol:'M&M',name:'Mahindra & Mahindra Ltd',sector:'Auto',cap:'large',basePrice:2680},
{symbol:'TECHM',name:'Tech Mahindra Ltd',sector:'IT',cap:'large',basePrice:1380},
{symbol:'ASIANPAINT',name:'Asian Paints Ltd',sector:'Consumer',cap:'large',basePrice:2850},
{symbol:'INDUSINDBK',name:'IndusInd Bank Ltd',sector:'Banking',cap:'large',basePrice:1450},
{symbol:'BAJAJ-AUTO',name:'Bajaj Auto Ltd',sector:'Auto',cap:'large',basePrice:8900},
{symbol:'ADANIENT',name:'Adani Enterprises Ltd',sector:'Infrastructure',cap:'large',basePrice:3100},
// === MID CAP (150 stocks) - BSE MidCap 150 Index ===
{symbol:'ZOMATO',name:'Zomato Ltd',sector:'Internet',cap:'mid',basePrice:240},
{symbol:'PAYTM',name:'One97 Communications Ltd',sector:'Fintech',cap:'mid',basePrice:780},
{symbol:'NYKAA',name:'FSN E-Commerce Ventures Ltd',sector:'E-Commerce',cap:'mid',basePrice:180},
{symbol:'POLICYBZR',name:'PB Fintech Ltd',sector:'Insurance',cap:'mid',basePrice:1650},
{symbol:'DELHIVERY',name:'Delhivery Ltd',sector:'Logistics',cap:'mid',basePrice:420},
{symbol:'MAPMYINDIA',name:'CE Info Systems Ltd',sector:'IT',cap:'mid',basePrice:1800},
{symbol:'IRCTC',name:'Indian Railway Catering & Tourism Corp',sector:'Travel Tech',cap:'mid',basePrice:880},
{symbol:'TRENT',name:'Trent Ltd',sector:'Retail',cap:'mid',basePrice:4200},
{symbol:'MOTHERSON',name:'Samvardhana Motherson International Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:140},
{symbol:'VOLTAS',name:'Voltas Ltd',sector:'Consumer',cap:'mid',basePrice:1150},
{symbol:'MAXHEALTH',name:'Max Healthcare Institute Ltd',sector:'Healthcare',cap:'mid',basePrice:820},
{symbol:'OBEROIRLTY',name:'Oberoi Realty Ltd',sector:'Real Estate',cap:'mid',basePrice:1600},
{symbol:'PHOENIXLTD',name:'The Phoenix Mills Ltd',sector:'Real Estate',cap:'mid',basePrice:1650},
{symbol:'GODREJPROP',name:'Godrej Properties Ltd',sector:'Real Estate',cap:'mid',basePrice:2350},
{symbol:'PRESTIGE',name:'Prestige Estates Projects Ltd',sector:'Real Estate',cap:'mid',basePrice:1280},
{symbol:'MPHASIS',name:'Mphasis Ltd',sector:'IT',cap:'mid',basePrice:2450},
{symbol:'LTIM',name:'LTIMindtree Ltd',sector:'IT',cap:'mid',basePrice:5200},
{symbol:'COFORGE',name:'Coforge Ltd',sector:'IT',cap:'mid',basePrice:5800},
{symbol:'PERSISTENT',name:'Persistent Systems Ltd',sector:'IT',cap:'mid',basePrice:4500},
{symbol:'FEDERALBNK',name:'The Federal Bank Ltd',sector:'Banking',cap:'mid',basePrice:165},
{symbol:'IDFCFIRSTB',name:'IDFC First Bank Ltd',sector:'Banking',cap:'mid',basePrice:72},
{symbol:'BANDHANBNK',name:'Bandhan Bank Ltd',sector:'Banking',cap:'mid',basePrice:213},
{symbol:'AUBANK',name:'AU Small Finance Bank Ltd',sector:'Banking',cap:'mid',basePrice:1030},
{symbol:'MUTHOOTFIN',name:'Muthoot Finance Ltd',sector:'Finance',cap:'mid',basePrice:1750},
{symbol:'CHOLAFIN',name:'Cholamandalam Investment & Finance Co Ltd',sector:'Finance',cap:'mid',basePrice:1320},
{symbol:'SHRIRAMFIN',name:'Shriram Finance Ltd',sector:'Finance',cap:'mid',basePrice:2450},
{symbol:'MANAPPURAM',name:'Manappuram Finance Ltd',sector:'Finance',cap:'mid',basePrice:185},
{symbol:'PIIND',name:'PI Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:3650},
{symbol:'AARTIIND',name:'Aarti Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:580},
{symbol:'DEEPAKNITRO',name:'Deepak Nitrite Ltd',sector:'Chemicals',cap:'mid',basePrice:2100},
{symbol:'SOLARINDS',name:'Solar Industries India Ltd',sector:'Chemicals',cap:'mid',basePrice:8500},
{symbol:'ASTRAL',name:'Astral Ltd',sector:'Industrial',cap:'mid',basePrice:1900},
{symbol:'POLYCAB',name:'Polycab India Ltd',sector:'Electronics',cap:'mid',basePrice:5600},
{symbol:'CUMMINSIND',name:'Cummins India Ltd',sector:'Engineering',cap:'mid',basePrice:2500},
{symbol:'APLAPOLLO',name:'APL Apollo Tubes Ltd',sector:'Metals',cap:'mid',basePrice:1550},
{symbol:'SUPREMEIND',name:'Supreme Industries Ltd',sector:'Industrial',cap:'mid',basePrice:4800},
{symbol:'PAGEIND',name:'Page Industries Ltd',sector:'Textiles',cap:'mid',basePrice:38000},
{symbol:'DIXON',name:'Dixon Technologies India Ltd',sector:'Electronics',cap:'mid',basePrice:5400},
{symbol:'HONAUT',name:'Honeywell Automation India Ltd',sector:'Industrial',cap:'mid',basePrice:42000},
{symbol:'SCHAEFFLER',name:'Schaeffler India Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:3200},
{symbol:'SYNGENE',name:'Syngene International Ltd',sector:'Pharma',cap:'mid',basePrice:780},
{symbol:'AUROPHARMA',name:'Aurobindo Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:1150},
{symbol:'ALKEM',name:'Alkem Laboratories Ltd',sector:'Pharma',cap:'mid',basePrice:5200},
{symbol:'LAURUSLABS',name:'Laurus Labs Ltd',sector:'Pharma',cap:'mid',basePrice:420},
{symbol:'IPCALAB',name:'IPCA Laboratories Ltd',sector:'Pharma',cap:'mid',basePrice:1350},
{symbol:'TORNTPHARM',name:'Torrent Pharmaceuticals Ltd',sector:'Pharma',cap:'mid',basePrice:2600},
{symbol:'JUBLFOOD',name:'Jubilant FoodWorks Ltd',sector:'QSR',cap:'mid',basePrice:520},
{symbol:'DEVYANI',name:'Devyani International Ltd',sector:'QSR',cap:'mid',basePrice:165},
{symbol:'INDIANHOTELS',name:'The Indian Hotels Company Ltd',sector:'Hotels',cap:'mid',basePrice:580},
{symbol:'LEMONTR',name:'Lemon Tree Hotels Ltd',sector:'Hotels',cap:'mid',basePrice:125},
{symbol:'CROMPTON',name:'Crompton Greaves Consumer Electricals Ltd',sector:'Consumer',cap:'mid',basePrice:340},
{symbol:'HAVELLS',name:'Havells India Ltd',sector:'Consumer',cap:'mid',basePrice:1580},
{symbol:'WHIRLPOOL',name:'Whirlpool of India Ltd',sector:'Consumer',cap:'mid',basePrice:1350},
{symbol:'BLUESTARLT',name:'Blue Star Ltd',sector:'Consumer',cap:'mid',basePrice:1250},
{symbol:'METROBRAND',name:'Metro Brands Ltd',sector:'Retail',cap:'mid',basePrice:1200},
{symbol:'VMART',name:'V-Mart Retail Ltd',sector:'Retail',cap:'mid',basePrice:2100},
{symbol:'ABFRL',name:'Aditya Birla Fashion & Retail Ltd',sector:'Fashion',cap:'mid',basePrice:220},
{symbol:'MEDANTA',name:'Global Health Ltd',sector:'Healthcare',cap:'mid',basePrice:1450},
{symbol:'FORTIS',name:'Fortis Healthcare Ltd',sector:'Healthcare',cap:'mid',basePrice:480},
{symbol:'KIMS',name:'Krishna Institute of Medical Sciences Ltd',sector:'Healthcare',cap:'mid',basePrice:2200},
{symbol:'IIFL',name:'IIFL Finance Ltd',sector:'Finance',cap:'mid',basePrice:450},
{symbol:'ANGELONE',name:'Angel One Ltd',sector:'Finance',cap:'mid',basePrice:2400},
{symbol:'BSOFT',name:'Birlasoft Ltd',sector:'IT',cap:'mid',basePrice:620},
{symbol:'ROUTE',name:'Route Mobile Ltd',sector:'IT',cap:'mid',basePrice:1650},
{symbol:'TANLA',name:'Tanla Platforms Ltd',sector:'IT',cap:'mid',basePrice:980},
{symbol:'ZEEL',name:'Zee Entertainment Enterprises Ltd',sector:'Media',cap:'mid',basePrice:135},
{symbol:'SUNTV',name:'Sun TV Network Ltd',sector:'Media',cap:'mid',basePrice:620},
{symbol:'CONCOR',name:'Container Corporation of India Ltd',sector:'Logistics',cap:'mid',basePrice:780},
{symbol:'RVNL',name:'Rail Vikas Nigam Ltd',sector:'Infrastructure',cap:'mid',basePrice:250},
{symbol:'IRFC',name:'Indian Railway Finance Corporation Ltd',sector:'Finance',cap:'mid',basePrice:155},
{symbol:'RECLTD',name:'REC Ltd',sector:'Finance',cap:'mid',basePrice:480},
{symbol:'PFC',name:'Power Finance Corporation Ltd',sector:'Finance',cap:'mid',basePrice:420},
{symbol:'NHPC',name:'NHPC Ltd',sector:'Power',cap:'mid',basePrice:85},
{symbol:'SJVN',name:'SJVN Ltd',sector:'Power',cap:'mid',basePrice:115},
{symbol:'TORNTPOWER',name:'Torrent Power Ltd',sector:'Power',cap:'mid',basePrice:1650},
{symbol:'CESC',name:'CESC Ltd',sector:'Power',cap:'mid',basePrice:155},
{symbol:'TATAPOWER',name:'Tata Power Company Ltd',sector:'Power',cap:'mid',basePrice:420},
{symbol:'ADANIGREEN',name:'Adani Green Energy Ltd',sector:'Energy',cap:'mid',basePrice:1750},
{symbol:'ADANIPORTS',name:'Adani Ports and Special Economic Zone Ltd',sector:'Infrastructure',cap:'mid',basePrice:1280},
{symbol:'GLAND',name:'Gland Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:1650},
{symbol:'BIOCON',name:'Biocon Ltd',sector:'Pharma',cap:'mid',basePrice:320},
{symbol:'CLEAN',name:'Clean Science and Technology Ltd',sector:'Chemicals',cap:'mid',basePrice:1450},
{symbol:'ATUL',name:'Atul Ltd',sector:'Chemicals',cap:'mid',basePrice:6200},
{symbol:'CARBORUNIV',name:'Carborundum Universal Ltd',sector:'Industrial',cap:'mid',basePrice:1150},
{symbol:'GRINDWELL',name:'Grindwell Norton Ltd',sector:'Industrial',cap:'mid',basePrice:2000},
{symbol:'TIINDIA',name:'Tube Investments of India Ltd',sector:'Industrial',cap:'mid',basePrice:3400},
{symbol:'BRIGADE',name:'Brigade Enterprises Ltd',sector:'Real Estate',cap:'mid',basePrice:1150},
{symbol:'LODHA',name:'Macrotech Developers Ltd',sector:'Real Estate',cap:'mid',basePrice:1350},
{symbol:'SONACOMS',name:'Sona BLW Precision Forgings Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:580},
{symbol:'HAPPSTMNDS',name:'Happiest Minds Technologies Ltd',sector:'IT',cap:'mid',basePrice:750},
{symbol:'INTELLECT',name:'Intellect Design Arena Ltd',sector:'IT',cap:'mid',basePrice:680},
{symbol:'FLUOROCHEM',name:'Gujarat Fluorochemicals Ltd',sector:'Chemicals',cap:'mid',basePrice:3200},
{symbol:'ESCORTS',name:'Escorts Kubota Ltd',sector:'Auto',cap:'mid',basePrice:3400},
{symbol:'EICHERMOT',name:'Eicher Motors Ltd',sector:'Auto',cap:'mid',basePrice:4500},
{symbol:'THERMAX',name:'Thermax Ltd',sector:'Engineering',cap:'mid',basePrice:3800},
{symbol:'CGPOWER',name:'CG Power and Industrial Solutions Ltd',sector:'Industrial',cap:'mid',basePrice:520},
{symbol:'BHEL',name:'Bharat Heavy Electricals Ltd',sector:'Engineering',cap:'mid',basePrice:245},
{symbol:'BEL',name:'Bharat Electronics Ltd',sector:'Defence',cap:'mid',basePrice:280},
{symbol:'HAL',name:'Hindustan Aeronautics Ltd',sector:'Defence',cap:'mid',basePrice:4200},
{symbol:'APOLLOTYRE',name:'Apollo Tyres Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:430},
{symbol:'ASTERDM',name:'Aster DM Healthcare Ltd',sector:'Healthcare',cap:'mid',basePrice:820},
{symbol:'ATHERENERG',name:'Ather Energy Ltd',sector:'EV',cap:'mid',basePrice:1282},
{symbol:'ECLERX',name:'eClerx Services Ltd',sector:'IT',cap:'mid',basePrice:3200},
{symbol:'HDFCAMC',name:'HDFC Asset Management Company Ltd',sector:'Finance',cap:'mid',basePrice:4500},
{symbol:'UNIONBANK',name:'Union Bank of India',sector:'Banking',cap:'mid',basePrice:145},
{symbol:'HUDCO',name:'Housing & Urban Development Corporation Ltd',sector:'Finance',cap:'mid',basePrice:230},
{symbol:'ABCAPITAL',name:'Aditya Birla Capital Ltd',sector:'Finance',cap:'mid',basePrice:230},
{symbol:'ICICIGI',name:'ICICI Lombard General Insurance Co Ltd',sector:'Insurance',cap:'mid',basePrice:1680},
{symbol:'SBILIFE',name:'SBI Life Insurance Company Ltd',sector:'Insurance',cap:'mid',basePrice:1580},
{symbol:'HDFCLIFE',name:'HDFC Life Insurance Company Ltd',sector:'Insurance',cap:'mid',basePrice:650},
{symbol:'ICICIPRULI',name:'ICICI Prudential Life Insurance Co Ltd',sector:'Insurance',cap:'mid',basePrice:620},
{symbol:'GICRE',name:'General Insurance Corporation of India',sector:'Insurance',cap:'mid',basePrice:320},
{symbol:'NIACL',name:'The New India Assurance Company Ltd',sector:'Insurance',cap:'mid',basePrice:220},
{symbol:'STARHEALTH',name:'Star Health & Allied Insurance Co Ltd',sector:'Insurance',cap:'mid',basePrice:580},
{symbol:'LICHSGFIN',name:'LIC Housing Finance Ltd',sector:'Finance',cap:'mid',basePrice:450},
{symbol:'CANFINHOME',name:'Can Fin Homes Ltd',sector:'Finance',cap:'mid',basePrice:820},
{symbol:'GMRAIRPORT',name:'GMR Airports Infrastructure Ltd',sector:'Infrastructure',cap:'mid',basePrice:85},
{symbol:'INDIGO',name:'InterGlobe Aviation Ltd',sector:'Aviation',cap:'mid',basePrice:4800},
{symbol:'PETRONET',name:'Petronet LNG Ltd',sector:'Oil & Gas',cap:'mid',basePrice:280},
{symbol:'GAIL',name:'GAIL India Ltd',sector:'Oil & Gas',cap:'mid',basePrice:195},
{symbol:'OIL',name:'Oil India Ltd',sector:'Oil & Gas',cap:'mid',basePrice:520},
{symbol:'HINDPETRO',name:'Hindustan Petroleum Corporation Ltd',sector:'Oil & Gas',cap:'mid',basePrice:420},
{symbol:'BPCL',name:'Bharat Petroleum Corporation Ltd',sector:'Oil & Gas',cap:'mid',basePrice:580},
{symbol:'IOC',name:'Indian Oil Corporation Ltd',sector:'Oil & Gas',cap:'mid',basePrice:165},
{symbol:'COALINDIA',name:'Coal India Ltd',sector:'Mining',cap:'mid',basePrice:480},
{symbol:'NMDC',name:'NMDC Ltd',sector:'Mining',cap:'mid',basePrice:245},
{symbol:'VEDL',name:'Vedanta Ltd',sector:'Metals',cap:'mid',basePrice:420},
{symbol:'HINDZINC',name:'Hindustan Zinc Ltd',sector:'Metals',cap:'mid',basePrice:580},
{symbol:'NATIONALUM',name:'National Aluminium Company Ltd',sector:'Metals',cap:'mid',basePrice:165},
{symbol:'SAIL',name:'Steel Authority of India Ltd',sector:'Metals',cap:'mid',basePrice:120},
{symbol:'JINDALSTEL',name:'Jindal Steel & Power Ltd',sector:'Metals',cap:'mid',basePrice:780},
{symbol:'AMBUJACEM',name:'Ambuja Cements Ltd',sector:'Cement',cap:'mid',basePrice:620},
{symbol:'SHREECEM',name:'Shree Cement Ltd',sector:'Cement',cap:'mid',basePrice:26500},
{symbol:'ACC',name:'ACC Ltd',sector:'Cement',cap:'mid',basePrice:2350},
{symbol:'DALBHARAT',name:'Dalmia Bharat Ltd',sector:'Cement',cap:'mid',basePrice:1850},
{symbol:'RAMCOCEM',name:'The Ramco Cements Ltd',sector:'Cement',cap:'mid',basePrice:920},
{symbol:'PIDILITIND',name:'Pidilite Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:2750},
{symbol:'DABUR',name:'Dabur India Ltd',sector:'FMCG',cap:'mid',basePrice:580},
{symbol:'GODREJCP',name:'Godrej Consumer Products Ltd',sector:'FMCG',cap:'mid',basePrice:1250},
{symbol:'MARICO',name:'Marico Ltd',sector:'FMCG',cap:'mid',basePrice:620},
{symbol:'COLPAL',name:'Colgate-Palmolive India Ltd',sector:'FMCG',cap:'mid',basePrice:2650},
{symbol:'BERGEPAINT',name:'Berger Paints India Ltd',sector:'Consumer',cap:'mid',basePrice:520},
{symbol:'BALKRISHNA',name:'Balkrishna Industries Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:2650},
{symbol:'MRF',name:'MRF Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:125000},
{symbol:'BOSCHLTD',name:'Bosch Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:32000},
{symbol:'EXIDEIND',name:'Exide Industries Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:480},
{symbol:'AMARAJABAT',name:'Amara Raja Energy & Mobility Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:780},
{symbol:'SUNDRMFAST',name:'Sundram Fasteners Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:1050},
{symbol:'SKFINDIA',name:'SKF India Ltd',sector:'Industrial',cap:'mid',basePrice:4800},
{symbol:'TIMKEN',name:'Timken India Ltd',sector:'Industrial',cap:'mid',basePrice:3200},
// === SMALL CAP (250 stocks) - BSE SmallCap 250 Index ===
{symbol:'OLACABS',name:'Ola Electric Mobility Ltd',sector:'EV',cap:'small',basePrice:85},
{symbol:'IDEAFORGE',name:'ideaForge Technology Ltd',sector:'Defence',cap:'small',basePrice:620},
{symbol:'YATHARTH',name:'Yatharth Hospital & Trauma Care Services Ltd',sector:'Healthcare',cap:'small',basePrice:520},
{symbol:'ZAGGLE',name:'Zaggle Prepaid Ocean Services Ltd',sector:'Fintech',cap:'small',basePrice:380},
{symbol:'NETWEB',name:'Netweb Technologies India Ltd',sector:'IT',cap:'small',basePrice:2400},
{symbol:'BONDADA',name:'Bondada Engineering Ltd',sector:'Energy',cap:'small',basePrice:450},
{symbol:'JYOTICTL',name:'Jyoti CNC Automation Ltd',sector:'Industrial',cap:'small',basePrice:1100},
{symbol:'TBOTEK',name:'TBO Tek Ltd',sector:'Travel Tech',cap:'small',basePrice:1500},
{symbol:'JUNIPER',name:'Juniper Hotels Ltd',sector:'Hotels',cap:'small',basePrice:420},
{symbol:'CELLO',name:'Cello World Ltd',sector:'Consumer',cap:'small',basePrice:750},
{symbol:'KAYNES',name:'Kaynes Technology India Ltd',sector:'Electronics',cap:'small',basePrice:3800},
{symbol:'EXICOM',name:'Exicom Tele-Systems Ltd',sector:'EV',cap:'small',basePrice:320},
{symbol:'DOMS',name:'DOMS Industries Ltd',sector:'Stationery',cap:'small',basePrice:2200},
{symbol:'SENCO',name:'Senco Gold Ltd',sector:'Jewellery',cap:'small',basePrice:1100},
{symbol:'SAMHI',name:'Samhi Hotels Ltd',sector:'Hotels',cap:'small',basePrice:280},
{symbol:'CREDO',name:'Credo Brands Marketing Ltd',sector:'Fashion',cap:'small',basePrice:450},
{symbol:'PVRINOX',name:'PVR INOX Ltd',sector:'Entertainment',cap:'small',basePrice:1400},
{symbol:'RATEGAIN',name:'RateGain Travel Technologies Ltd',sector:'Travel Tech',cap:'small',basePrice:680},
{symbol:'SAPPHIRE',name:'Sapphire Foods India Ltd',sector:'QSR',cap:'small',basePrice:1400},
{symbol:'MEDPLUS',name:'MedPlus Health Services Ltd',sector:'Healthcare',cap:'small',basePrice:640},
{symbol:'CAMPUS',name:'Campus Activewear Ltd',sector:'Fashion',cap:'small',basePrice:265},
{symbol:'GPIL',name:'Godawari Power and Ispat Ltd',sector:'Metals',cap:'small',basePrice:850},
{symbol:'GALAXYSURF',name:'Galaxy Surfactants Ltd',sector:'Chemicals',cap:'small',basePrice:2600},
{symbol:'DATAPATTNS',name:'Data Patterns India Ltd',sector:'Defence',cap:'small',basePrice:2400},
{symbol:'PARAS',name:'Paras Defence and Space Technologies Ltd',sector:'Defence',cap:'small',basePrice:980},
{symbol:'MAZAGON',name:'Mazagon Dock Shipbuilders Ltd',sector:'Defence',cap:'small',basePrice:3800},
{symbol:'COCHINSHIP',name:'Cochin Shipyard Ltd',sector:'Defence',cap:'small',basePrice:1850},
{symbol:'GRSE',name:'Garden Reach Shipbuilders & Engineers Ltd',sector:'Defence',cap:'small',basePrice:2100},
{symbol:'LATENTVIEW',name:'Latent View Analytics Ltd',sector:'IT',cap:'small',basePrice:420},
{symbol:'CARTRADE',name:'CarTrade Tech Ltd',sector:'Internet',cap:'small',basePrice:850},
{symbol:'EASEMYTRIP',name:'Easy Trip Planners Ltd',sector:'Travel Tech',cap:'small',basePrice:38},
{symbol:'IXIGO',name:'Le Travenues Technology Ltd',sector:'Travel Tech',cap:'small',basePrice:145},
{symbol:'YATRA',name:'Yatra Online Ltd',sector:'Travel Tech',cap:'small',basePrice:120},
{symbol:'FIVESTAR',name:'Five-Star Business Finance Ltd',sector:'Finance',cap:'small',basePrice:720},
{symbol:'JBMA',name:'JBM Auto Ltd',sector:'Auto Ancillary',cap:'small',basePrice:1750},
{symbol:'LXCHEM',name:'Laxmi Organic Industries Ltd',sector:'Chemicals',cap:'small',basePrice:265},
{symbol:'HOMEFIRST',name:'Home First Finance Company India Ltd',sector:'Finance',cap:'small',basePrice:950},
{symbol:'APTUS',name:'Aptus Value Housing Finance India Ltd',sector:'Finance',cap:'small',basePrice:320},
{symbol:'ELECTRONICA',name:'Electronica Plastic Machines Ltd',sector:'Industrial',cap:'small',basePrice:380},
{symbol:'MASTERTRUST',name:'Mastertrust Ltd',sector:'Finance',cap:'small',basePrice:240},
{symbol:'SYRMA',name:'Syrma SGS Technology Ltd',sector:'Electronics',cap:'small',basePrice:420},
{symbol:'AETHER',name:'Aether Industries Ltd',sector:'Chemicals',cap:'small',basePrice:850},
{symbol:'AVALON',name:'Avalon Technologies Ltd',sector:'Electronics',cap:'small',basePrice:580},
{symbol:'CYIENT',name:'Cyient Ltd',sector:'IT',cap:'small',basePrice:1650},
{symbol:'ZENTEC',name:'Zen Technologies Ltd',sector:'Defence',cap:'small',basePrice:1450},
{symbol:'DREAMFOLKS',name:'Dreamfolks Services Ltd',sector:'Travel Tech',cap:'small',basePrice:420},
{symbol:'EPIGRAL',name:'Epigral Ltd',sector:'Chemicals',cap:'small',basePrice:1650},
{symbol:'SHYAMMET',name:'Shyam Metalics and Energy Ltd',sector:'Metals',cap:'small',basePrice:620},
{symbol:'GRAVITA',name:'Gravita India Ltd',sector:'Metals',cap:'small',basePrice:1850},
{symbol:'CRAFTSMAN',name:'Craftsman Automation Ltd',sector:'Auto Ancillary',cap:'small',basePrice:4500},
{symbol:'TVSHLDGS',name:'TVS Holdings Ltd',sector:'Finance',cap:'small',basePrice:8200},
{symbol:'BIKAJI',name:'Bikaji Foods International Ltd',sector:'FMCG',cap:'small',basePrice:650},
{symbol:'GOPAL',name:'Gopal Snacks Ltd',sector:'FMCG',cap:'small',basePrice:320},
{symbol:'MAMA',name:'Mama Earth (Honasa Consumer Ltd)',sector:'FMCG',cap:'small',basePrice:380},
{symbol:'SBFC',name:'SBFC Finance Ltd',sector:'Finance',cap:'small',basePrice:82},
{symbol:'SIGNATURE',name:'Signature Global India Ltd',sector:'Real Estate',cap:'small',basePrice:1350},
{symbol:'SOBHA',name:'Sobha Ltd',sector:'Real Estate',cap:'small',basePrice:1550},
{symbol:'RAYMOND',name:'Raymond Ltd',sector:'Textiles',cap:'small',basePrice:1650},
{symbol:'KFINTECH',name:'KFin Technologies Ltd',sector:'Fintech',cap:'small',basePrice:680},
{symbol:'CAMS',name:'Computer Age Management Services Ltd',sector:'Fintech',cap:'small',basePrice:3200},
{symbol:'JSWENERGY',name:'JSW Energy Ltd',sector:'Power',cap:'small',basePrice:520},
{symbol:'RENEW',name:'ReNew Energy Global PLC',sector:'Energy',cap:'small',basePrice:450},
{symbol:'SWANENERGY',name:'Swan Energy Ltd',sector:'Energy',cap:'small',basePrice:580},
{symbol:'UCOBANK',name:'UCO Bank',sector:'Banking',cap:'small',basePrice:42},
{symbol:'TRITURBINE',name:'Triveni Turbine Ltd',sector:'Engineering',cap:'small',basePrice:520},
{symbol:'ANURAS',name:'Anupam Rasayan India Ltd',sector:'Chemicals',cap:'small',basePrice:850},
{symbol:'MOTISONS',name:'Motisons Jewellers Ltd',sector:'Jewellery',cap:'small',basePrice:145},
{symbol:'KALYANKJIL',name:'Kalyan Jewellers India Ltd',sector:'Jewellery',cap:'small',basePrice:520},
{symbol:'PNBHOUSING',name:'PNB Housing Finance Ltd',sector:'Finance',cap:'small',basePrice:780},
{symbol:'EQUITAS',name:'Equitas Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:95},
{symbol:'UJJIVANSFB',name:'Ujjivan Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:42},
{symbol:'INDIGOPNTS',name:'Indigo Paints Ltd',sector:'Consumer',cap:'small',basePrice:1450},
{symbol:'KPITTECH',name:'KPIT Technologies Ltd',sector:'IT',cap:'small',basePrice:1350},
{symbol:'TATAELXSI',name:'Tata Elxsi Ltd',sector:'IT',cap:'small',basePrice:6800},
{symbol:'RRKABEL',name:'R R Kabel Ltd',sector:'Electronics',cap:'small',basePrice:1450},
{symbol:'JKCEMENT',name:'JK Cement Ltd',sector:'Cement',cap:'small',basePrice:3800},
{symbol:'RATNAMANI',name:'Ratnamani Metals & Tubes Ltd',sector:'Metals',cap:'small',basePrice:3100},
{symbol:'HAPPYFORGE',name:'Happy Forgings Ltd',sector:'Industrial',cap:'small',basePrice:850},
{symbol:'WONDERLA',name:'Wonderla Holidays Ltd',sector:'Entertainment',cap:'small',basePrice:780},
{symbol:'IMAGICAA',name:'Imagicaaworld Entertainment Ltd',sector:'Entertainment',cap:'small',basePrice:65},
{symbol:'NAZARA',name:'Nazara Technologies Ltd',sector:'Entertainment',cap:'small',basePrice:820},
{symbol:'RAINBOW',name:'Rainbow Childrens Medicare Ltd',sector:'Healthcare',cap:'small',basePrice:1350},
{symbol:'SUPRIYA',name:'Supriya Lifescience Ltd',sector:'Pharma',cap:'small',basePrice:420},
{symbol:'WINDLAS',name:'Windlas Biotech Ltd',sector:'Pharma',cap:'small',basePrice:680},
{symbol:'EMUDHRA',name:'eMudhra Ltd',sector:'IT',cap:'small',basePrice:650},
{symbol:'TRACXN',name:'Tracxn Technologies Ltd',sector:'Fintech',cap:'small',basePrice:85},
{symbol:'INFOBEANS',name:'InfoBeans Technologies Ltd',sector:'IT',cap:'small',basePrice:420},
{symbol:'GPPL',name:'Gujarat Pipavav Port Ltd',sector:'Logistics',cap:'small',basePrice:185},
{symbol:'MAHLIFE',name:'Mahindra Lifespace Developers Ltd',sector:'Real Estate',cap:'small',basePrice:520},
{symbol:'REFEX',name:'Refex Industries Ltd',sector:'Industrial',cap:'small',basePrice:480},
{symbol:'FIEMIND',name:'Fiem Industries Ltd',sector:'Auto Ancillary',cap:'small',basePrice:1250},
{symbol:'GREENPANEL',name:'Greenpanel Industries Ltd',sector:'Industrial',cap:'small',basePrice:320},
{symbol:'PENIND',name:'Pennar Industries Ltd',sector:'Metals',cap:'small',basePrice:155},
{symbol:'HGINFRA',name:'H.G. Infra Engineering Ltd',sector:'Infrastructure',cap:'small',basePrice:1350},
{symbol:'WOCKPHARMA',name:'Wockhardt Ltd',sector:'Pharma',cap:'small',basePrice:580},
{symbol:'ROSSARI',name:'Rossari Biotech Ltd',sector:'Chemicals',cap:'small',basePrice:750},
{symbol:'ETHOSLTD',name:'Ethos Ltd',sector:'Retail',cap:'small',basePrice:2400},
{symbol:'GOCOLORS',name:'Go Fashion India Ltd',sector:'Fashion',cap:'small',basePrice:1050},
{symbol:'VEDANT',name:'Vedant Fashions Ltd',sector:'Fashion',cap:'small',basePrice:1150},
{symbol:'HARSHA',name:'Harsha Engineers International Ltd',sector:'Industrial',cap:'small',basePrice:450},
{symbol:'HINDCOPPER',name:'Hindustan Copper Ltd',sector:'Metals',cap:'small',basePrice:280},
{symbol:'TARSONS',name:'Tarsons Products Ltd',sector:'Healthcare',cap:'small',basePrice:420},
{symbol:'YESBANK',name:'Yes Bank Ltd',sector:'Banking',cap:'small',basePrice:22},
{symbol:'GROWW',name:'Groww (Billdesk parent - NextBillion Technology)',sector:'Fintech',cap:'small',basePrice:250},
{symbol:'VIYASH',name:'Viyash Life Sciences Ltd',sector:'Pharma',cap:'small',basePrice:1200},
{symbol:'FCL',name:'Fineotex Chemical Ltd',sector:'Chemicals',cap:'small',basePrice:85},
{symbol:'KWIL',name:'KW International Ltd',sector:'Real Estate',cap:'small',basePrice:3400},
{symbol:'IDEA',name:'Vodafone Idea Ltd',sector:'Telecom',cap:'small',basePrice:14},
{symbol:'AMIORG',name:'Ami Organics Ltd',sector:'Chemicals',cap:'small',basePrice:1050},
{symbol:'ACE',name:'Action Construction Equipment Ltd',sector:'Industrial',cap:'small',basePrice:280},
{symbol:'ALKYLAMINE',name:'Alkyl Amines Chemicals Ltd',sector:'Chemicals',cap:'small',basePrice:2200},
{symbol:'AMBER',name:'Amber Enterprises India Ltd',sector:'Electronics',cap:'small',basePrice:4500},
{symbol:'ANDHRAPET',name:'Andhra Petrochemicals Ltd',sector:'Chemicals',cap:'small',basePrice:120},
{symbol:'APLLTD',name:'Alembic Pharmaceuticals Ltd',sector:'Pharma',cap:'small',basePrice:680},
{symbol:'ARCHEAN',name:'Archean Chemical Industries Ltd',sector:'Chemicals',cap:'small',basePrice:620},
{symbol:'ARVINDFASHN',name:'Arvind Fashions Ltd',sector:'Fashion',cap:'small',basePrice:420},
{symbol:'ASAHISONG',name:'Asahi Songwon Colors Ltd',sector:'Chemicals',cap:'small',basePrice:280},
{symbol:'ASHIANA',name:'Ashiana Housing Ltd',sector:'Real Estate',cap:'small',basePrice:320},
{symbol:'ASTEC',name:'Astec LifeSciences Ltd',sector:'Chemicals',cap:'small',basePrice:1650},
{symbol:'AURIONPRO',name:'Aurionpro Solutions Ltd',sector:'IT',cap:'small',basePrice:1450},
{symbol:'AVANTIFEED',name:'Avanti Feeds Ltd',sector:'FMCG',cap:'small',basePrice:520},
{symbol:'BAJAJHCARE',name:'Bajaj Healthcare Ltd',sector:'Pharma',cap:'small',basePrice:420},
{symbol:'BANARISUG',name:'Balrampur Chini Mills Ltd',sector:'Sugar',cap:'small',basePrice:3200},
{symbol:'BASF',name:'BASF India Ltd',sector:'Chemicals',cap:'small',basePrice:3800},
{symbol:'BECTORFOOD',name:'Mrs Bectors Food Specialities Ltd',sector:'FMCG',cap:'small',basePrice:380},
{symbol:'BEML',name:'BEML Ltd',sector:'Industrial',cap:'small',basePrice:3200},
{symbol:'BLKASHYAP',name:'B L Kashyap and Sons Ltd',sector:'Infrastructure',cap:'small',basePrice:180},
{symbol:'BODALCHEM',name:'Bodal Chemicals Ltd',sector:'Chemicals',cap:'small',basePrice:120},
{symbol:'CANARA',name:'Canara Bank',sector:'Banking',cap:'small',basePrice:580},
{symbol:'CAPACITE',name:'Capacite Infraprojects Ltd',sector:'Infrastructure',cap:'small',basePrice:280},
{symbol:'CARYSIL',name:'Carysil Ltd',sector:'Consumer',cap:'small',basePrice:650},
{symbol:'CASTROLIND',name:'Castrol India Ltd',sector:'Oil & Gas',cap:'small',basePrice:220},
{symbol:'CCL',name:'CCL Products India Ltd',sector:'FMCG',cap:'small',basePrice:580},
{symbol:'CENTURYPLY',name:'Century Plyboards India Ltd',sector:'Industrial',cap:'small',basePrice:680},
{symbol:'CHALET',name:'Chalet Hotels Ltd',sector:'Hotels',cap:'small',basePrice:420},
{symbol:'CHEMCON',name:'Chemcon Speciality Chemicals Ltd',sector:'Chemicals',cap:'small',basePrice:380},
{symbol:'CHENNPETRO',name:'Chennai Petroleum Corporation Ltd',sector:'Oil & Gas',cap:'small',basePrice:850},
{symbol:'CMSINFO',name:'CMS Info Systems Ltd',sector:'Finance',cap:'small',basePrice:420},
{symbol:'COCHINREF',name:'Cochin Refineries (BPCL Kochi)',sector:'Oil & Gas',cap:'small',basePrice:180},
{symbol:'CONCORDBIO',name:'Concord Biotech Ltd',sector:'Pharma',cap:'small',basePrice:580},
{symbol:'CONTROLPR',name:'Control Print Ltd',sector:'Industrial',cap:'small',basePrice:680},
{symbol:'CSBBANK',name:'CSB Bank Ltd',sector:'Banking',cap:'small',basePrice:320},
{symbol:'DEEPAKFERT',name:'Deepak Fertilisers & Petrochemicals Corp Ltd',sector:'Fertilizer',cap:'small',basePrice:520},
{symbol:'DHANUKA',name:'Dhanuka Agritech Ltd',sector:'Chemicals',cap:'small',basePrice:1350},
{symbol:'ELECON',name:'Elecon Engineering Company Ltd',sector:'Engineering',cap:'small',basePrice:580},
{symbol:'ELGIEQUIP',name:'Elgi Equipments Ltd',sector:'Industrial',cap:'small',basePrice:520},
{symbol:'EMAMILTD',name:'Emami Ltd',sector:'FMCG',cap:'small',basePrice:580},
{symbol:'ERIS',name:'Eris Lifesciences Ltd',sector:'Pharma',cap:'small',basePrice:950},
{symbol:'ESABINDIA',name:'ESAB India Ltd',sector:'Industrial',cap:'small',basePrice:4200},
{symbol:'FILATEX',name:'Filatex India Ltd',sector:'Textiles',cap:'small',basePrice:65},
{symbol:'FINOLEXIND',name:'Finolex Industries Ltd',sector:'Industrial',cap:'small',basePrice:220},
{symbol:'GABRIEL',name:'Gabriel India Ltd',sector:'Auto Ancillary',cap:'small',basePrice:380},
{symbol:'GARFIBRES',name:'Garware Technical Fibres Ltd',sector:'Textiles',cap:'small',basePrice:2800},
{symbol:'GATEWAY',name:'Gateway Distriparks Ltd',sector:'Logistics',cap:'small',basePrice:85},
{symbol:'GENUSPOWER',name:'Genus Power Infrastructures Ltd',sector:'Power',cap:'small',basePrice:320},
{symbol:'GESHIP',name:'Great Eastern Shipping Company Ltd',sector:'Shipping',cap:'small',basePrice:850},
{symbol:'GHCL',name:'GHCL Ltd',sector:'Chemicals',cap:'small',basePrice:520},
{symbol:'GLENMARK',name:'Glenmark Pharmaceuticals Ltd',sector:'Pharma',cap:'small',basePrice:1450},
{symbol:'GMDCLTD',name:'Gujarat Mineral Development Corporation Ltd',sector:'Mining',cap:'small',basePrice:320},
{symbol:'GNFC',name:'Gujarat Narmada Valley Fertilizers & Chemicals Ltd',sector:'Fertilizer',cap:'small',basePrice:620},
{symbol:'GODFRYPHLP',name:'Godfrey Phillips India Ltd',sector:'FMCG',cap:'small',basePrice:4800},
{symbol:'GODREJIND',name:'Godrej Industries Ltd',sector:'Industrial',cap:'small',basePrice:680},
{symbol:'GOLDIAM',name:'Goldiam International Ltd',sector:'Jewellery',cap:'small',basePrice:280},
{symbol:'GRAUER',name:'Grauer & Weil India Ltd',sector:'Chemicals',cap:'small',basePrice:3200},
{symbol:'GUJGAS',name:'Gujarat Gas Ltd',sector:'Oil & Gas',cap:'small',basePrice:520},
{symbol:'HATHWAY',name:'Hathway Cable & Datacom Ltd',sector:'Telecom',cap:'small',basePrice:22},
{symbol:'HERITGFOOD',name:'Heritage Foods Ltd',sector:'FMCG',cap:'small',basePrice:520},
{symbol:'HIKAL',name:'Hikal Ltd',sector:'Chemicals',cap:'small',basePrice:280},
{symbol:'HIL',name:'HIL Ltd',sector:'Industrial',cap:'small',basePrice:6800},
{symbol:'HLEGLAS',name:'HLE Glascoat Ltd',sector:'Industrial',cap:'small',basePrice:580},
{symbol:'HSCL',name:'Hindustan Steelworks Construction Ltd',sector:'Infrastructure',cap:'small',basePrice:85},
{symbol:'ICRA',name:'ICRA Ltd',sector:'Finance',cap:'small',basePrice:5200},
{symbol:'IGARASHI',name:'Igarashi Motors India Ltd',sector:'Auto Ancillary',cap:'small',basePrice:480},
{symbol:'IMFA',name:'Indian Metals & Ferro Alloys Ltd',sector:'Metals',cap:'small',basePrice:580},
{symbol:'INDIAMART',name:'IndiaMART InterMESH Ltd',sector:'Internet',cap:'small',basePrice:2800},
{symbol:'INDOSTAR',name:'IndoStar Capital Finance Ltd',sector:'Finance',cap:'small',basePrice:280},
{symbol:'INFIBEAM',name:'Infibeam Avenues Ltd',sector:'Fintech',cap:'small',basePrice:28},
{symbol:'IONEXCHANG',name:'Ion Exchange India Ltd',sector:'Industrial',cap:'small',basePrice:420},
{symbol:'ISEC',name:'ICICI Securities Ltd',sector:'Finance',cap:'small',basePrice:780},
{symbol:'ITI',name:'ITI Ltd',sector:'Telecom',cap:'small',basePrice:280},
{symbol:'JAMNAAUTO',name:'Jamna Auto Industries Ltd',sector:'Auto Ancillary',cap:'small',basePrice:95},
{symbol:'JAYNECOIND',name:'Jay Neco Industries Ltd',sector:'Metals',cap:'small',basePrice:120},
{symbol:'JCHAC',name:'Johnson Controls-Hitachi Air Conditioning India Ltd',sector:'Consumer',cap:'small',basePrice:2200},
{symbol:'JETAIRWAYS',name:'Jet Airways India Ltd',sector:'Aviation',cap:'small',basePrice:22},
{symbol:'JINDALSAW',name:'Jindal SAW Ltd',sector:'Metals',cap:'small',basePrice:380},
{symbol:'JMC',name:'JMC Projects India Ltd',sector:'Infrastructure',cap:'small',basePrice:85},
{symbol:'JMFINANCIL',name:'JM Financial Ltd',sector:'Finance',cap:'small',basePrice:85},
{symbol:'JKLAKSHMI',name:'JK Lakshmi Cement Ltd',sector:'Cement',cap:'small',basePrice:780},
{symbol:'JKTYRE',name:'JK Tyre & Industries Ltd',sector:'Auto Ancillary',cap:'small',basePrice:380},
{symbol:'JUBLPHARMA',name:'Jubilant Pharmova Ltd',sector:'Pharma',cap:'small',basePrice:580},
{symbol:'JUSTDIAL',name:'Just Dial Ltd',sector:'Internet',cap:'small',basePrice:1050},
{symbol:'KABRAEXTRU',name:'Kabra Extrusiontechnik Ltd',sector:'Industrial',cap:'small',basePrice:320},
{symbol:'KANSAINER',name:'Kansai Nerolac Paints Ltd',sector:'Consumer',cap:'small',basePrice:280},
{symbol:'KENNAMET',name:'Kennametal India Ltd',sector:'Industrial',cap:'small',basePrice:2200},
{symbol:'KIRLOSENG',name:'Kirloskar Oil Engines Ltd',sector:'Engineering',cap:'small',basePrice:480},
{symbol:'KIRLOSBROS',name:'Kirloskar Brothers Ltd',sector:'Engineering',cap:'small',basePrice:850},
{symbol:'KOKUYOCMLN',name:'Kokuyo Camlin Ltd',sector:'Stationery',cap:'small',basePrice:280},
{symbol:'KOLTEPATIL',name:'Kolte-Patil Developers Ltd',sector:'Real Estate',cap:'small',basePrice:320},
{symbol:'KPRMILL',name:'KPR Mill Ltd',sector:'Textiles',cap:'small',basePrice:680},
{symbol:'KRBL',name:'KRBL Ltd',sector:'FMCG',cap:'small',basePrice:280},
{symbol:'KTKBANK',name:'Karnataka Bank Ltd',sector:'Banking',cap:'small',basePrice:85},
{symbol:'LALPATHLAB',name:'Dr Lal PathLabs Ltd',sector:'Healthcare',cap:'small',basePrice:2800},
{symbol:'LUXIND',name:'Lux Industries Ltd',sector:'Textiles',cap:'small',basePrice:1850},
{symbol:'MAITHANALL',name:'Maithan Alloys Ltd',sector:'Metals',cap:'small',basePrice:1050},
{symbol:'MANINFRA',name:'Man Infraconstruction Ltd',sector:'Infrastructure',cap:'small',basePrice:180},
{symbol:'MANORAMA',name:'Manorama Industries Ltd',sector:'FMCG',cap:'small',basePrice:420},
{symbol:'MASTEK',name:'Mastek Ltd',sector:'IT',cap:'small',basePrice:2400},
{symbol:'MAYURUNIQ',name:'Mayur Uniquoters Ltd',sector:'Textiles',cap:'small',basePrice:420},
{symbol:'MRPL',name:'Mangalore Refinery and Petrochemicals Ltd',sector:'Oil & Gas',cap:'small',basePrice:180},
{symbol:'MSTCLTD',name:'MSTC Ltd',sector:'Industrial',cap:'small',basePrice:420},
{symbol:'NATCOPHARM',name:'Natco Pharma Ltd',sector:'Pharma',cap:'small',basePrice:780},
{symbol:'NAVINFLUOR',name:'Navin Fluorine International Ltd',sector:'Chemicals',cap:'small',basePrice:3800},
{symbol:'NESCO',name:'Nesco Ltd',sector:'Real Estate',cap:'small',basePrice:850},
{symbol:'NILKAMAL',name:'Nilkamal Ltd',sector:'Consumer',cap:'small',basePrice:2400},
{symbol:'NUVOCO',name:'Nuvoco Vistas Corporation Ltd',sector:'Cement',cap:'small',basePrice:380},
{symbol:'ORIENTCEM',name:'Orient Cement Ltd',sector:'Cement',cap:'small',basePrice:180},
{symbol:'ORIENTELEC',name:'Orient Electric Ltd',sector:'Consumer',cap:'small',basePrice:280},
{symbol:'PRAJIND',name:'Praj Industries Ltd',sector:'Engineering',cap:'small',basePrice:680},
{symbol:'PRSMJOHNSN',name:'Prism Johnson Ltd',sector:'Cement',cap:'small',basePrice:120},
{symbol:'QUESS',name:'Quess Corp Ltd',sector:'Industrial',cap:'small',basePrice:620},
{symbol:'RAJESHEXPO',name:'Rajesh Exports Ltd',sector:'Jewellery',cap:'small',basePrice:520},
{symbol:'RALLIS',name:'Rallis India Ltd',sector:'Chemicals',cap:'small',basePrice:280},
{symbol:'RBLBANK',name:'RBL Bank Ltd',sector:'Banking',cap:'small',basePrice:220},
{symbol:'REDINGTON',name:'Redington Ltd',sector:'IT',cap:'small',basePrice:180},
{symbol:'RELIGARE',name:'Religare Enterprises Ltd',sector:'Finance',cap:'small',basePrice:280},
{symbol:'REPRO',name:'Repro India Ltd',sector:'Industrial',cap:'small',basePrice:780},
{symbol:'RITES',name:'RITES Ltd',sector:'Infrastructure',cap:'small',basePrice:520},
{symbol:'RSYSTEMS',name:'R Systems International Ltd',sector:'IT',cap:'small',basePrice:520},
{symbol:'SANOFI',name:'Sanofi India Ltd',sector:'Pharma',cap:'small',basePrice:6200},
{symbol:'SEQUENT',name:'Sequent Scientific Ltd',sector:'Pharma',cap:'small',basePrice:180},
{symbol:'SHARDACROP',name:'Sharda Cropchem Ltd',sector:'Chemicals',cap:'small',basePrice:520},
{symbol:'SHOPERSTOP',name:'Shoppers Stop Ltd',sector:'Retail',cap:'small',basePrice:780},
{symbol:'SJFL',name:'Sheela Foam Ltd',sector:'Consumer',cap:'small',basePrice:320},
{symbol:'SOLARA',name:'Solara Active Pharma Sciences Ltd',sector:'Pharma',cap:'small',basePrice:280},
{symbol:'SOUTHBANK',name:'South Indian Bank Ltd',sector:'Banking',cap:'small',basePrice:28},
{symbol:'STARCEMENT',name:'Star Cement Ltd',sector:'Cement',cap:'small',basePrice:120},
{symbol:'STLTECH',name:'Sterlite Technologies Ltd',sector:'Telecom',cap:'small',basePrice:120},
{symbol:'SUNDARAM',name:'Sundaram Finance Ltd',sector:'Finance',cap:'small',basePrice:1050},
{symbol:'SUPRAJIT',name:'Suprajit Engineering Ltd',sector:'Auto Ancillary',cap:'small',basePrice:420},
{symbol:'SUVEN',name:'Suven Pharmaceuticals Ltd',sector:'Pharma',cap:'small',basePrice:520},
{symbol:'SYMPHONY',name:'Symphony Ltd',sector:'Consumer',cap:'small',basePrice:1250},
{symbol:'TAINWALCHM',name:'Tainwala Chemicals & Plastics India Ltd',sector:'Chemicals',cap:'small',basePrice:1850},
{symbol:'TATAINVEST',name:'Tata Investment Corporation Ltd',sector:'Finance',cap:'small',basePrice:2800},
{symbol:'TDPOWER',name:'TD Power Systems Ltd',sector:'Power',cap:'small',basePrice:420},
{symbol:'TEAMLEASE',name:'TeamLease Services Ltd',sector:'Industrial',cap:'small',basePrice:2800},
{symbol:'THYROCARE',name:'Thyrocare Technologies Ltd',sector:'Healthcare',cap:'small',basePrice:580},
{symbol:'TITAGARH',name:'Titagarh Rail Systems Ltd',sector:'Industrial',cap:'small',basePrice:850},
{symbol:'TMB',name:'Tamilnad Mercantile Bank Ltd',sector:'Banking',cap:'small',basePrice:480},
{symbol:'TRIDENT',name:'Trident Ltd',sector:'Textiles',cap:'small',basePrice:35},
{symbol:'TTKPRESTIG',name:'TTK Prestige Ltd',sector:'Consumer',cap:'small',basePrice:7800},
{symbol:'TMCV',name:'Tata Motors Commercial Vehicles',sector:'Auto',cap:'mid',basePrice:223},
{symbol:'TMPV',name:'Tata Motors Passenger Vehicles',sector:'Auto',cap:'mid',basePrice:494}
];
