const NSE_STOCKS = [
  // ===== LARGE CAP (50 stocks) - Nifty 50 Constituents =====
  {symbol:'RELIANCE',name:'Reliance Industries Ltd',sector:'Energy',cap:'large',basePrice:2950},
  {symbol:'TCS',name:'Tata Consultancy Services Ltd',sector:'IT',cap:'large',basePrice:3850},
  {symbol:'HDFCBANK',name:'HDFC Bank Ltd',sector:'Banking',cap:'large',basePrice:1720},
  {symbol:'INFY',name:'Infosys Ltd',sector:'IT',cap:'large',basePrice:1580},
  {symbol:'ICICIBANK',name:'ICICI Bank Ltd',sector:'Banking',cap:'large',basePrice:1280},
  {symbol:'HINDUNILVR',name:'Hindustan Unilever Ltd',sector:'FMCG',cap:'large',basePrice:2480},
  {symbol:'ITC',name:'ITC Ltd',sector:'FMCG',cap:'large',basePrice:465},
  {symbol:'SBIN',name:'State Bank of India',sector:'Banking',cap:'large',basePrice:820},
  {symbol:'BHARTIARTL',name:'Bharti Airtel Ltd',sector:'Telecom',cap:'large',basePrice:1650},
  {symbol:'KOTAKBANK',name:'Kotak Mahindra Bank Ltd',sector:'Banking',cap:'large',basePrice:1850},
  {symbol:'LT',name:'Larsen & Toubro Ltd',sector:'Infrastructure',cap:'large',basePrice:3520},
  {symbol:'AXISBANK',name:'Axis Bank Ltd',sector:'Banking',cap:'large',basePrice:1150},
  {symbol:'BAJFINANCE',name:'Bajaj Finance Ltd',sector:'Finance',cap:'large',basePrice:6800},
  {symbol:'MARUTI',name:'Maruti Suzuki India Ltd',sector:'Auto',cap:'large',basePrice:12500},
  {symbol:'TITAN',name:'Titan Company Ltd',sector:'Consumer',cap:'large',basePrice:3250},
  {symbol:'SUNPHARMA',name:'Sun Pharmaceutical Industries Ltd',sector:'Pharma',cap:'large',basePrice:1180},
  {symbol:'TATAMOTORS',name:'Tata Motors Ltd',sector:'Auto',cap:'large',basePrice:950},
  {symbol:'HCLTECH',name:'HCL Technologies Ltd',sector:'IT',cap:'large',basePrice:1520},
  {symbol:'NTPC',name:'NTPC Ltd',sector:'Power',cap:'large',basePrice:365},
  {symbol:'POWERGRID',name:'Power Grid Corporation of India Ltd',sector:'Power',cap:'large',basePrice:310},
  {symbol:'TATASTEEL',name:'Tata Steel Ltd',sector:'Metals',cap:'large',basePrice:155},
  {symbol:'ADANIENT',name:'Adani Enterprises Ltd',sector:'Infrastructure',cap:'large',basePrice:3100},
  {symbol:'NESTLEIND',name:'Nestle India Ltd',sector:'FMCG',cap:'large',basePrice:2400},
  {symbol:'ULTRACEMCO',name:'UltraTech Cement Ltd',sector:'Cement',cap:'large',basePrice:10200},
  {symbol:'WIPRO',name:'Wipro Ltd',sector:'IT',cap:'large',basePrice:480},
  {symbol:'M&M',name:'Mahindra & Mahindra Ltd',sector:'Auto',cap:'large',basePrice:2680},
  {symbol:'ONGC',name:'Oil and Natural Gas Corporation Ltd',sector:'Energy',cap:'large',basePrice:265},
  {symbol:'JSWSTEEL',name:'JSW Steel Ltd',sector:'Metals',cap:'large',basePrice:880},
  {symbol:'COALINDIA',name:'Coal India Ltd',sector:'Mining',cap:'large',basePrice:440},
  {symbol:'BAJAJFINSV',name:'Bajaj Finserv Ltd',sector:'Finance',cap:'large',basePrice:1680},
  {symbol:'DRREDDY',name:'Dr Reddys Laboratories Ltd',sector:'Pharma',cap:'large',basePrice:5900},
  {symbol:'CIPLA',name:'Cipla Ltd',sector:'Pharma',cap:'large',basePrice:1480},
  {symbol:'DIVISLAB',name:'Divi\'s Laboratories Ltd',sector:'Pharma',cap:'large',basePrice:3750},
  {symbol:'GRASIM',name:'Grasim Industries Ltd',sector:'Cement',cap:'large',basePrice:2350},
  {symbol:'BRITANNIA',name:'Britannia Industries Ltd',sector:'FMCG',cap:'large',basePrice:5100},
  {symbol:'HEROMOTOCO',name:'Hero MotoCorp Ltd',sector:'Auto',cap:'large',basePrice:4600},
  {symbol:'EICHERMOT',name:'Eicher Motors Ltd',sector:'Auto',cap:'large',basePrice:4200},
  {symbol:'APOLLOHOSP',name:'Apollo Hospitals Enterprise Ltd',sector:'Healthcare',cap:'large',basePrice:5800},
  {symbol:'BPCL',name:'Bharat Petroleum Corporation Ltd',sector:'Energy',cap:'large',basePrice:340},
  {symbol:'TATACONSUM',name:'Tata Consumer Products Ltd',sector:'FMCG',cap:'large',basePrice:1050},
  {symbol:'SBILIFE',name:'SBI Life Insurance Company Ltd',sector:'Insurance',cap:'large',basePrice:1520},
  {symbol:'INDUSINDBK',name:'IndusInd Bank Ltd',sector:'Banking',cap:'large',basePrice:1450},
  {symbol:'HDFCLIFE',name:'HDFC Life Insurance Company Ltd',sector:'Insurance',cap:'large',basePrice:640},
  {symbol:'ADANIPORTS',name:'Adani Ports and Special Economic Zone Ltd',sector:'Infrastructure',cap:'large',basePrice:1250},
  {symbol:'HINDALCO',name:'Hindalco Industries Ltd',sector:'Metals',cap:'large',basePrice:580},
  {symbol:'BAJAJ-AUTO',name:'Bajaj Auto Ltd',sector:'Auto',cap:'large',basePrice:8900},
  {symbol:'TECHM',name:'Tech Mahindra Ltd',sector:'IT',cap:'large',basePrice:1380},
  {symbol:'ASIANPAINT',name:'Asian Paints Ltd',sector:'Consumer',cap:'large',basePrice:2850},
  {symbol:'UPL',name:'UPL Ltd',sector:'Chemicals',cap:'large',basePrice:520},
  {symbol:'SHRIRAMFIN',name:'Shriram Finance Ltd',sector:'Finance',cap:'large',basePrice:2400},

  // ===== MID CAP (150 stocks) - Nifty Midcap 150 Constituents =====
  {symbol:'PERSISTENT',name:'Persistent Systems Ltd',sector:'IT',cap:'mid',basePrice:5200},
  {symbol:'COFORGE',name:'Coforge Ltd',sector:'IT',cap:'mid',basePrice:5800},
  {symbol:'MPHASIS',name:'MphasiS Ltd',sector:'IT',cap:'mid',basePrice:2600},
  {symbol:'FEDERALBNK',name:'Federal Bank Ltd',sector:'Banking',cap:'mid',basePrice:168},
  {symbol:'ESCORTS',name:'Escorts Kubota Ltd',sector:'Auto',cap:'mid',basePrice:3400},
  {symbol:'AUROPHARMA',name:'Aurobindo Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:1280},
  {symbol:'CROMPTON',name:'Crompton Greaves Consumer Electricals Ltd',sector:'Consumer',cap:'mid',basePrice:380},
  {symbol:'MUTHOOTFIN',name:'Muthoot Finance Ltd',sector:'Finance',cap:'mid',basePrice:1850},
  {symbol:'CUMMINSIND',name:'Cummins India Ltd',sector:'Industrial',cap:'mid',basePrice:2800},
  {symbol:'POLYCAB',name:'Polycab India Ltd',sector:'Industrial',cap:'mid',basePrice:5600},
  {symbol:'TRENT',name:'Trent Ltd',sector:'Retail',cap:'mid',basePrice:4200},
  {symbol:'GODREJCP',name:'Godrej Consumer Products Ltd',sector:'FMCG',cap:'mid',basePrice:1350},
  {symbol:'VOLTAS',name:'Voltas Ltd',sector:'Consumer',cap:'mid',basePrice:1150},
  {symbol:'PIIND',name:'PI Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:3800},
  {symbol:'ASTRAL',name:'Astral Ltd',sector:'Industrial',cap:'mid',basePrice:1900},
  {symbol:'JUBLFOOD',name:'Jubilant FoodWorks Ltd',sector:'Consumer',cap:'mid',basePrice:580},
  {symbol:'MAXHEALTH',name:'Max Healthcare Institute Ltd',sector:'Healthcare',cap:'mid',basePrice:820},
  {symbol:'DMART',name:'Avenue Supermarts Ltd',sector:'Retail',cap:'mid',basePrice:4100},
  {symbol:'OBEROIRLTY',name:'Oberoi Realty Ltd',sector:'Real Estate',cap:'mid',basePrice:1600},
  {symbol:'TORNTPHARM',name:'Torrent Pharmaceuticals Ltd',sector:'Pharma',cap:'mid',basePrice:2600},
  {symbol:'BHARATFORG',name:'Bharat Forge Ltd',sector:'Industrial',cap:'mid',basePrice:1350},
  {symbol:'IDFCFIRSTB',name:'IDFC First Bank Ltd',sector:'Banking',cap:'mid',basePrice:82},
  {symbol:'LICHSGFIN',name:'LIC Housing Finance Ltd',sector:'Finance',cap:'mid',basePrice:620},
  {symbol:'PAGEIND',name:'Page Industries Ltd',sector:'Textiles',cap:'mid',basePrice:42000},
  {symbol:'PHOENIXLTD',name:'Phoenix Mills Ltd',sector:'Real Estate',cap:'mid',basePrice:1650},
  {symbol:'SOLARIND',name:'Solar Industries India Ltd',sector:'Chemicals',cap:'mid',basePrice:6800},
  {symbol:'ABCAPITAL',name:'Aditya Birla Capital Ltd',sector:'Finance',cap:'mid',basePrice:210},
  {symbol:'MFSL',name:'Max Financial Services Ltd',sector:'Insurance',cap:'mid',basePrice:1050},
  {symbol:'COLPAL',name:'Colgate-Palmolive India Ltd',sector:'FMCG',cap:'mid',basePrice:2700},
  {symbol:'AMBUJACEM',name:'Ambuja Cements Ltd',sector:'Cement',cap:'mid',basePrice:620},
  {symbol:'CONCOR',name:'Container Corporation of India Ltd',sector:'Logistics',cap:'mid',basePrice:880},
  {symbol:'IRCTC',name:'Indian Railway Catering and Tourism Corporation Ltd',sector:'Consumer',cap:'mid',basePrice:880},
  {symbol:'SAIL',name:'Steel Authority of India Ltd',sector:'Metals',cap:'mid',basePrice:130},
  {symbol:'CANBK',name:'Canara Bank',sector:'Banking',cap:'mid',basePrice:110},
  {symbol:'INDHOTEL',name:'Indian Hotels Company Ltd',sector:'Hotels',cap:'mid',basePrice:620},
  {symbol:'OFSS',name:'Oracle Financial Services Software Ltd',sector:'IT',cap:'mid',basePrice:5200},
  {symbol:'LUPIN',name:'Lupin Ltd',sector:'Pharma',cap:'mid',basePrice:1600},
  {symbol:'IPCALAB',name:'IPCA Laboratories Ltd',sector:'Pharma',cap:'mid',basePrice:1350},
  {symbol:'ABB',name:'ABB India Ltd',sector:'Industrial',cap:'mid',basePrice:5800},
  {symbol:'SIEMENS',name:'Siemens Ltd',sector:'Industrial',cap:'mid',basePrice:5400},
  {symbol:'HAVELLS',name:'Havells India Ltd',sector:'Consumer',cap:'mid',basePrice:1580},
  {symbol:'WHIRLPOOL',name:'Whirlpool of India Ltd',sector:'Consumer',cap:'mid',basePrice:1400},
  {symbol:'BALKRISIND',name:'Balkrishna Industries Ltd',sector:'Auto',cap:'mid',basePrice:2600},
  {symbol:'SUNDARMFIN',name:'Sundaram Finance Ltd',sector:'Finance',cap:'mid',basePrice:4200},
  {symbol:'MCDOWELL',name:'United Spirits Ltd',sector:'Consumer',cap:'mid',basePrice:6800},
  {symbol:'BERGEPAINT',name:'Berger Paints India Ltd',sector:'Consumer',cap:'mid',basePrice:550},
  {symbol:'PIDILITIND',name:'Pidilite Industries Ltd',sector:'Chemicals',cap:'mid',basePrice:2750},
  {symbol:'ATUL',name:'Atul Ltd',sector:'Chemicals',cap:'mid',basePrice:6400},
  {symbol:'SYNGENE',name:'Syngene International Ltd',sector:'Healthcare',cap:'mid',basePrice:780},
  {symbol:'ALKEM',name:'Alkem Laboratories Ltd',sector:'Pharma',cap:'mid',basePrice:5200},
  {symbol:'BANDHANBNK',name:'Bandhan Bank Ltd',sector:'Banking',cap:'mid',basePrice:220},
  {symbol:'NAUKRI',name:'Info Edge India Ltd',sector:'Internet',cap:'mid',basePrice:5400},
  {symbol:'LTIM',name:'LTIMindtree Ltd',sector:'IT',cap:'mid',basePrice:5600},
  {symbol:'PETRONET',name:'Petronet LNG Ltd',sector:'Energy',cap:'mid',basePrice:260},
  {symbol:'GLAND',name:'Gland Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:1750},
  {symbol:'NHPC',name:'NHPC Ltd',sector:'Power',cap:'mid',basePrice:68},
  {symbol:'TATAPOWER',name:'Tata Power Company Ltd',sector:'Power',cap:'mid',basePrice:420},
  {symbol:'TATACOMM',name:'Tata Communications Ltd',sector:'Telecom',cap:'mid',basePrice:1780},
  {symbol:'BIOCON',name:'Biocon Ltd',sector:'Pharma',cap:'mid',basePrice:280},
  {symbol:'LAURUSLABS',name:'Laurus Labs Ltd',sector:'Pharma',cap:'mid',basePrice:420},
  {symbol:'MANAPPURAM',name:'Manappuram Finance Ltd',sector:'Finance',cap:'mid',basePrice:180},
  {symbol:'LINDEINDIA',name:'Linde India Ltd',sector:'Chemicals',cap:'mid',basePrice:6200},
  {symbol:'AUBANK',name:'AU Small Finance Bank Ltd',sector:'Banking',cap:'mid',basePrice:650},
  {symbol:'CHOLAFIN',name:'Cholamandalam Investment and Finance Co Ltd',sector:'Finance',cap:'mid',basePrice:1350},
  {symbol:'PNB',name:'Punjab National Bank',sector:'Banking',cap:'mid',basePrice:105},
  {symbol:'BANKBARODA',name:'Bank of Baroda',sector:'Banking',cap:'mid',basePrice:260},
  {symbol:'RECLTD',name:'REC Ltd',sector:'Finance',cap:'mid',basePrice:520},
  {symbol:'PFC',name:'Power Finance Corporation Ltd',sector:'Finance',cap:'mid',basePrice:480},
  {symbol:'NMDC',name:'NMDC Ltd',sector:'Mining',cap:'mid',basePrice:220},
  {symbol:'GODREJPROP',name:'Godrej Properties Ltd',sector:'Real Estate',cap:'mid',basePrice:2200},
  {symbol:'INDUSTOWER',name:'Indus Towers Ltd',sector:'Telecom',cap:'mid',basePrice:350},
  {symbol:'ZYDUSLIFE',name:'Zydus Lifesciences Ltd',sector:'Pharma',cap:'mid',basePrice:620},
  {symbol:'APLAPOLLO',name:'APL Apollo Tubes Ltd',sector:'Industrial',cap:'mid',basePrice:1650},
  {symbol:'DEEPAKNITRI',name:'Deepak Nitrite Ltd',sector:'Chemicals',cap:'mid',basePrice:2200},
  {symbol:'SCHAEFFLER',name:'Schaeffler India Ltd',sector:'Auto',cap:'mid',basePrice:3400},
  {symbol:'HONAUT',name:'Honeywell Automation India Ltd',sector:'Industrial',cap:'mid',basePrice:48000},
  {symbol:'GLAXO',name:'GlaxoSmithKline Pharmaceuticals Ltd',sector:'Pharma',cap:'mid',basePrice:1650},
  {symbol:'STARHEALTH',name:'Star Health and Allied Insurance Co Ltd',sector:'Insurance',cap:'mid',basePrice:580},
  {symbol:'SUPREMEIND',name:'Supreme Industries Ltd',sector:'Industrial',cap:'mid',basePrice:4800},
  {symbol:'THERMAX',name:'Thermax Ltd',sector:'Industrial',cap:'mid',basePrice:3200},
  {symbol:'RATNAMANI',name:'Ratnamani Metals and Tubes Ltd',sector:'Industrial',cap:'mid',basePrice:3100},
  {symbol:'SUNDRMFAST',name:'Sundram Fasteners Ltd',sector:'Auto',cap:'mid',basePrice:1150},
  {symbol:'NATCO',name:'Natco Pharma Ltd',sector:'Pharma',cap:'mid',basePrice:880},
  {symbol:'KANSAINER',name:'Kansai Nerolac Paints Ltd',sector:'Consumer',cap:'mid',basePrice:420},
  {symbol:'JKCEMENT',name:'JK Cement Ltd',sector:'Cement',cap:'mid',basePrice:4200},
  {symbol:'TVSMOTOR',name:'TVS Motor Company Ltd',sector:'Auto',cap:'mid',basePrice:2200},
  {symbol:'ACC',name:'ACC Ltd',sector:'Cement',cap:'mid',basePrice:2450},
  {symbol:'EMAMILTD',name:'Emami Ltd',sector:'FMCG',cap:'mid',basePrice:620},
  {symbol:'PRESTIGE',name:'Prestige Estates Projects Ltd',sector:'Real Estate',cap:'mid',basePrice:1250},
  {symbol:'KAJARIACER',name:'Kajaria Ceramics Ltd',sector:'Consumer',cap:'mid',basePrice:1350},
  {symbol:'ZEEL',name:'Zee Entertainment Enterprises Ltd',sector:'Media',cap:'mid',basePrice:145},
  {symbol:'RAMCOCEM',name:'Ramco Cements Ltd',sector:'Cement',cap:'mid',basePrice:920},
  {symbol:'TATACHEM',name:'Tata Chemicals Ltd',sector:'Chemicals',cap:'mid',basePrice:1080},
  {symbol:'SUMICHEM',name:'Sumitomo Chemical India Ltd',sector:'Chemicals',cap:'mid',basePrice:420},
  {symbol:'NIACL',name:'New India Assurance Company Ltd',sector:'Insurance',cap:'mid',basePrice:195},
  {symbol:'SPARC',name:'Sun Pharma Advanced Research Company Ltd',sector:'Pharma',cap:'mid',basePrice:310},
  {symbol:'CENTRALBK',name:'Central Bank of India',sector:'Banking',cap:'mid',basePrice:62},
  {symbol:'MARICO',name:'Marico Ltd',sector:'FMCG',cap:'mid',basePrice:580},
  {symbol:'DABUR',name:'Dabur India Ltd',sector:'FMCG',cap:'mid',basePrice:560},
  {symbol:'SUNTV',name:'Sun TV Network Ltd',sector:'Media',cap:'mid',basePrice:620},
  {symbol:'APOLLOTYRE',name:'Apollo Tyres Ltd',sector:'Auto',cap:'mid',basePrice:430},
  {symbol:'FINPIPE',name:'Finolex Industries Ltd',sector:'Industrial',cap:'mid',basePrice:265},
  {symbol:'IDEA',name:'Vodafone Idea Ltd',sector:'Telecom',cap:'mid',basePrice:14},
  {symbol:'TORNTPOWER',name:'Torrent Power Ltd',sector:'Power',cap:'mid',basePrice:680},
  {symbol:'INDIANB',name:'Indian Bank',sector:'Banking',cap:'mid',basePrice:520},
  {symbol:'GICRE',name:'General Insurance Corporation of India',sector:'Insurance',cap:'mid',basePrice:340},
  {symbol:'BOSCHLTD',name:'Bosch Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:19800},
  {symbol:'MOTHERSON',name:'Samvardhana Motherson International Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:135},
  {symbol:'CGPOWER',name:'CG Power and Industrial Solutions Ltd',sector:'Industrial',cap:'mid',basePrice:520},
  {symbol:'LTTS',name:'L&T Technology Services Ltd',sector:'IT',cap:'mid',basePrice:4850},
  {symbol:'ABFRL',name:'Aditya Birla Fashion and Retail Ltd',sector:'Retail',cap:'mid',basePrice:220},
  {symbol:'IDBI',name:'IDBI Bank Ltd',sector:'Banking',cap:'mid',basePrice:82},
  {symbol:'IOC',name:'Indian Oil Corporation Ltd',sector:'Oil & Gas',cap:'mid',basePrice:145},
  {symbol:'HINDPETRO',name:'Hindustan Petroleum Corporation Ltd',sector:'Oil & Gas',cap:'mid',basePrice:310},
  {symbol:'GAIL',name:'GAIL India Ltd',sector:'Oil & Gas',cap:'mid',basePrice:185},
  {symbol:'BHEL',name:'Bharat Heavy Electricals Ltd',sector:'Industrial',cap:'mid',basePrice:265},
  {symbol:'GUJGAS',name:'Gujarat Gas Ltd',sector:'Energy',cap:'mid',basePrice:520},
  {symbol:'EXIDEIND',name:'Exide Industries Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:340},
  {symbol:'MRF',name:'MRF Ltd',sector:'Auto Ancillary',cap:'mid',basePrice:125000},
  {symbol:'BATAINDIA',name:'Bata India Ltd',sector:'Consumer',cap:'mid',basePrice:1520},
  {symbol:'LALPATHLAB',name:'Dr Lal PathLabs Ltd',sector:'Healthcare',cap:'mid',basePrice:2850},
  {symbol:'FORTIS',name:'Fortis Healthcare Ltd',sector:'Healthcare',cap:'mid',basePrice:450},
  {symbol:'GMRINFRA',name:'GMR Airports Infrastructure Ltd',sector:'Infrastructure',cap:'mid',basePrice:82},
  {symbol:'ADANIGREEN',name:'Adani Green Energy Ltd',sector:'Power',cap:'mid',basePrice:1750},
  {symbol:'ADANITRANS',name:'Adani Energy Solutions Ltd',sector:'Power',cap:'mid',basePrice:1080},
  {symbol:'VEDL',name:'Vedanta Ltd',sector:'Metals',cap:'mid',basePrice:420},
  {symbol:'NATIONALUM',name:'National Aluminium Company Ltd',sector:'Metals',cap:'mid',basePrice:165},
  {symbol:'JINDALSTL',name:'Jindal Steel and Power Ltd',sector:'Metals',cap:'mid',basePrice:880},
  {symbol:'DALBHARAT',name:'Dalmia Bharat Ltd',sector:'Cement',cap:'mid',basePrice:1950},
  {symbol:'INDIACEM',name:'India Cements Ltd',sector:'Cement',cap:'mid',basePrice:285},
  {symbol:'LLOYDSME',name:'Lloyds Metals and Energy Ltd',sector:'Metals',cap:'mid',basePrice:780},
  {symbol:'CANFINHOME',name:'Can Fin Homes Ltd',sector:'Finance',cap:'mid',basePrice:780},
  {symbol:'IIFL',name:'IIFL Finance Ltd',sector:'Finance',cap:'mid',basePrice:480},
  {symbol:'LTFH',name:'L&T Finance Ltd',sector:'Finance',cap:'mid',basePrice:155},
  {symbol:'COROMANDEL',name:'Coromandel International Ltd',sector:'Fertilizer',cap:'mid',basePrice:1250},
  {symbol:'GNFC',name:'Gujarat Narmada Valley Fertilizers and Chemicals Ltd',sector:'Fertilizer',cap:'mid',basePrice:620},
  {symbol:'CHAMBALFERT',name:'Chambal Fertilisers and Chemicals Ltd',sector:'Fertilizer',cap:'mid',basePrice:345},
  {symbol:'HINDCOPPER',name:'Hindustan Copper Ltd',sector:'Mining',cap:'mid',basePrice:255},
  {symbol:'IREDA',name:'Indian Renewable Energy Development Agency Ltd',sector:'Finance',cap:'mid',basePrice:185},
  {symbol:'HUDCO',name:'Housing and Urban Development Corporation Ltd',sector:'Finance',cap:'mid',basePrice:220},
  {symbol:'SUZLON',name:'Suzlon Energy Ltd',sector:'Power',cap:'mid',basePrice:52},
  {symbol:'JSPL',name:'Jindal Stainless Ltd',sector:'Metals',cap:'mid',basePrice:620},
  {symbol:'KEI',name:'KEI Industries Ltd',sector:'Industrial',cap:'mid',basePrice:3800},
  {symbol:'TRIDENT',name:'Trident Ltd',sector:'Textiles',cap:'mid',basePrice:38},
  {symbol:'SUVENPHAR',name:'Suven Pharmaceuticals Ltd',sector:'Pharma',cap:'mid',basePrice:580},
  {symbol:'JSWINFRA',name:'JSW Infrastructure Ltd',sector:'Infrastructure',cap:'mid',basePrice:260},
  {symbol:'SOBHA',name:'Sobha Ltd',sector:'Real Estate',cap:'mid',basePrice:1550},
  {symbol:'BRIGADE',name:'Brigade Enterprises Ltd',sector:'Real Estate',cap:'mid',basePrice:1180},
  {symbol:'TTML',name:'Tata Teleservices Maharashtra Ltd',sector:'Telecom',cap:'mid',basePrice:85},
  {symbol:'MOTILALOFS',name:'Motilal Oswal Financial Services Ltd',sector:'Finance',cap:'mid',basePrice:1850},

  // ===== SMALL CAP (250 stocks) - Nifty Smallcap 250 Constituents =====
  {symbol:'CDSL',name:'Central Depository Services India Ltd',sector:'Fintech',cap:'small',basePrice:1800},
  {symbol:'KPITTECH',name:'KPIT Technologies Ltd',sector:'IT',cap:'small',basePrice:1450},
  {symbol:'DEEPAKNTR',name:'Deepak Fertilisers and Petrochemicals Ltd',sector:'Chemicals',cap:'small',basePrice:2200},
  {symbol:'MAZDOCK',name:'Mazagon Dock Shipbuilders Ltd',sector:'Defence',cap:'small',basePrice:3800},
  {symbol:'BEL',name:'Bharat Electronics Ltd',sector:'Defence',cap:'small',basePrice:280},
  {symbol:'HAL',name:'Hindustan Aeronautics Ltd',sector:'Defence',cap:'small',basePrice:4200},
  {symbol:'COCHINSHIP',name:'Cochin Shipyard Ltd',sector:'Shipping',cap:'small',basePrice:1800},
  {symbol:'IRFC',name:'Indian Railway Finance Corporation Ltd',sector:'Finance',cap:'small',basePrice:160},
  {symbol:'ZOMATO',name:'Zomato Ltd',sector:'Internet',cap:'small',basePrice:240},
  {symbol:'PAYTM',name:'One97 Communications Ltd',sector:'Fintech',cap:'small',basePrice:780},
  {symbol:'JIOFIN',name:'Jio Financial Services Ltd',sector:'Fintech',cap:'small',basePrice:310},
  {symbol:'POLICYBZR',name:'PB Fintech Ltd',sector:'Fintech',cap:'small',basePrice:1650},
  {symbol:'DELHIVERY',name:'Delhivery Ltd',sector:'Logistics',cap:'small',basePrice:420},
  {symbol:'AFFLE',name:'Affle India Ltd',sector:'IT',cap:'small',basePrice:1180},
  {symbol:'CLEAN',name:'Clean Science and Technology Ltd',sector:'Chemicals',cap:'small',basePrice:1500},
  {symbol:'FINEORG',name:'Fine Organic Industries Ltd',sector:'Chemicals',cap:'small',basePrice:4800},
  {symbol:'FCL',name:'Fineotex Chemical Ltd',sector:'Chemicals',cap:'small',basePrice:85},
  {symbol:'GRINDWELL',name:'Grindwell Norton Ltd',sector:'Industrial',cap:'small',basePrice:2100},
  {symbol:'HAPPSTMNDS',name:'Happiest Minds Technologies Ltd',sector:'IT',cap:'small',basePrice:780},
  {symbol:'ROUTE',name:'Route Mobile Ltd',sector:'IT',cap:'small',basePrice:1650},
  {symbol:'TANLA',name:'Tanla Platforms Ltd',sector:'IT',cap:'small',basePrice:920},
  {symbol:'DATAPATTNS',name:'Data Patterns India Ltd',sector:'Defence',cap:'small',basePrice:2400},
  {symbol:'IDEAFORGE',name:'Ideaforge Technology Ltd',sector:'Defence',cap:'small',basePrice:680},
  {symbol:'SYRMA',name:'Syrma SGS Technology Ltd',sector:'Electronics',cap:'small',basePrice:420},
  {symbol:'KAYNES',name:'Kaynes Technology India Ltd',sector:'Electronics',cap:'small',basePrice:3800},
  {symbol:'DIXON',name:'Dixon Technologies India Ltd',sector:'Electronics',cap:'small',basePrice:5200},
  {symbol:'AMBER',name:'Amber Enterprises India Ltd',sector:'Electronics',cap:'small',basePrice:3400},
  {symbol:'OLECTRA',name:'Olectra Greentech Ltd',sector:'EV',cap:'small',basePrice:1350},
  {symbol:'TATAELXSI',name:'Tata Elxsi Ltd',sector:'IT',cap:'small',basePrice:6800},
  {symbol:'SONACOMS',name:'Sona BLW Precision Forgings Ltd',sector:'Auto',cap:'small',basePrice:620},
  {symbol:'CRAFTSMAN',name:'Craftsman Automation Ltd',sector:'Auto',cap:'small',basePrice:4800},
  {symbol:'CARTRADE',name:'CarTrade Tech Ltd',sector:'Internet',cap:'small',basePrice:820},
  {symbol:'YATHARTH',name:'Yatharth Hospital and Trauma Care Services Ltd',sector:'Healthcare',cap:'small',basePrice:520},
  {symbol:'MEDANTA',name:'Global Health Ltd',sector:'Healthcare',cap:'small',basePrice:1350},
  {symbol:'RAINBOW',name:'Rainbow Childrens Medicare Ltd',sector:'Healthcare',cap:'small',basePrice:1450},
  {symbol:'AAVAS',name:'Aavas Financiers Ltd',sector:'Finance',cap:'small',basePrice:1650},
  {symbol:'HOMEFIRST',name:'Home First Finance Company India Ltd',sector:'Finance',cap:'small',basePrice:950},
  {symbol:'APTUS',name:'Aptus Value Housing Finance India Ltd',sector:'Finance',cap:'small',basePrice:340},
  {symbol:'CAMPUS',name:'Campus Activewear Ltd',sector:'Consumer',cap:'small',basePrice:280},
  {symbol:'METROBRAND',name:'Metro Brands Ltd',sector:'Retail',cap:'small',basePrice:1250},
  {symbol:'GPIL',name:'Godawari Power and Ispat Ltd',sector:'Metals',cap:'small',basePrice:680},
  {symbol:'RVNL',name:'Rail Vikas Nigam Ltd',sector:'Infrastructure',cap:'small',basePrice:260},
  {symbol:'IRCON',name:'Ircon International Ltd',sector:'Infrastructure',cap:'small',basePrice:220},
  {symbol:'NBCC',name:'NBCC India Ltd',sector:'Infrastructure',cap:'small',basePrice:140},
  {symbol:'ENGINERSIN',name:'Engineers India Ltd',sector:'Infrastructure',cap:'small',basePrice:210},
  {symbol:'EASEMYTRIP',name:'Easy Trip Planners Ltd',sector:'Internet',cap:'small',basePrice:38},
  {symbol:'IXIGO',name:'Le Travenues Technology Ltd',sector:'Internet',cap:'small',basePrice:155},
  {symbol:'RATEGAIN',name:'RateGain Travel Technologies Ltd',sector:'IT',cap:'small',basePrice:680},
  {symbol:'LATENTVIEW',name:'Latent View Analytics Ltd',sector:'IT',cap:'small',basePrice:420},
  {symbol:'INTELLECT',name:'Intellect Design Arena Ltd',sector:'IT',cap:'small',basePrice:780},
  {symbol:'MASTEK',name:'Mastek Ltd',sector:'IT',cap:'small',basePrice:2600},
  {symbol:'BIRLASOFT',name:'Birlasoft Ltd',sector:'IT',cap:'small',basePrice:580},
  {symbol:'ZENSAR',name:'Zensar Technologies Ltd',sector:'IT',cap:'small',basePrice:520},
  {symbol:'NUVAMA',name:'Nuvama Wealth Management Ltd',sector:'Finance',cap:'small',basePrice:5200},
  {symbol:'ANGELONE',name:'Angel One Ltd',sector:'Fintech',cap:'small',basePrice:2800},
  {symbol:'CAMS',name:'Computer Age Management Services Ltd',sector:'Fintech',cap:'small',basePrice:3200},
  {symbol:'JBCHEPHARM',name:'JB Chemicals and Pharmaceuticals Ltd',sector:'Pharma',cap:'small',basePrice:1750},
  {symbol:'SUPRIYA',name:'Supriya Lifescience Ltd',sector:'Pharma',cap:'small',basePrice:480},
  {symbol:'LXCHEM',name:'Laxmi Organic Industries Ltd',sector:'Chemicals',cap:'small',basePrice:280},
  {symbol:'TATVA',name:'Tatva Chintan Pharma Chem Ltd',sector:'Chemicals',cap:'small',basePrice:1850},
  {symbol:'GALAXYSURF',name:'Galaxy Surfactants Ltd',sector:'Chemicals',cap:'small',basePrice:2800},
  {symbol:'FLUOROCHEM',name:'Gujarat Fluorochemicals Ltd',sector:'Chemicals',cap:'small',basePrice:3200},
  {symbol:'ANANDRATHI',name:'Anand Rathi Wealth Ltd',sector:'Finance',cap:'small',basePrice:4200},
  {symbol:'FIVESTAR',name:'Five-Star Business Finance Ltd',sector:'Finance',cap:'small',basePrice:780},
  {symbol:'JKLAKSHMI',name:'JK Lakshmi Cement Ltd',sector:'Cement',cap:'small',basePrice:820},
  {symbol:'STARCEMENT',name:'Star Cement Ltd',sector:'Cement',cap:'small',basePrice:210},
  {symbol:'RADICO',name:'Radico Khaitan Ltd',sector:'Consumer',cap:'small',basePrice:1650},
  {symbol:'GLOBUSSPR',name:'Globus Spirits Ltd',sector:'Consumer',cap:'small',basePrice:1050},
  {symbol:'SAPPHIRE',name:'Sapphire Foods India Ltd',sector:'Consumer',cap:'small',basePrice:1450},
  {symbol:'DEVYANI',name:'Devyani International Ltd',sector:'Consumer',cap:'small',basePrice:165},
  {symbol:'SHOPERSTOP',name:'Shoppers Stop Ltd',sector:'Retail',cap:'small',basePrice:780},
  {symbol:'VMART',name:'V-Mart Retail Ltd',sector:'Retail',cap:'small',basePrice:2200},
  {symbol:'TEGA',name:'Tega Industries Ltd',sector:'Industrial',cap:'small',basePrice:1450},
  {symbol:'CERA',name:'Cera Sanitaryware Ltd',sector:'Consumer',cap:'small',basePrice:7200},
  {symbol:'ELGIEQUIP',name:'Elgi Equipments Ltd',sector:'Industrial',cap:'small',basePrice:580},
  {symbol:'TIMKEN',name:'Timken India Ltd',sector:'Industrial',cap:'small',basePrice:3400},
  {symbol:'PRAJ',name:'Praj Industries Ltd',sector:'Industrial',cap:'small',basePrice:520},
  {symbol:'GPPL',name:'Gujarat Pipavav Port Ltd',sector:'Logistics',cap:'small',basePrice:165},
  {symbol:'TCI',name:'Transport Corporation of India Ltd',sector:'Logistics',cap:'small',basePrice:880},
  {symbol:'BLUESTARCO',name:'Blue Star Ltd',sector:'Consumer',cap:'small',basePrice:1250},
  {symbol:'CENTURYTEX',name:'Century Textiles and Industries Ltd',sector:'Textiles',cap:'small',basePrice:1650},
  {symbol:'RAYMOND',name:'Raymond Ltd',sector:'Textiles',cap:'small',basePrice:1850},
  {symbol:'TVSSRICHAK',name:'TVS Srichakra Ltd',sector:'Auto',cap:'small',basePrice:3200},
  {symbol:'GRSE',name:'Garden Reach Shipbuilders and Engineers Ltd',sector:'Defence',cap:'small',basePrice:2100},
  {symbol:'BDL',name:'Bharat Dynamics Ltd',sector:'Defence',cap:'small',basePrice:1250},
  {symbol:'JSWENERGY',name:'JSW Energy Ltd',sector:'Power',cap:'small',basePrice:480},
  {symbol:'SJVN',name:'SJVN Ltd',sector:'Power',cap:'small',basePrice:120},
  {symbol:'POWERMECH',name:'Power Mech Projects Ltd',sector:'Infrastructure',cap:'small',basePrice:4800},
  {symbol:'PRICOLLTD',name:'Pricol Ltd',sector:'Auto',cap:'small',basePrice:480},
  {symbol:'ELECON',name:'Elecon Engineering Company Ltd',sector:'Industrial',cap:'small',basePrice:580},
  {symbol:'SENCO',name:'Senco Gold Ltd',sector:'Consumer',cap:'small',basePrice:1050},
  {symbol:'KALYANKJIL',name:'Kalyan Jewellers India Ltd',sector:'Consumer',cap:'small',basePrice:480},
  {symbol:'NETWORK18',name:'Network18 Media and Investments Ltd',sector:'Media',cap:'small',basePrice:82},
  {symbol:'NAZARA',name:'Nazara Technologies Ltd',sector:'Media',cap:'small',basePrice:780},
  {symbol:'PVRINOX',name:'PVR INOX Ltd',sector:'Media',cap:'small',basePrice:1450},
  {symbol:'ZAGGLE',name:'Zaggle Prepaid Ocean Services Ltd',sector:'Fintech',cap:'small',basePrice:340},
  {symbol:'RBLBANK',name:'RBL Bank Ltd',sector:'Banking',cap:'small',basePrice:240},
  {symbol:'UJJIVANSFB',name:'Ujjivan Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:48},
  {symbol:'EQUITASBNK',name:'Equitas Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:95},
  {symbol:'NYKAA',name:'FSN E-Commerce Ventures Ltd',sector:'Internet',cap:'small',basePrice:175},
  {symbol:'EIDPARRY',name:'EID Parry India Ltd',sector:'Sugar',cap:'small',basePrice:620},
  {symbol:'BALRAMCHIN',name:'Balrampur Chini Mills Ltd',sector:'Sugar',cap:'small',basePrice:420},
  {symbol:'RENUKA',name:'Shree Renuka Sugars Ltd',sector:'Sugar',cap:'small',basePrice:48},
  {symbol:'TRIVENI',name:'Triveni Engineering and Industries Ltd',sector:'Sugar',cap:'small',basePrice:380},
  {symbol:'DHAMPUR',name:'Dhampur Sugar Mills Ltd',sector:'Sugar',cap:'small',basePrice:220},
  {symbol:'AVALON',name:'Avalon Technologies Ltd',sector:'Electronics',cap:'small',basePrice:520},
  {symbol:'HBLPOWER',name:'HBL Power Systems Ltd',sector:'Electronics',cap:'small',basePrice:580},
  {symbol:'NELCO',name:'Nelco Ltd',sector:'Electronics',cap:'small',basePrice:850},
  {symbol:'MIDHANI',name:'Mishra Dhatu Nigam Ltd',sector:'Defence',cap:'small',basePrice:380},
  {symbol:'PARAS',name:'Paras Defence and Space Technologies Ltd',sector:'Defence',cap:'small',basePrice:920},
  {symbol:'DCXINDIA',name:'DCX Systems Ltd',sector:'Defence',cap:'small',basePrice:310},
  {symbol:'ASTRAZEN',name:'AstraZeneca Pharma India Ltd',sector:'Pharma',cap:'small',basePrice:5800},
  {symbol:'ERIS',name:'Eris Lifesciences Ltd',sector:'Pharma',cap:'small',basePrice:920},
  {symbol:'AJANTPHARM',name:'Ajanta Pharma Ltd',sector:'Pharma',cap:'small',basePrice:2400},
  {symbol:'GRANULES',name:'Granules India Ltd',sector:'Pharma',cap:'small',basePrice:380},
  {symbol:'SOLARA',name:'Solara Active Pharma Sciences Ltd',sector:'Pharma',cap:'small',basePrice:420},
  {symbol:'MARKSANS',name:'Marksans Pharma Ltd',sector:'Pharma',cap:'small',basePrice:155},
  {symbol:'SHILPAMED',name:'Shilpa Medicare Ltd',sector:'Pharma',cap:'small',basePrice:520},
  {symbol:'CAPLIPOINT',name:'Caplin Point Laboratories Ltd',sector:'Pharma',cap:'small',basePrice:1350},
  {symbol:'NEULANDLAB',name:'Neuland Laboratories Ltd',sector:'Pharma',cap:'small',basePrice:6200},
  {symbol:'WINDLAS',name:'Windlas Biotech Ltd',sector:'Pharma',cap:'small',basePrice:680},
  {symbol:'DELTACORP',name:'Delta Corp Ltd',sector:'Hotels',cap:'small',basePrice:180},
  {symbol:'LEMONTREE',name:'Lemon Tree Hotels Ltd',sector:'Hotels',cap:'small',basePrice:135},
  {symbol:'CHALET',name:'Chalet Hotels Ltd',sector:'Hotels',cap:'small',basePrice:680},
  {symbol:'EIHOTEL',name:'EIH Ltd',sector:'Hotels',cap:'small',basePrice:310},
  {symbol:'JUNIPER',name:'Juniper Hotels Ltd',sector:'Hotels',cap:'small',basePrice:420},
  {symbol:'INTERGLOBE',name:'InterGlobe Aviation Ltd',sector:'Aviation',cap:'small',basePrice:4200},
  {symbol:'SPICEJET',name:'SpiceJet Ltd',sector:'Aviation',cap:'small',basePrice:62},
  {symbol:'SAFARI',name:'Safari Industries India Ltd',sector:'Consumer',cap:'small',basePrice:2400},
  {symbol:'VGUARD',name:'V-Guard Industries Ltd',sector:'Consumer',cap:'small',basePrice:420},
  {symbol:'SYMPHONY',name:'Symphony Ltd',sector:'Consumer',cap:'small',basePrice:1050},
  {symbol:'ORIENTELEC',name:'Orient Electric Ltd',sector:'Consumer',cap:'small',basePrice:280},
  {symbol:'TTKHLTCARE',name:'TTK Healthcare Ltd',sector:'Consumer',cap:'small',basePrice:1250},
  {symbol:'BAJAJELEC',name:'Bajaj Electricals Ltd',sector:'Consumer',cap:'small',basePrice:1180},
  {symbol:'STOVEKRAFT',name:'Stove Kraft Ltd',sector:'Consumer',cap:'small',basePrice:680},
  {symbol:'JYOTHY',name:'Jyothy Labs Ltd',sector:'FMCG',cap:'small',basePrice:420},
  {symbol:'BIKAJI',name:'Bikaji Foods International Ltd',sector:'FMCG',cap:'small',basePrice:650},
  {symbol:'GODFRYPHLP',name:'Godfrey Phillips India Ltd',sector:'FMCG',cap:'small',basePrice:4800},
  {symbol:'KRBL',name:'KRBL Ltd',sector:'FMCG',cap:'small',basePrice:310},
  {symbol:'HATSUN',name:'Hatsun Agro Product Ltd',sector:'FMCG',cap:'small',basePrice:1050},
  {symbol:'WESTLIFE',name:'Westlife Foodworld Ltd',sector:'Consumer',cap:'small',basePrice:780},
  {symbol:'BARBEQUE',name:'Barbeque-Nation Hospitality Ltd',sector:'Consumer',cap:'small',basePrice:520},
  {symbol:'MAHLIFE',name:'Mahindra Lifespace Developers Ltd',sector:'Real Estate',cap:'small',basePrice:520},
  {symbol:'SUNTECK',name:'Sunteck Realty Ltd',sector:'Real Estate',cap:'small',basePrice:480},
  {symbol:'KOLTEPATIL',name:'Kolte-Patil Developers Ltd',sector:'Real Estate',cap:'small',basePrice:420},
  {symbol:'ANANTRAJ',name:'Anant Raj Ltd',sector:'Real Estate',cap:'small',basePrice:580},
  {symbol:'PURVA',name:'Puravankara Ltd',sector:'Real Estate',cap:'small',basePrice:380},
  {symbol:'ASHOKA',name:'Ashoka Buildcon Ltd',sector:'Infrastructure',cap:'small',basePrice:220},
  {symbol:'KNR',name:'KNR Constructions Ltd',sector:'Infrastructure',cap:'small',basePrice:310},
  {symbol:'PNCINFRA',name:'PNC Infratech Ltd',sector:'Infrastructure',cap:'small',basePrice:380},
  {symbol:'HCC',name:'Hindustan Construction Company Ltd',sector:'Infrastructure',cap:'small',basePrice:38},
  {symbol:'NLCINDIA',name:'NLC India Ltd',sector:'Power',cap:'small',basePrice:245},
  {symbol:'CESC',name:'CESC Ltd',sector:'Power',cap:'small',basePrice:155},
  {symbol:'JPPOWER',name:'Jaiprakash Power Ventures Ltd',sector:'Power',cap:'small',basePrice:18},
  {symbol:'RPOWER',name:'Reliance Power Ltd',sector:'Power',cap:'small',basePrice:42},
  {symbol:'INOXWIND',name:'Inox Wind Ltd',sector:'Power',cap:'small',basePrice:155},
  {symbol:'MAHSEAMLES',name:'Maharashtra Seamless Ltd',sector:'Metals',cap:'small',basePrice:780},
  {symbol:'WELCORP',name:'Welspun Corp Ltd',sector:'Metals',cap:'small',basePrice:520},
  {symbol:'MOIL',name:'MOIL Ltd',sector:'Mining',cap:'small',basePrice:340},
  {symbol:'KIOCL',name:'KIOCL Ltd',sector:'Mining',cap:'small',basePrice:280},
  {symbol:'HLEGLAS',name:'HLE Glascoat Ltd',sector:'Industrial',cap:'small',basePrice:520},
  {symbol:'TDPOWERSYS',name:'TD Power Systems Ltd',sector:'Industrial',cap:'small',basePrice:420},
  {symbol:'AIAENG',name:'AIA Engineering Ltd',sector:'Industrial',cap:'small',basePrice:3800},
  {symbol:'KENNAMETAL',name:'Kennametal India Ltd',sector:'Industrial',cap:'small',basePrice:2400},
  {symbol:'CARBORUNIV',name:'Carborundum Universal Ltd',sector:'Industrial',cap:'small',basePrice:1250},
  {symbol:'ISGEC',name:'Isgec Heavy Engineering Ltd',sector:'Industrial',cap:'small',basePrice:780},
  {symbol:'TRIVENIGR',name:'Triveni Turbine Ltd',sector:'Industrial',cap:'small',basePrice:480},
  {symbol:'ESABINDIA',name:'ESAB India Ltd',sector:'Industrial',cap:'small',basePrice:5800},
  {symbol:'GARFIBRES',name:'Garware Technical Fibres Ltd',sector:'Industrial',cap:'small',basePrice:3200},
  {symbol:'MAPMYINDIA',name:'CE Info Systems Ltd',sector:'IT',cap:'small',basePrice:1850},
  {symbol:'QUICKHEAL',name:'Quick Heal Technologies Ltd',sector:'IT',cap:'small',basePrice:520},
  {symbol:'NUCLEUS',name:'Nucleus Software Exports Ltd',sector:'IT',cap:'small',basePrice:1050},
  {symbol:'NEWGEN',name:'Newgen Software Technologies Ltd',sector:'IT',cap:'small',basePrice:920},
  {symbol:'CYIENT',name:'Cyient Ltd',sector:'IT',cap:'small',basePrice:1750},
  {symbol:'NIITLTD',name:'NIIT Ltd',sector:'IT',cap:'small',basePrice:480},
  {symbol:'KFINTECH',name:'KFin Technologies Ltd',sector:'Fintech',cap:'small',basePrice:680},
  {symbol:'UTIAMC',name:'UTI Asset Management Company Ltd',sector:'Finance',cap:'small',basePrice:820},
  {symbol:'HDFCAMC',name:'HDFC Asset Management Company Ltd',sector:'Finance',cap:'small',basePrice:3800},
  {symbol:'MASFIN',name:'MAS Financial Services Ltd',sector:'Finance',cap:'small',basePrice:780},
  {symbol:'CREDITACC',name:'CreditAccess Grameen Ltd',sector:'Finance',cap:'small',basePrice:1150},
  {symbol:'FUSION',name:'Fusion Micro Finance Ltd',sector:'Finance',cap:'small',basePrice:420},
  {symbol:'SPANDANA',name:'Spandana Sphoorty Financial Ltd',sector:'Finance',cap:'small',basePrice:780},
  {symbol:'SBFC',name:'SBFC Finance Ltd',sector:'Finance',cap:'small',basePrice:82},
  {symbol:'ESAFSFB',name:'ESAF Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:55},
  {symbol:'SURYODAY',name:'Suryoday Small Finance Bank Ltd',sector:'Banking',cap:'small',basePrice:135},
  {symbol:'DCBBANK',name:'DCB Bank Ltd',sector:'Banking',cap:'small',basePrice:125},
  {symbol:'KARUR',name:'Karur Vysya Bank Ltd',sector:'Banking',cap:'small',basePrice:185},
  {symbol:'SOUTHBANK',name:'South Indian Bank Ltd',sector:'Banking',cap:'small',basePrice:28},
  {symbol:'GLENMARK',name:'Glenmark Pharmaceuticals Ltd',sector:'Pharma',cap:'small',basePrice:1080},
  {symbol:'SANOFI',name:'Sanofi India Ltd',sector:'Pharma',cap:'small',basePrice:6800},
  {symbol:'PFIZER',name:'Pfizer Ltd',sector:'Pharma',cap:'small',basePrice:4200},
  {symbol:'ABBOTINDIA',name:'Abbott India Ltd',sector:'Pharma',cap:'small',basePrice:24000},
  {symbol:'NOCIL',name:'NOCIL Ltd',sector:'Chemicals',cap:'small',basePrice:260},
  {symbol:'ALKYLAMINE',name:'Alkyl Amines Chemicals Ltd',sector:'Chemicals',cap:'small',basePrice:2200},
  {symbol:'NAVINFLUOR',name:'Navin Fluorine International Ltd',sector:'Chemicals',cap:'small',basePrice:3400},
  {symbol:'SRF',name:'SRF Ltd',sector:'Chemicals',cap:'small',basePrice:2400},
  {symbol:'VINATI',name:'Vinati Organics Ltd',sector:'Chemicals',cap:'small',basePrice:1850},
  {symbol:'ANUPAM',name:'Anupam Rasayan India Ltd',sector:'Chemicals',cap:'small',basePrice:820},
  {symbol:'ROSSARI',name:'Rossari Biotech Ltd',sector:'Chemicals',cap:'small',basePrice:780},
  {symbol:'AARTIIND',name:'Aarti Industries Ltd',sector:'Chemicals',cap:'small',basePrice:580},
  {symbol:'NEOGEN',name:'Neogen Chemicals Ltd',sector:'Chemicals',cap:'small',basePrice:1450},
  {symbol:'ORIENTCEM',name:'Orient Cement Ltd',sector:'Cement',cap:'small',basePrice:195},
  {symbol:'HEIDELBERG',name:'Heidelberg Cement India Ltd',sector:'Cement',cap:'small',basePrice:210},
  {symbol:'PRISMJOHN',name:'Prism Johnson Ltd',sector:'Cement',cap:'small',basePrice:155},
  {symbol:'BIRLACORPN',name:'Birla Corporation Ltd',sector:'Cement',cap:'small',basePrice:1350},
  {symbol:'SAGARCEM',name:'Sagar Cements Ltd',sector:'Cement',cap:'small',basePrice:220},
  {symbol:'WELSPUNIND',name:'Welspun Living Ltd',sector:'Textiles',cap:'small',basePrice:155},
  {symbol:'ARVIND',name:'Arvind Ltd',sector:'Textiles',cap:'small',basePrice:380},
  {symbol:'KPR',name:'KPR Mill Ltd',sector:'Textiles',cap:'small',basePrice:780},
  {symbol:'GOKEX',name:'Gokaldas Exports Ltd',sector:'Textiles',cap:'small',basePrice:820},
  {symbol:'HIMATSEIDE',name:'Himatsingka Seide Ltd',sector:'Textiles',cap:'small',basePrice:155},
  {symbol:'LAXMIMACH',name:'Lakshmi Machine Works Ltd',sector:'Textiles',cap:'small',basePrice:15800},
  {symbol:'SUPRAJIT',name:'Suprajit Engineering Ltd',sector:'Auto Ancillary',cap:'small',basePrice:420},
  {symbol:'ENDURANCE',name:'Endurance Technologies Ltd',sector:'Auto Ancillary',cap:'small',basePrice:1850},
  {symbol:'MINDA',name:'Uno Minda Ltd',sector:'Auto Ancillary',cap:'small',basePrice:780},
  {symbol:'LUMAXTECH',name:'Lumax Auto Technologies Ltd',sector:'Auto Ancillary',cap:'small',basePrice:480},
  {symbol:'SANDHAR',name:'Sandhar Technologies Ltd',sector:'Auto Ancillary',cap:'small',basePrice:520},
  {symbol:'GABRIEL',name:'Gabriel India Ltd',sector:'Auto Ancillary',cap:'small',basePrice:380},
  {symbol:'VARROC',name:'Varroc Engineering Ltd',sector:'Auto Ancillary',cap:'small',basePrice:520},
  {symbol:'JAMNAAUTO',name:'Jamna Auto Industries Ltd',sector:'Auto Ancillary',cap:'small',basePrice:120},
  {symbol:'HFCL',name:'HFCL Ltd',sector:'Telecom',cap:'small',basePrice:95},
  {symbol:'STLTECH',name:'Sterlite Technologies Ltd',sector:'Telecom',cap:'small',basePrice:155},
  {symbol:'TEJAS',name:'Tejas Networks Ltd',sector:'Telecom',cap:'small',basePrice:920},
  {symbol:'RAILTEL',name:'RailTel Corporation of India Ltd',sector:'Telecom',cap:'small',basePrice:380},
  {symbol:'GESHIP',name:'Great Eastern Shipping Company Ltd',sector:'Shipping',cap:'small',basePrice:1050},
  {symbol:'SCI',name:'Shipping Corporation of India Ltd',sector:'Shipping',cap:'small',basePrice:220},
  {symbol:'ALLCARGO',name:'Allcargo Logistics Ltd',sector:'Logistics',cap:'small',basePrice:380},
  {symbol:'BLUEDART',name:'Blue Dart Express Ltd',sector:'Logistics',cap:'small',basePrice:6800},
  {symbol:'VRLLOG',name:'VRL Logistics Ltd',sector:'Logistics',cap:'small',basePrice:520},
  {symbol:'RITES',name:'RITES Ltd',sector:'Infrastructure',cap:'small',basePrice:520},
  {symbol:'BEML',name:'BEML Ltd',sector:'Infrastructure',cap:'small',basePrice:3800},
  {symbol:'TIINDIA',name:'Tube Investments of India Ltd',sector:'Industrial',cap:'small',basePrice:3400},
  {symbol:'MMTC',name:'MMTC Ltd',sector:'Mining',cap:'small',basePrice:72},
  {symbol:'DEEPIND',name:'Deep Industries Ltd',sector:'Oil & Gas',cap:'small',basePrice:520},
  {symbol:'MRPL',name:'Mangalore Refinery and Petrochemicals Ltd',sector:'Oil & Gas',cap:'small',basePrice:155},
  {symbol:'CHENNPETRO',name:'Chennai Petroleum Corporation Ltd',sector:'Oil & Gas',cap:'small',basePrice:680},
  {symbol:'IGL',name:'Indraprastha Gas Ltd',sector:'Oil & Gas',cap:'small',basePrice:480},
  {symbol:'MGL',name:'Mahanagar Gas Ltd',sector:'Oil & Gas',cap:'small',basePrice:1350},
  {symbol:'TCPLPACK',name:'TCPL Packaging Ltd',sector:'Packaging',cap:'small',basePrice:2400},
  {symbol:'HUHTAMAKI',name:'Huhtamaki India Ltd',sector:'Packaging',cap:'small',basePrice:320},
  {symbol:'UFLEX',name:'Uflex Ltd',sector:'Packaging',cap:'small',basePrice:520},
  {symbol:'EPL',name:'EPL Ltd',sector:'Packaging',cap:'small',basePrice:195},
  {symbol:'JKPAPER',name:'JK Paper Ltd',sector:'Paper',cap:'small',basePrice:380},
  {symbol:'TNPL',name:'Tamil Nadu Newsprint and Papers Ltd',sector:'Paper',cap:'small',basePrice:280},
  {symbol:'ANDHRAPAP',name:'Andhra Paper Ltd',sector:'Paper',cap:'small',basePrice:420},
  {symbol:'RCF',name:'Rashtriya Chemicals and Fertilizers Ltd',sector:'Fertilizer',cap:'small',basePrice:145},
  {symbol:'NFL',name:'National Fertilizers Ltd',sector:'Fertilizer',cap:'small',basePrice:92},
  {symbol:'GSFC',name:'Gujarat State Fertilizers and Chemicals Ltd',sector:'Fertilizer',cap:'small',basePrice:175},
  {symbol:'FACT',name:'Fertilisers and Chemicals Travancore Ltd',sector:'Fertilizer',cap:'small',basePrice:680},
  {symbol:'ZUARI',name:'Zuari Agro Chemicals Ltd',sector:'Fertilizer',cap:'small',basePrice:310},
  {symbol:'GOLD1-E',name:'Nippon India Gold ETF',sector:'Commodity ETF',cap:'small',basePrice:113},
  {symbol:'SILVERIETF-E',name:'ICICI Prudential Silver ETF',sector:'Commodity ETF',cap:'small',basePrice:165}
];
