const NASDAQ_STOCKS = [
  // === LARGE CAP (100 stocks) — NASDAQ-100 Constituents ===
  {symbol:'AAPL',name:'Apple Inc.',sector:'Technology',cap:'large',basePrice:195,currency:'$'},
  {symbol:'MSFT',name:'Microsoft Corporation',sector:'Technology',cap:'large',basePrice:430,currency:'$'},
  {symbol:'GOOGL',name:'Alphabet Inc.',sector:'Technology',cap:'large',basePrice:175,currency:'$'},
  {symbol:'AMZN',name:'Amazon.com Inc.',sector:'E-Commerce',cap:'large',basePrice:185,currency:'$'},
  {symbol:'NVDA',name:'NVIDIA Corporation',sector:'Semiconductors',cap:'large',basePrice:135,currency:'$'},
  {symbol:'META',name:'Meta Platforms Inc.',sector:'Technology',cap:'large',basePrice:510,currency:'$'},
  {symbol:'TSLA',name:'Tesla Inc.',sector:'Auto/EV',cap:'large',basePrice:250,currency:'$'},
  {symbol:'AVGO',name:'Broadcom Inc.',sector:'Semiconductors',cap:'large',basePrice:165,currency:'$'},
  {symbol:'COST',name:'Costco Wholesale Corporation',sector:'Retail',cap:'large',basePrice:720,currency:'$'},
  {symbol:'NFLX',name:'Netflix Inc.',sector:'Entertainment',cap:'large',basePrice:630,currency:'$'},
  {symbol:'AMD',name:'Advanced Micro Devices Inc.',sector:'Semiconductors',cap:'large',basePrice:155,currency:'$'},
  {symbol:'ADBE',name:'Adobe Inc.',sector:'Software',cap:'large',basePrice:530,currency:'$'},
  {symbol:'PEP',name:'PepsiCo Inc.',sector:'Consumer',cap:'large',basePrice:175,currency:'$'},
  {symbol:'INTC',name:'Intel Corporation',sector:'Semiconductors',cap:'large',basePrice:32,currency:'$'},
  {symbol:'CMCSA',name:'Comcast Corporation',sector:'Media',cap:'large',basePrice:42,currency:'$'},
  {symbol:'QCOM',name:'Qualcomm Inc.',sector:'Semiconductors',cap:'large',basePrice:175,currency:'$'},
  {symbol:'INTU',name:'Intuit Inc.',sector:'Software',cap:'large',basePrice:620,currency:'$'},
  {symbol:'AMAT',name:'Applied Materials Inc.',sector:'Semiconductors',cap:'large',basePrice:195,currency:'$'},
  {symbol:'ISRG',name:'Intuitive Surgical Inc.',sector:'Healthcare',cap:'large',basePrice:400,currency:'$'},
  {symbol:'BKNG',name:'Booking Holdings Inc.',sector:'Travel',cap:'large',basePrice:3800,currency:'$'},
  {symbol:'LRCX',name:'Lam Research Corporation',sector:'Semiconductors',cap:'large',basePrice:920,currency:'$'},
  {symbol:'MU',name:'Micron Technology Inc.',sector:'Semiconductors',cap:'large',basePrice:110,currency:'$'},
  {symbol:'REGN',name:'Regeneron Pharmaceuticals Inc.',sector:'Biotech',cap:'large',basePrice:980,currency:'$'},
  {symbol:'KLAC',name:'KLA Corporation',sector:'Semiconductors',cap:'large',basePrice:680,currency:'$'},
  {symbol:'PANW',name:'Palo Alto Networks Inc.',sector:'Cybersecurity',cap:'large',basePrice:310,currency:'$'},
  {symbol:'SNPS',name:'Synopsys Inc.',sector:'Software',cap:'large',basePrice:540,currency:'$'},
  {symbol:'CDNS',name:'Cadence Design Systems Inc.',sector:'Software',cap:'large',basePrice:290,currency:'$'},
  {symbol:'MRVL',name:'Marvell Technology Inc.',sector:'Semiconductors',cap:'large',basePrice:72,currency:'$'},
  {symbol:'ABNB',name:'Airbnb Inc.',sector:'Travel',cap:'large',basePrice:150,currency:'$'},
  {symbol:'FTNT',name:'Fortinet Inc.',sector:'Cybersecurity',cap:'large',basePrice:75,currency:'$'},
  {symbol:'CRWD',name:'CrowdStrike Holdings Inc.',sector:'Cybersecurity',cap:'large',basePrice:320,currency:'$'},
  {symbol:'DDOG',name:'Datadog Inc.',sector:'Cloud',cap:'large',basePrice:125,currency:'$'},
  {symbol:'ZS',name:'Zscaler Inc.',sector:'Cybersecurity',cap:'large',basePrice:220,currency:'$'},
  {symbol:'LULU',name:'Lululemon Athletica Inc.',sector:'Retail',cap:'large',basePrice:420,currency:'$'},
  {symbol:'MDLZ',name:'Mondelez International Inc.',sector:'Consumer',cap:'large',basePrice:72,currency:'$'},
  {symbol:'GILD',name:'Gilead Sciences Inc.',sector:'Biotech',cap:'large',basePrice:85,currency:'$'},
  {symbol:'AMGN',name:'Amgen Inc.',sector:'Biotech',cap:'large',basePrice:290,currency:'$'},
  {symbol:'ADP',name:'Automatic Data Processing Inc.',sector:'Technology',cap:'large',basePrice:265,currency:'$'},
  {symbol:'CSX',name:'CSX Corporation',sector:'Technology',cap:'large',basePrice:35,currency:'$'},
  {symbol:'SBUX',name:'Starbucks Corporation',sector:'QSR',cap:'large',basePrice:95,currency:'$'},
  {symbol:'MNST',name:'Monster Beverage Corporation',sector:'Consumer',cap:'large',basePrice:56,currency:'$'},
  {symbol:'PYPL',name:'PayPal Holdings Inc.',sector:'Fintech',cap:'large',basePrice:65,currency:'$'},
  {symbol:'ORLY',name:'O\'Reilly Automotive Inc.',sector:'Retail',cap:'large',basePrice:1050,currency:'$'},
  {symbol:'CEG',name:'Constellation Energy Corp.',sector:'Technology',cap:'large',basePrice:180,currency:'$'},
  {symbol:'MELI',name:'MercadoLibre Inc.',sector:'E-Commerce',cap:'large',basePrice:1680,currency:'$'},
  {symbol:'TEAM',name:'Atlassian Corporation',sector:'Software',cap:'large',basePrice:240,currency:'$'},
  {symbol:'WDAY',name:'Workday Inc.',sector:'Cloud',cap:'large',basePrice:270,currency:'$'},
  {symbol:'CTAS',name:'Cintas Corporation',sector:'Consumer',cap:'large',basePrice:620,currency:'$'},
  {symbol:'VRSK',name:'Verisk Analytics Inc.',sector:'Technology',cap:'large',basePrice:245,currency:'$'},
  {symbol:'ROP',name:'Roper Technologies Inc.',sector:'Technology',cap:'large',basePrice:560,currency:'$'},
  {symbol:'ODFL',name:'Old Dominion Freight Line Inc.',sector:'Technology',cap:'large',basePrice:420,currency:'$'},
  {symbol:'IDXX',name:'IDEXX Laboratories Inc.',sector:'Healthcare',cap:'large',basePrice:520,currency:'$'},
  {symbol:'FAST',name:'Fastenal Company',sector:'Retail',cap:'large',basePrice:72,currency:'$'},
  {symbol:'EA',name:'Electronic Arts Inc.',sector:'Gaming',cap:'large',basePrice:140,currency:'$'},
  {symbol:'ANSS',name:'ANSYS Inc.',sector:'Software',cap:'large',basePrice:330,currency:'$'},
  {symbol:'DXCM',name:'DexCom Inc.',sector:'Healthcare',cap:'large',basePrice:120,currency:'$'},
  {symbol:'PCAR',name:'PACCAR Inc.',sector:'Auto/EV',cap:'large',basePrice:95,currency:'$'},
  {symbol:'CPRT',name:'Copart Inc.',sector:'Technology',cap:'large',basePrice:48,currency:'$'},
  {symbol:'ROST',name:'Ross Stores Inc.',sector:'Retail',cap:'large',basePrice:145,currency:'$'},
  {symbol:'PAYX',name:'Paychex Inc.',sector:'Technology',cap:'large',basePrice:120,currency:'$'},
  {symbol:'KDP',name:'Keurig Dr Pepper Inc.',sector:'Consumer',cap:'large',basePrice:35,currency:'$'},
  {symbol:'AZN',name:'AstraZeneca PLC',sector:'Biotech',cap:'large',basePrice:70,currency:'$'},
  {symbol:'NXPI',name:'NXP Semiconductors NV',sector:'Semiconductors',cap:'large',basePrice:230,currency:'$'},
  {symbol:'GEHC',name:'GE HealthCare Technologies Inc.',sector:'Healthcare',cap:'large',basePrice:82,currency:'$'},
  {symbol:'EXC',name:'Exelon Corporation',sector:'Technology',cap:'large',basePrice:42,currency:'$'},
  {symbol:'XEL',name:'Xcel Energy Inc.',sector:'Technology',cap:'large',basePrice:62,currency:'$'},
  {symbol:'ON',name:'ON Semiconductor Corp.',sector:'Semiconductors',cap:'large',basePrice:72,currency:'$'},
  {symbol:'CDW',name:'CDW Corporation',sector:'Technology',cap:'large',basePrice:230,currency:'$'},
  {symbol:'TTWO',name:'Take-Two Interactive Software',sector:'Gaming',cap:'large',basePrice:165,currency:'$'},
  {symbol:'WBD',name:'Warner Bros. Discovery Inc.',sector:'Media',cap:'large',basePrice:12,currency:'$'},
  {symbol:'FANG',name:'Diamondback Energy Inc.',sector:'Technology',cap:'large',basePrice:165,currency:'$'},
  {symbol:'BKR',name:'Baker Hughes Company',sector:'Technology',cap:'large',basePrice:35,currency:'$'},
  {symbol:'GFS',name:'GlobalFoundries Inc.',sector:'Semiconductors',cap:'large',basePrice:55,currency:'$'},
  {symbol:'MCHP',name:'Microchip Technology Inc.',sector:'Semiconductors',cap:'large',basePrice:80,currency:'$'},
  {symbol:'DASH',name:'DoorDash Inc.',sector:'Technology',cap:'large',basePrice:125,currency:'$'},
  {symbol:'ARM',name:'Arm Holdings PLC',sector:'Semiconductors',cap:'large',basePrice:130,currency:'$'},
  {symbol:'SMCI',name:'Super Micro Computer Inc.',sector:'Hardware',cap:'large',basePrice:45,currency:'$'},
  {symbol:'BIIB',name:'Biogen Inc.',sector:'Biotech',cap:'large',basePrice:220,currency:'$'},
  {symbol:'MRNA',name:'Moderna Inc.',sector:'Biotech',cap:'large',basePrice:105,currency:'$'},
  {symbol:'HON',name:'Honeywell International Inc.',sector:'Technology',cap:'large',basePrice:200,currency:'$'},
  {symbol:'DLTR',name:'Dollar Tree Inc.',sector:'Retail',cap:'large',basePrice:135,currency:'$'},
  {symbol:'ILMN',name:'Illumina Inc.',sector:'Healthcare',cap:'large',basePrice:130,currency:'$'},
  {symbol:'CHTR',name:'Charter Communications Inc.',sector:'Media',cap:'large',basePrice:380,currency:'$'},
  {symbol:'MAR',name:'Marriott International Inc.',sector:'Travel',cap:'large',basePrice:240,currency:'$'},
  {symbol:'AEP',name:'American Electric Power Co.',sector:'Technology',cap:'large',basePrice:88,currency:'$'},
  {symbol:'CTSH',name:'Cognizant Technology Solutions',sector:'Technology',cap:'large',basePrice:75,currency:'$'},
  {symbol:'VRTX',name:'Vertex Pharmaceuticals Inc.',sector:'Biotech',cap:'large',basePrice:410,currency:'$'},
  {symbol:'PDD',name:'PDD Holdings Inc.',sector:'E-Commerce',cap:'large',basePrice:125,currency:'$'},
  {symbol:'LCID',name:'Lucid Group Inc.',sector:'Auto/EV',cap:'large',basePrice:4,currency:'$'},
  {symbol:'ASML',name:'ASML Holding NV',sector:'Semiconductors',cap:'large',basePrice:710,currency:'$'},
  {symbol:'TMUS',name:'T-Mobile US Inc.',sector:'Technology',cap:'large',basePrice:165,currency:'$'},
  {symbol:'ADI',name:'Analog Devices Inc.',sector:'Semiconductors',cap:'large',basePrice:205,currency:'$'},
  {symbol:'TXN',name:'Texas Instruments Inc.',sector:'Semiconductors',cap:'large',basePrice:175,currency:'$'},
  {symbol:'SIRI',name:'Sirius XM Holdings Inc.',sector:'Media',cap:'large',basePrice:4,currency:'$'},
  {symbol:'MTCH',name:'Match Group Inc.',sector:'Internet',cap:'large',basePrice:38,currency:'$'},
  {symbol:'MSTR',name:'MicroStrategy Inc.',sector:'Technology',cap:'large',basePrice:480,currency:'$'},
  {symbol:'ENPH',name:'Enphase Energy Inc.',sector:'Technology',cap:'large',basePrice:120,currency:'$'},
  {symbol:'WBA',name:'Walgreens Boots Alliance Inc.',sector:'Healthcare',cap:'large',basePrice:22,currency:'$'},
  {symbol:'ZM',name:'Zoom Video Communications Inc.',sector:'Cloud',cap:'large',basePrice:68,currency:'$'},
  {symbol:'ALGN',name:'Align Technology Inc.',sector:'Healthcare',cap:'large',basePrice:280,currency:'$'},
  // === MID CAP (50 stocks) — NASDAQ Mid-Caps ($10B-$50B) ===
  {symbol:'SNOW',name:'Snowflake Inc.',sector:'Cloud',cap:'mid',basePrice:165,currency:'$'},
  {symbol:'TTD',name:'The Trade Desk Inc.',sector:'AdTech',cap:'mid',basePrice:85,currency:'$'},
  {symbol:'NET',name:'Cloudflare Inc.',sector:'Cloud',cap:'mid',basePrice:95,currency:'$'},
  {symbol:'OKTA',name:'Okta Inc.',sector:'Cybersecurity',cap:'mid',basePrice:105,currency:'$'},
  {symbol:'HUBS',name:'HubSpot Inc.',sector:'Software',cap:'mid',basePrice:580,currency:'$'},
  {symbol:'MDB',name:'MongoDB Inc.',sector:'Cloud',cap:'mid',basePrice:280,currency:'$'},
  {symbol:'COIN',name:'Coinbase Global Inc.',sector:'Fintech',cap:'mid',basePrice:220,currency:'$'},
  {symbol:'ROKU',name:'Roku Inc.',sector:'Entertainment',cap:'mid',basePrice:65,currency:'$'},
  {symbol:'DKNG',name:'DraftKings Inc.',sector:'Gaming',cap:'mid',basePrice:38,currency:'$'},
  {symbol:'RIVN',name:'Rivian Automotive Inc.',sector:'Auto/EV',cap:'mid',basePrice:14,currency:'$'},
  {symbol:'MNDY',name:'Monday.com Ltd.',sector:'Software',cap:'mid',basePrice:250,currency:'$'},
  {symbol:'BILL',name:'BILL Holdings Inc.',sector:'Fintech',cap:'mid',basePrice:72,currency:'$'},
  {symbol:'CELH',name:'Celsius Holdings Inc.',sector:'Consumer',cap:'mid',basePrice:55,currency:'$'},
  {symbol:'PATH',name:'UiPath Inc.',sector:'Software',cap:'mid',basePrice:15,currency:'$'},
  {symbol:'CRSP',name:'CRISPR Therapeutics AG',sector:'Biotech',cap:'mid',basePrice:55,currency:'$'},
  {symbol:'TWLO',name:'Twilio Inc.',sector:'Cloud',cap:'mid',basePrice:65,currency:'$'},
  {symbol:'PINS',name:'Pinterest Inc.',sector:'Internet',cap:'mid',basePrice:35,currency:'$'},
  {symbol:'LYFT',name:'Lyft Inc.',sector:'Ride-hailing',cap:'mid',basePrice:18,currency:'$'},
  {symbol:'RBLX',name:'Roblox Corporation',sector:'Gaming',cap:'mid',basePrice:42,currency:'$'},
  {symbol:'ETSY',name:'Etsy Inc.',sector:'E-Commerce',cap:'mid',basePrice:75,currency:'$'},
  {symbol:'ZI',name:'ZoomInfo Technologies Inc.',sector:'Software',cap:'mid',basePrice:20,currency:'$'},
  {symbol:'SPLK',name:'Splunk Inc.',sector:'Software',cap:'mid',basePrice:155,currency:'$'},
  {symbol:'DOCN',name:'DigitalOcean Holdings Inc.',sector:'Cloud',cap:'mid',basePrice:35,currency:'$'},
  {symbol:'CFLT',name:'Confluent Inc.',sector:'Cloud',cap:'mid',basePrice:28,currency:'$'},
  {symbol:'GTLB',name:'GitLab Inc.',sector:'Software',cap:'mid',basePrice:55,currency:'$'},
  {symbol:'PCOR',name:'Procore Technologies Inc.',sector:'Software',cap:'mid',basePrice:68,currency:'$'},
  {symbol:'VEEV',name:'Veeva Systems Inc.',sector:'Cloud',cap:'mid',basePrice:195,currency:'$'},
  {symbol:'TOST',name:'Toast Inc.',sector:'Fintech',cap:'mid',basePrice:25,currency:'$'},
  {symbol:'NTNX',name:'Nutanix Inc.',sector:'Cloud',cap:'mid',basePrice:55,currency:'$'},
  {symbol:'ESTC',name:'Elastic NV',sector:'Software',cap:'mid',basePrice:110,currency:'$'},
  {symbol:'CYBR',name:'CyberArk Software Ltd.',sector:'Cybersecurity',cap:'mid',basePrice:240,currency:'$'},
  {symbol:'PAYC',name:'Paycom Software Inc.',sector:'Software',cap:'mid',basePrice:195,currency:'$'},
  {symbol:'PCTY',name:'Paylocity Holding Corp.',sector:'Software',cap:'mid',basePrice:165,currency:'$'},
  {symbol:'ENSG',name:'Ensign Group Inc.',sector:'Healthcare',cap:'mid',basePrice:115,currency:'$'},
  {symbol:'EXAS',name:'Exact Sciences Corporation',sector:'Healthcare',cap:'mid',basePrice:72,currency:'$'},
  {symbol:'MANH',name:'Manhattan Associates Inc.',sector:'Software',cap:'mid',basePrice:220,currency:'$'},
  {symbol:'TYL',name:'Tyler Technologies Inc.',sector:'Software',cap:'mid',basePrice:450,currency:'$'},
  {symbol:'FIVE',name:'Five Below Inc.',sector:'Retail',cap:'mid',basePrice:145,currency:'$'},
  {symbol:'CHWY',name:'Chewy Inc.',sector:'E-Commerce',cap:'mid',basePrice:28,currency:'$'},
  {symbol:'SMAR',name:'Smartsheet Inc.',sector:'Software',cap:'mid',basePrice:48,currency:'$'},
  {symbol:'QLYS',name:'Qualys Inc.',sector:'Cybersecurity',cap:'mid',basePrice:155,currency:'$'},
  {symbol:'TRMB',name:'Trimble Inc.',sector:'Technology',cap:'mid',basePrice:58,currency:'$'},
  {symbol:'WIX',name:'Wix.com Ltd.',sector:'Internet',cap:'mid',basePrice:145,currency:'$'},
  {symbol:'PODD',name:'Insulet Corporation',sector:'Healthcare',cap:'mid',basePrice:175,currency:'$'},
  {symbol:'FLEX',name:'Flex Ltd.',sector:'Hardware',cap:'mid',basePrice:28,currency:'$'},
  {symbol:'SWAV',name:'Shockwave Medical Inc.',sector:'Healthcare',cap:'mid',basePrice:330,currency:'$'},
  {symbol:'LSCC',name:'Lattice Semiconductor Corp.',sector:'Semiconductors',cap:'mid',basePrice:72,currency:'$'},
  {symbol:'GLOB',name:'Globant S.A.',sector:'Technology',cap:'mid',basePrice:195,currency:'$'},
  {symbol:'AZPN',name:'Aspen Technology Inc.',sector:'Software',cap:'mid',basePrice:210,currency:'$'},
  {symbol:'FRSH',name:'Freshworks Inc.',sector:'Software',cap:'mid',basePrice:18,currency:'$'},
  // === SMALL CAP (50 stocks) — NASDAQ Small-Caps (< $10B) ===
  {symbol:'IONQ',name:'IonQ Inc.',sector:'Quantum Computing',cap:'small',basePrice:18,currency:'$'},
  {symbol:'RKLB',name:'Rocket Lab USA Inc.',sector:'Aerospace',cap:'small',basePrice:22,currency:'$'},
  {symbol:'SOUN',name:'SoundHound AI Inc.',sector:'AI',cap:'small',basePrice:8,currency:'$'},
  {symbol:'JOBY',name:'Joby Aviation Inc.',sector:'Aerospace',cap:'small',basePrice:6.5,currency:'$'},
  {symbol:'DNA',name:'Ginkgo Bioworks Holdings Inc.',sector:'Biotech',cap:'small',basePrice:12,currency:'$'},
  {symbol:'PLTR',name:'Palantir Technologies Inc.',sector:'AI',cap:'small',basePrice:24,currency:'$'},
  {symbol:'SOFI',name:'SoFi Technologies Inc.',sector:'Fintech',cap:'small',basePrice:9,currency:'$'},
  {symbol:'GRAB',name:'Grab Holdings Ltd.',sector:'Ride-hailing',cap:'small',basePrice:3.8,currency:'$'},
  {symbol:'HOOD',name:'Robinhood Markets Inc.',sector:'Fintech',cap:'small',basePrice:18,currency:'$'},
  {symbol:'AFRM',name:'Affirm Holdings Inc.',sector:'Fintech',cap:'small',basePrice:42,currency:'$'},
  {symbol:'UPST',name:'Upstart Holdings Inc.',sector:'Fintech',cap:'small',basePrice:28,currency:'$'},
  {symbol:'U',name:'Unity Software Inc.',sector:'Gaming',cap:'small',basePrice:22,currency:'$'},
  {symbol:'RDDT',name:'Reddit Inc.',sector:'Internet',cap:'small',basePrice:55,currency:'$'},
  {symbol:'DUOL',name:'Duolingo Inc.',sector:'EdTech',cap:'small',basePrice:220,currency:'$'},
  {symbol:'APP',name:'AppLovin Corporation',sector:'AdTech',cap:'small',basePrice:85,currency:'$'},
  {symbol:'CAVA',name:'CAVA Group Inc.',sector:'QSR',cap:'small',basePrice:75,currency:'$'},
  {symbol:'BMBL',name:'Bumble Inc.',sector:'Internet',cap:'small',basePrice:15,currency:'$'},
  {symbol:'SKLZ',name:'Skillz Inc.',sector:'Gaming',cap:'small',basePrice:7,currency:'$'},
  {symbol:'OPEN',name:'Opendoor Technologies Inc.',sector:'Technology',cap:'small',basePrice:3.5,currency:'$'},
  {symbol:'ASAN',name:'Asana Inc.',sector:'Software',cap:'small',basePrice:18,currency:'$'},
  {symbol:'GDRX',name:'GoodRx Holdings Inc.',sector:'Healthcare',cap:'small',basePrice:7,currency:'$'},
  {symbol:'BIGC',name:'BigCommerce Holdings Inc.',sector:'E-Commerce',cap:'small',basePrice:8,currency:'$'},
  {symbol:'WKHS',name:'Workhorse Group Inc.',sector:'Auto/EV',cap:'small',basePrice:1.2,currency:'$'},
  {symbol:'LAZR',name:'Luminar Technologies Inc.',sector:'Auto/EV',cap:'small',basePrice:4,currency:'$'},
  {symbol:'VLD',name:'Velo3D Inc.',sector:'Technology',cap:'small',basePrice:2.5,currency:'$'},
  {symbol:'MAPS',name:'WM Technology Inc.',sector:'Technology',cap:'small',basePrice:1.8,currency:'$'},
  {symbol:'SEAT',name:'Vivid Seats Inc.',sector:'Entertainment',cap:'small',basePrice:6,currency:'$'},
  {symbol:'BRZE',name:'Braze Inc.',sector:'Software',cap:'small',basePrice:45,currency:'$'},
  {symbol:'NNOX',name:'Nano-X Imaging Ltd.',sector:'Healthcare',cap:'small',basePrice:12,currency:'$'},
  {symbol:'QBTS',name:'D-Wave Quantum Inc.',sector:'Quantum Computing',cap:'small',basePrice:3,currency:'$'},
  {symbol:'RGTI',name:'Rigetti Computing Inc.',sector:'Quantum Computing',cap:'small',basePrice:2,currency:'$'},
  {symbol:'ARQT',name:'Arcus Biosciences Inc.',sector:'Biotech',cap:'small',basePrice:18,currency:'$'},
  {symbol:'CIFR',name:'Cipher Mining Inc.',sector:'Technology',cap:'small',basePrice:5,currency:'$'},
  {symbol:'ASTS',name:'AST SpaceMobile Inc.',sector:'Aerospace',cap:'small',basePrice:15,currency:'$'},
  {symbol:'LUNR',name:'Intuitive Machines Inc.',sector:'Aerospace',cap:'small',basePrice:8,currency:'$'},
  {symbol:'RDW',name:'Redwire Corporation',sector:'Aerospace',cap:'small',basePrice:6,currency:'$'},
  {symbol:'SMWB',name:'Similarweb Ltd.',sector:'Software',cap:'small',basePrice:10,currency:'$'},
  {symbol:'TASK',name:'TaskUs Inc.',sector:'Technology',cap:'small',basePrice:14,currency:'$'},
  {symbol:'DLO',name:'DLocal Ltd.',sector:'Fintech',cap:'small',basePrice:12,currency:'$'},
  {symbol:'VERX',name:'Vertex Inc.',sector:'Software',cap:'small',basePrice:25,currency:'$'},
  {symbol:'CWAN',name:'Clearwater Analytics Holdings',sector:'Fintech',cap:'small',basePrice:20,currency:'$'},
  {symbol:'RELY',name:'Remitly Global Inc.',sector:'Fintech',cap:'small',basePrice:18,currency:'$'},
  {symbol:'KARO',name:'Karooooo Ltd.',sector:'Technology',cap:'small',basePrice:35,currency:'$'},
  {symbol:'BLZE',name:'Backblaze Inc.',sector:'Cloud',cap:'small',basePrice:9,currency:'$'},
  {symbol:'PRCT',name:'PROCEPT BioRobotics Corp.',sector:'Healthcare',cap:'small',basePrice:55,currency:'$'},
  {symbol:'AEHR',name:'Aehr Test Systems',sector:'Semiconductors',cap:'small',basePrice:18,currency:'$'},
  {symbol:'VERV',name:'Verve Therapeutics Inc.',sector:'Biotech',cap:'small',basePrice:8,currency:'$'},
  {symbol:'MGNI',name:'Magnite Inc.',sector:'AdTech',cap:'small',basePrice:12,currency:'$'},
  {symbol:'INDI',name:'Indie Semiconductor Inc.',sector:'Semiconductors',cap:'small',basePrice:7,currency:'$'},
  {symbol:'BTDR',name:'Bitdeer Technologies Group',sector:'Technology',cap:'small',basePrice:10,currency:'$'}
];
